### ISSUE TITLE
Missing URIs for China

### ISSUE THREAD

**Issue by franklesniak** [MicrosoftDocs/office-docs-powershell#4830] opened 2020-02-05 00:16 UTC
The URIs for China are missing from this page. I do not have access to a China tenant, but I believe they are:

ConnectionUri parameter value:
https://partner.outlook.cn/PowerShell-LiveID

AzureADAuthorizationEndPointUri parameter value:
https://login.chinacloudapi.cn/common

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e527db-a4c2-782e-5a5f-ad8b3159a977
* Version Independent ID: f2de1272-5e37-c59f-fcb9-34fa66b0d268
* Content: [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment] 2020-02-05 09:50
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment] 2020-02-06 01:47
@franklesniak, are we sure that China/21Vianet event supports using the MFA module for Exchange Online PowerShell? In late 2017, we removed the China/21Vianet information from the topic (on TechNet at the time) per internal instruction because the MFA module didn't work with China/21Vianet organizations.

Has something changed?

**Comment by franklesniak** [comment] 2020-02-09 21:10
Chris, you might be right about China/21Vianet not supporting MFA - unfortunately, I do not have access to a China tenant to confirm or deny.

Let me explain what I am trying to do, though:
I'm writing a function that uses the Exchange Online v2 module to connect to Exchange. I want to support the different Office 365 "environments" (GCC High, China, Germany, etc.). To do that, I need to specify the PowerShell connection URI and the Azure AD Authorization Endpoint URI when I run Connect-ExchangeOnline.

To that point, this page "Connect to Exchange Online PowerShell using multi-factor authentication" seems to be the most-authoritative source for these URIs, but the China ones are absent.

Maybe the right thing to do is to spin up a new page for Exchange Online v2 that lists the URIs without tying them back to the use of MFA?

**Comment by yogkumgit** [comment] 2020-02-11 13:31
@chrisda Please reply. Thanks

**Comment by chrisda** [comment] 2020-02-11 18:53
@franklesniak, I can dig it. But, as I described, China/21Vianet doesn't support MFA, so no need to update the topic that's the target of this issue. Semi-relatedly, I confirmed a long time ago that there's no such thing as standalone Exchange Online Protection PowerShell in China/21Vianet, so the [EOP PowerShell connection topic](https://docs.microsoft.com/powershell/exchange/exchange-eop/connect-to-exchange-online-protection-powershell) doesn't contain a China ConnectionUri value, but it does have a Germany value.

As for the EXO V2 module, if you think there is missing information in it, I encourage you to open an Issue on that specific topic and/or send email to the EXO V2 module alias: exocmdletpreview[at]service[dot]microsoft[dot]com.

Thanks for the feedback.

**Comment by victorguo** [comment] 2020-02-25 07:12
@franklesniak I tested several months ago #4581 and found that EXO V2 didn't support national clouds yet. Are they supported now?

@chrisda But, using EXO V1 with oAuth (modern authentication) without MFA, we still need the ConnectionUri and AzureADAuthorizationEndPointUri for China. How can we know the URLs?

**Comment by franklesniak** [comment] 2020-02-25 15:25
Looks like they might have just added support? Hot off the presses:

https://office365itpros.com/2020/02/25/microsoft-updates-exchange-online-management-powershell-module/amp/

**Comment by victorguo** [comment] 2020-02-25 16:17
@franklesniak Thanks for the info. But I just tried. Still no luck.

**Comment by chrisda** [comment] 2020-02-27 18:51
@victorguo, I don't understand your question to me. You're trying to use the MFA module to connect to a tenant in China/21Vianet, but you aren't using MFA, just Modern Auth? I would suggest you reach out to 21Vianet for answers and to see if that's even possible. If you find anything, no need to re-open this Issue; just update the topic directly as described [here](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md).

if you have questions about the ExO V2 module, please use their feedback channel at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

Closing.

**Closed by chrisda** 2020-02-27 18:51 UTC
Labels: area:exchange
