### ISSUE TITLE
Not Working in Sharepoint 2016

### ISSUE THREAD

**Issue by SurabhiGupta2808** [MicrosoftDocs/office-docs-powershell#3234] opened 2019-04-17 12:35 UTC
Hello Team,

I am using SharePoint 2016 server and after connected using to site when i hit get -pnpuser it through error 
**Connect-PnPOnline -Url "XYz" -CurrentCredentials
Get-PnPUser**

Error :---

Get-PnPUser : Field or property "Alerts" does not exist.
At line:1 char:1
+ Get-PnPUser
+ ~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPUser], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Principals.GetUser
> EXCEPTION,SharePointPnP.PowerShell.Commands.Principals.GetUser

**Comment by yogkumgit** [comment] 2019-04-18 11:54
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2019-05-03 14:46
Hello @SurabhiGupta2808 
Thanks for your feedback.
As you may know, this issue resource is spefically to address issues within documentation. Besides that, I tested and could not reproduce the error. I do not identify that a change in documentation needs to be done.
Thank you!

**Comment by VesaJuvonen** [comment] 2019-05-13 06:25
Closing based on the comment from @get-itips. Root cause most likely is using of SharePoint Online targeted PnP cmdlets for SP2016 as there are difference set of capabilities supported cross different versions of SharePoint.

**Closed by VesaJuvonen** 2019-05-13 06:25 UTC
