### ISSUE TITLE
Add-TeamChannelUser -Role owner fails on shared channel

### ISSUE THREAD

**Issue by kleilu** [MicrosoftDocs/office-docs-powershell#10249] opened 2022-12-15 10:10 UTC
Running:  "Add-TeamChannelUser -groupid $teamid -DisplayName $kanaal -User $eigenaar -Role Owner" on a shared channel fails.

1. Channel is newly created
2. ChannelUser is already created before promoting to owner

Error message:
Add-TeamChannelUser : Error occurred while executing
Code: BadRequest
Message: $filter query is not supported while fetching members of shared channels.
InnerError:
  RequestId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
  DateTimeStamp: 2022-12-15T10:00:44
HttpStatusCode: BadRequest
At line:1 char:1
+ Add-TeamChannelUser -groupid "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-TeamChannelUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Teams.PowerShell.TeamsCmdlets.ErrorHandling.ApiException,Microsoft.Teams.PowerShell.TeamsCmdlets.AddTeamChannelUser

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd91d571-ca88-5766-2666-d6a4d34cdbed
* Version Independent ID: 2481b258-b593-e323-90f0-e9ca6e7797bf
* Content: [Add-TeamChannelUser (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Add-TeamChannelUser.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by stovakor** [comment] 2022-12-20 19:10
Microsoft Case # 33149197
I submitted this case about this exact issue on 9/29.

The issue is also on Remove-TeamChannelUser

**Comment by get-itips** [comment] 2022-12-22 19:58
Tested in 4.9.1 and it works, closing as here we are limited to documentation issues.
Thank you

**Closed by get-itips** 2022-12-22 19:58 UTC
Labels: area:teams
