### ISSUE TITLE
IgnoreLegalHold no longer available?

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/office-docs-powershell#6449] opened 2020-09-01 15:49 UTC
It seems that the -IgnoreLegalHold parameter is no longer available, can you please confirm and update the article accordingly? Or clarify/rephrase the below:

"Note: This parameter is not available or functional on users objects in Exchange Online."

Is it available for *some* objects only, can you clarify how can we invoke it and maybe add an example? 

In any case it doesnt even seem to be available in the definition of the Disable-Mailbox cmdlet, at least according to Get-ManagementRole :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb358499-22a0-fa5c-c577-540de0049ddc
* Version Independent ID: 1c7960eb-3661-e96c-a9d7-18218256d6a1
* Content: [Disable-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/disable-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Disable-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Disable-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by michevnew** [comment] 2020-09-01 15:54
Well, I was pointed to this: https://docs.microsoft.com/en-us/office365/troubleshoot/holds/ignorelegalhold-not-available
Should we maybe merge the articles? :)

**Comment by chrisda** [comment] 2020-09-01 16:42
@michevnew, the "not available or functional" text was used because at the time, the parameter was still _available_ but it didn't work.

So are you saying the parameter is completely gone now?

**Comment by michevnew** [comment] 2020-09-02 08:01
It's not available in any of the tenants I tried, and according to the article above it should have been removed.

**Comment by chrisda** [comment] 2020-09-03 21:28
@michevnew, confirmed. I added "This parameter is available only in on-premises Exchange" to the IgnoreLegalHold parameter description in the following topics:

- Disable-Mailbox
- Remove-Mailbox
- Remove-MailUser

Thanks for the feedback.

Closing

**Closed by chrisda** 2020-09-03 21:28 UTC
Labels: area:exchange
