### ISSUE TITLE
Exchange Online V2 PowerShell module - Microsoft's code signing certificate expired

### ISSUE THREAD

**Issue by dejanforo** [MicrosoftDocs/office-docs-powershell#5686] opened 2020-05-24 18:19 UTC
Microsoft code singing certificate which is used to sign the Exchange Online V2 PowerShell module code has expired on May 2nd 2020 

<img width="303" alt="Microsoft code signing certificate expired" src="https://user-images.githubusercontent.com/53783806/82761511-52386080-9dfb-11ea-8d5f-b615360d8d93.png">

**Comment by yogkumgit** [comment] 2020-05-25 10:32
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment] 2020-05-25 16:53
Hi @dejanforo, thank you for your feedback.

I couldn't reproduce this behaviour.

The Exchange Online PowerShell V2 module is currently in Preview. If you have any feedback, concerns, or are facing any issues with the EXO V2 module, contact us at exocmdletpreview[at]service[dot]microsoft[dot]com (email address intentionally obscured to help prevent spam).

When you report an issue, be sure to include the log files in your email message.

To generate the log files, replace <Path to store log file> with the output folder you want, and run the following command:
_Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All_

**Comment by yogkumgit** [comment] 2020-05-26 10:54
@dariomws  Thank you very much for the contribution and sharing this explanation. @dejanforo 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-05-26 10:54 UTC
Labels: area:exchange
