### ISSUE TITLE
Description missing for PersonalAccountsEnabled

### ISSUE THREAD

**Issue by jalrok** [MicrosoftDocs/office-docs-powershell#10279] opened 2022-12-22 20:04 UTC
Published description for PersonalAccountsEnabled contains placeholder text.

"
-PersonalAccountsEnabled
     This parameter is available only in the cloud-based service.

     {{ Fill PersonalAccountsEnabled Description }}
"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 022da80e-29cd-f6b5-aa00-48e2d16c4be8
* Version Independent ID: c3353c03-e416-f693-104f-6b6f5955b721
* Content: [Set-OwaMailboxPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-12-27 18:39
@jalrok, I'm tempted to resolve this as a duplicate of #10276.

Same question: are you being directed to use this parameter from other content, or are you just pointing out the fact that it's empty?

**Closed** 2023-01-16 13:52 UTC
Labels: duplicate, area:exchange, Empty parameter description
