### ISSUE TITLE
Need to update couple of Rule parameter Limits.

### ISSUE THREAD

**Issue by MithunRathinam** [MicrosoftDocs/office-docs-powershell#10556] opened 2023-03-02 15:29 UTC
Hi Team,

Please update below Transport rule parameter Limits .

1) -RejectMessageReasonText 
The actual Limit is 1024 characters .

2) -GenerateNotification
The actual Limit is 5120 Characters.

Regards,
Mithun Rathinam.
Exchange Beta Engineer

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11bf4f19-ce5b-b13a-7c93-c627cd49cc35
* Version Independent ID: 17e31a5a-7b8f-9139-c2c4-4a819e2cde7e
* Content: [New-TransportRule (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/new-transportrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-TransportRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-TransportRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2023-03-02 17:36
Closing as duplicate of #10557 (updated parameters in both cmdlet topics).

**Closed by chrisda** 2023-03-02 17:36 UTC
Labels: Microsoft submitter
