### ISSUE TITLE
Where Filter does not always work

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#9529] opened 2022-06-09 19:24 UTC
My back is against the wall after downloading 4.4.1 and discovering that the deprecation of the LdapFilter parameter seems imminent.  With no traction on getting the -Filter to support wildcards for Identity (-Filter "Identity -like '00*'"), I'm resorting to using the PowerShell "Where" command to do my filtering, knowing that scripts are going to run 4 times slower.  Unfortunately, when testing to ensure that I get the same number of users with my new Where usage, vs what we used to get with the -LdapFilter, I've noticed that I'm missing a bunch of users.

For example, the following works

PS D:\Docs\PS\SFBO> Get-CsOnlineUser -Identity 'AATest@unimaxlab.com' | select displayname,Identity

DisplayName Identity
- - - - - - - - - - 
AA Test     687592fc-585a-4d93-b7cb-f88bb370d0bf

PS D:\Docs\PS\SFBO> Get-CsOnlineUser | Where {$_.Identity -like '68*'} | Select Identity,DisplayName

Identity                             DisplayName
- - - -                              - - - - - -
687592fc-585a-4d93-b7cb-f88bb370d0bf AA Test
68101823-ba48-44ce-9693-59d6401efd12 Matthew Lillard

But other instances, expected data is not returned

PS D:\Docs\PS\SFBO> Get-CsOnlineUser -Identity 'awinsor1@unimaxlab.com' | select Identity,DisplayName

Identity                             DisplayName
- - - -                              - - - - - -
b375a020-8db8-46b8-b9a0-40282bcb0289 Abbie Winsor

PS D:\Docs\PS\SFBO> Get-CsOnlineUser | Where {$_.Identity -like 'b3*'} | Select Identity,DisplayName
PS D:\Docs\PS\SFBO>

This is happening in 4.3.0 of the MicrosoftTeams module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by sarollins** [comment] 2022-06-10 02:16
I've even tried variations of converting the Identity to a string, thinking a guid compare may have some issues, but to no avail

Get-CsOnlineUser | Where {($_.Identity).ToString() -like 'b3*'} | Select Identity,DisplayName

**Comment by isrumnon** [comment] 2022-06-10 08:23
@sarollins we're looking into this issue but just need some additional information from you - Is the desired user/s appearing in the output when you just run Get-CsOnlineUser?

**Comment by sarollins** [comment] 2022-06-10 10:51
Oddly enough, I discovered this answer late last night and it does not.  Why would that be?

**Comment by sarollins** [comment] 2022-06-10 17:54
I'm seeing a lot of attributes not getting returned if I use the Where statement

Get-CsOnlineUser | Where {$_.Identity -like '68*'} | Select DisplayName, TeamsUpgradePolicy, Identity

DisplayName     TeamsUpgradePolicy Identity
-----------     ------------------ --------
AA Test                            687592fc-585a-4d93-b7cb-f88bb370d0bf


Get-CsOnlineUser -Identity '687592fc-585a-4d93-b7cb-f88bb370d0bf' | Select DisplayName, TeamsUpgradePolicy

DisplayName TeamsUpgradePolicy
----------- ------------------
AA Test     SfBWithTeamsCollabWithNotify

**Comment by isrumnon** [comment] 2022-06-13 07:27
Hi @sarollins we'll look into this, thanks for brining this to our attention. Can you help us with a few more details? 
We'll need fiddler traces for the scenarios that you are facing problems with to help us with our investigation 
P.S.: I'm sharing my mail ID separately

FYI: @pbafna03 on the client side filtering issue

**Comment by isrumnon** [comment] 2022-06-13 07:28
@sarollins my email ID is isrumnon@microsoft.com, you can share the fiddler traces here. I will be deleting this post due to privacy reasons

I’ve included the steps below to capture a Fiddler trace from a PowerShell session below just in case

1.	Start Fiddler.

2.	Hit F12, or go to file, and uncheck capture traffic

3.	Clear session if unwanted traffic is captured using Ctrl + A, then Ctrl + X

4.	Set fiddler options to decrypt https traffic:

a.            Tools -> Options -> HTTPS -> Decrypt HTTPS traffic
b.            Accept the root certificate install

5.	Configure Fiddler to allow remote connection captures:

a.           Tools -> Options -> Connections -> Allow remote computers to connect

6.	Open a command prompt as administrator

7.	Confirm no proxy server is configured using netsh
netsh winhttp show proxy

8.	Configure netsh to use Fiddler as proxy
Netsh winhttp set proxy 127.0.0.1:8888

9.	Establish a new PowerShell session and reproduce the issue

10.	Reset the proxy settings
netsh winhttp reset proxy

**Comment by yogkumgit** [comment] 2022-06-28 12:27
@sarollins

**Comment by yogkumgit** [comment] 2022-07-11 05:02
@sarollins We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2022-07-11 05:02 UTC
Labels: area:teams / skype
