### ISSUE TITLE
Link to the 'exchange' module at the top returns 404

### ISSUE THREAD

**Issue by giwleb** [MicrosoftDocs/office-docs-powershell#3836] opened 2019-08-14 13:45 UTC
https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/?view=exchange-ps 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a9d9ae7-3dc2-78a8-ce7f-1be4134aa918
* Version Independent ID: 5b45921f-534a-d200-f4b8-5370709e25e5
* Content: [Get-User (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/get-user?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Get-User.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Get-User.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment] 2019-08-14 16:53
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2019-08-20 01:08
Duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/3620

**Comment by get-itips** [comment] 2019-08-20 14:00
Hello @giwleb  I can confirm that a bug has been created internally at Microsoft to address this issue.
Updates of the progress will be handled at the referenced #3620 issue.
Thank you

**Comment by yogkumgit** [comment] 2019-08-21 10:36
@get-itips  Thank you very much for the contribution and sharing this explanation. @giwleb 
 Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment] 2019-08-21 10:36
@officedocsbot close

**Closed by yogkumgit** 2019-08-21 10:36 UTC

**Comment by dariomws** [comment] 2020-05-23 12:57
The Exchange module link issue was fixed this week. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
