### ISSUE TITLE
-SignatureHtml swicth no longer works.

### ISSUE THREAD

**Issue by kumaarrahul** [MicrosoftDocs/office-docs-powershell#9388] opened 2022-05-04 12:57 UTC
[Enter feedback here]

Hi Team,

The -SignatureHtml switch no longer works. Can the documentation be updated stating the same as this is leading to unnecessary confusion.

The current workaround is to disable 'Roaming signature' feature on the tenant for which a support request needs to be raised. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d9fd24-705e-4fa4-7ab0-9c35c31b013e
* Version Independent ID: 9cab50c8-7f41-40e2-ae3f-1be6ae94b28e
* Content: [Set-MailboxMessageConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxmessageconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-MailboxMessageConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-05-04 17:46
Closing as duplicate of #8537

**Closed by chrisda** 2022-05-04 17:46 UTC
Labels: area:exchange, status:duplicate
