### ISSUE TITLE
Date problem with Export-ActivityExplorerData

### ISSUE THREAD

**Issue by mfalc** [MicrosoftDocs/office-docs-powershell#10164] opened 2022-11-21 10:46 UTC
Hi,

There ir a problem when specifying -StratTime and -EndTime in Export-ActivityExplorerData.

It seems like it works from day 1 to 12 but any day greater than 12 of the month it doesn't.

When I try:

`$StartTime = "11/11/2022"`
`$EndTime = "12/11/2022"`
`$ExportActivityExplorer = Export-ActivityExplorerData -StartTime $StartTime -EndTime $EndTime -Filter1 @("Activity", "DLPRuleMatch") -Filter2 @("Workload", $WorkStream) -PageSize 5000 -OutputFormat Csv`

Works correctly.

But as soon as the day es greater than 12:

`$EndTime = "13/11/2022"`
`$ExportActivityExplorer = Export-ActivityExplorerData -StartTime $StartTime -EndTime $EndTime -Filter1 @("Activity", "DLPRuleMatch") -Filter2 @("Workload", $WorkStream) -PageSize 5000 -OutputFormat Csv`

This error appears:

> Cannot process argument transformation on parameter 'EndTime'. Cannot convert value "13/11/2022" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."
    + CategoryInfo          : InvalidData: (:) [Export-ActivityExplorerData], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Export-ActivityExplorerData
    + PSComputerName        : eur03b.ps.compliance.protection.outlook.com

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f188a25-7afc-f6cf-5d2a-5bc9fd08ca1f
* Version Independent ID: 33ed55ee-de0e-2c0c-2141-9a21083392cd
* Content: [Export-ActivityExplorerData (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/export-activityexplorerdata?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Export-ActivityExplorerData.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Export-ActivityExplorerData.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-11-28 21:56
Checking

**Comment by mfalc** [comment] 2023-01-04 08:54
> Checking

Hi! Any new about this issue? Thanks

**Comment by PowerBugi** [comment] 2023-01-06 18:44
I have the same problem !

**IMPORTANT INFORMATION :**
- My computer is in French (`Get-Culture` give me : fr-FR)
- It work when i change the PowerShell culture to "en-US" (cmdlet : `[cultureinfo]::currentculture = 'en-US'`)

I'm sure I'm doing it correctly, it's look like an OS region problem or date translation error in the module ExchangeOnlineManagement, so a bug for french users and maybe more.

--------------------------

At first I thought I was confusing the US format with the European format, so reversing the month and day in the date, **but it doesn't seem to be that**, I have the impression that it's the command that doesn't convert the dates I give correctly... Anyway, here's what happens (without setting my computer to en-US) :

If I do either of these two commands, it works :

```powershell
Export-ActivityExplorerData -StartTime "10 Oct 2022" -EndTime "12 Oct 2022"
Export-ActivityExplorerData -StartTime "09/05/2022" -EndTime "09/12/2022"
```

But if i try this :

```powershell
Export-ActivityExplorerData -StartTime "10 Oct 2022" -EndTime "13 Oct 2022"
Export-ActivityExplorerData -StartTime "09/05/2022" -EndTime "09/13/2022"
```

if have this kind of error :

```
Export-ActivityExplorerData: EndTime '13/10/2022 00:00:00' is not a valid datetime
Export-ActivityExplorerData: EndTime '13/09/2022 00:00:00' is not a valid datetime
```

and if i tried (reverted) :

```powershell
Export-ActivityExplorerData -StartTime "05/09/2022" -EndTime "13/09/2022"
```

then i got this error :

```
Export-ActivityExplorerData: Cannot process argument transformation on parameter 'EndTime'. Cannot convert value "13/09/2022" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."
```

--------------------------

**The stange thing is that, it work from 01 to 12 "day", and upper than 12 it don't work, so it really look like it's a mistake and the cmdlet don't understand that it's a day not a month...**

Also, if i try with another cmdlet in Exchange (for example the one below) i have no problem, so the problem is only for the ActivityExplorer cmdlet...

```powershell
Get-MessageTrace -StartDate "10 Oct 2022" -EndDate "15 Oct 2022" -SenderAddress "example@example.com"
```

So... It work with en-US PowerShell culture as a workaround, but with a "French" Windows configuration, it don't work, it is not specified in the documentation of the cmdlet !

Thank you for the help.
Regards.

**Comment by shivtorov** [comment] 2023-01-23 06:57
The cmdlet description asks you to provide  `<DateTime>` type values for  `-EndTime` and `-StartTime` .
But in all examples above you supply `<String>` values. 

Surely, we expect the cmdlet to be able to implicitly convert string values into DateTime based on local culture settings.
Since it does not work for some cultures, it is a bug in the cmdlet.

In the meantime, you can try explicitly converting dates into DateTime format.
E.g.
```powershell
Export-ActivityExplorerData -StartTime ([datetime]'2022-12-31') -EndTime ([datetime]'2023-01-23')
```

I prefer to always use ISO 8601 format for dates (YYYY-MM-DD) - it always works for me regardless of local culture settings

**Comment by PowerBugi** [comment] 2023-01-25 12:52
@shivtorov 

It don't change anything (i tried before), i confirm this is an OS region bug, due to a bad convertion i guess.

See bellow :

```powershell
PS > $Query = Export-ActivityExplorerData -StartTime ([datetime]'2022-12-31') -EndTime ([datetime]'2023-01-23')
Export-ActivityExplorerData: StartTime '31/12/2022 00:00:00' is not a valid datetime
PS > 
PS > $Query = Export-ActivityExplorerData -StartTime ([datetime]'2022-31-12') -EndTime ([datetime]'2023-23-01')
InvalidArgument: Cannot convert value "2022-31-12" to type "System.DateTime". Error: "String '2022-31-12' was not recognized as a valid DateTime."
```

I tried using things like this too, but not working if it's above 12 of the month : 

```powershell
[DateTime]$start = [DateTime]::UtcNow.Adddays(-7)
[DateTime]$end = [DateTime]::UtcNow.Adddays(-5)
```

It's not a because i'm using a string, it doesn't change anything, when i'm above the 12 of the month, there's the bug. But not i'm my Windows is setup as US region instead of FR.

**Comment by yogkumgit** [comment] 2023-01-30 12:54
@chrisda

**Comment by chrisda** [comment] 2023-02-02 01:36
Still waiting for a reply.

Other than using the date/time formats as specified in the examples (month first), I confirmed the following value works:

`Get-Date -Year 2022 -Month 12 -Day 31 -Hour 0 -Minute 0 -Format "MM/dd/yyyy HH:mm"`

But I don't see how that's any easier than just using `mm/dd/yyyy hh:mm` syntax.

Also unclear whether GMT date/time is required (it wouldn't surprise me if GMT was required).

**Comment by yogkumgit** [comment] 2023-02-03 15:16
@mfalc Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by drew-duckworth** [comment] 2023-03-31 02:52
Not sure why this has been closed: it is clearly still an open issue.

For instance, this works (Australian locale): 
`Export-ActivityExplorerData -StartTime "2023-03-01" -EndTime "**2023-03-10**" -PageSize 5000 -OutputFormat Json`

...but this does not: 
`Export-ActivityExplorerData -StartTime "2023-03-01" -EndTime "**2023-03-15**" -PageSize 5000 -OutputFormat Json`
It throws the following error, as described above for days of the month > 12:
`EndDate '15/03/2023 12:00:00 AM' is not a valid datetime`

**Comment by PowerBugi** [comment] 2023-04-03 14:22
@drew-duckworth Agree...

@chrisda Are you sure this will be fixed ? The fix will be in a new version of the ExchangeOnlineManagement ?

Thank you

**Comment by mfalc** [comment] 2023-04-13 13:19
Hello @chrisda , still having the same issue.

Thanks

**Comment by mfalc** [comment] 2023-04-26 09:45
Hi! Any news about this issue? Thanks

**Comment by chrisda** [comment] 2023-04-26 16:42
Nothing to report. Correct me if I'm wrong, but they should have fixed the original issue with DD-MM-YYYY not working, but the issue now is YYYY-MM-DD isn't working (or perhaps it never worked).

I'm also curious if there's a UTC angle to any of this (meaning, you need to convert your desired local date/time range into UTC to get accurate results).

**Comment by mfalc** [comment] 2023-04-27 08:00
Hello @chrisda ,

As I mentioned, and also was mentioned by other people from the comunity, each time we add a starting date or end date grater that 12 the Export-ActivityExplorerData command gives an error.

Image attached with errors.
<img width="908" alt="Screenshot_Errors" src="https://user-images.githubusercontent.com/117845627/234798130-5dcfe624-88b3-4951-a0a8-c107ebfde9bb.png">

I tried in PSv5 and PSv7 and is not working in any of the versions.

Could you provide a step-by-step guide of what you are doing to make it work? Because maybe I'm missing something.

Thanks in advanced.

**Comment by chrisda** [comment] 2023-04-27 16:23
OK, I was told that this is a bug and it's being worked on. Until it's fixed, this is the workaround:

> Change the culture to en-US using `Set-Culture 'en-US'` then restart the shell and use the cmdlet. Confirm the culture before running the cmdlet by using Get-Culture. It should return this:
>
> ![image](https://user-images.githubusercontent.com/33166947/234927265-29f2c908-f9a4-49b8-99e4-60f26a76d4f8.png)
>
> Then you can run the cmdlet using 'YYYY-MM-DD' format or 'MM-DD-YYYY' format.

**Closed** 2023-05-02 08:29 UTC
Labels: area:exchange, doc-enhancement
