### ISSUE TITLE
Geo-coordinates

### ISSUE THREAD

**Issue by hanspettermalme** [MicrosoftDocs/office-docs-powershell#7585] opened 2021-04-12 10:09 UTC
Be aware that geo-coordinatres do not sync in an Exchange hybrid environment ! You will not be able to set this on-prem and sync this to Exchange Online! At least that's what we have been told by Microsoft support. We would love to use this functionalty, hopefully that will soon be fixed ? 

Regards 
Hans Petter Malme 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af332a3-efc1-49aa-24c2-64b5031a2420
* Version Independent ID: f47bc209-aa9e-f337-1cfa-b8a727a9f780
* Content: [Set-Place (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-place?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2021-04-12 17:33
@hanspettermalme, how does your statement conflict or agree with the existing note at the top of the Set-Place topic:

>  **Note**: In hybrid environments, this cmdlet doesn't work on the following properties on synchronized room mailboxes: City, CountryOrRegion, **GeoCoordinates**, Phone, PostalCode, State, and Street. To modify these properties on synchronized room mailboxes, use the Set-User or Set-Mailbox cmdlets in on-premises Exchange.

So, you should be able to use the Set-User cmdlet with the GeoCoordinates parameter in on-premises Exchange PowerShell to set the coordinates.

Does this make sense?

**Comment by hanspettermalme** [comment] 2021-04-13 05:47
Hi Chris

Thanks for your reply. As you mention in your statement , use the set-user cmd in a hybrid/on-prem environment yes, I totally agree. Only that set-user on a meeting room with the -Geocoordinates those attributes will not sync via. Azure AD Connect and therefore not be able to show in Outlook! My dialogue with Microsoft support have confirmed this ☹ unfortunately. This looks like a nice feature that we absolutely would like to facilitate for our users.

Do you perhaps know a workaround for this issue ?
If of any interest here is the support case no. [Case #:24785240]

Thanks

[Line]

HANS PETTER
SYSTEM ADMINISTRATOR
FINANCE - IT

Hans Petter Malme
***@***.******@***.***%1f.com>
+47 46 41 03 36
Varner AS, Nesøyveien 4, 1396 BILLINGSTAD, NORWAY
[Varner]
varner­.com

**Comment by cfcpreilly** [comment] 2021-08-11 12:32
I'd like to add another voice to this issue and confirm that I am also seeing this issue. The 'GeoCoordinates' property, which I have set using Set-User, are not appearing on the object in Azure AD or Exchange Online. Other properties such as City, State, etc., which were set in the same Set-User cmd have synced successfully.

**Comment by cfcpreilly** [comment] 2021-08-11 12:59
@hanspettermalme I think I may have found the cause. The msDS-GeoCoordinatesLatitude, msDS-GeoCoordinatesLongitude and msDS-GeoCoordinatesAltitude attributes are not selected on the connector that pulls information from Active Directory. Open the Synchronization Service on the computer running Azure AD Connect. Select the connector of type 'Active Directory Domain Services' > Properties > Attributes > Select 'Show All' checkbox > Select the three properties:

![image](https://user-images.githubusercontent.com/6863212/129032786-ef5aff66-fe33-4e40-9c67-edb2a0a49450.png)

**Comment by cfcpreilly** [comment] 2021-08-11 14:24
@hanspettermalme you'll also need to add the new attribute to synchronization rules. The following guide is talking about a different user attribute, but it describes the steps: [https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sync-feature-preferreddatalocation](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sync-feature-preferreddatalocation)

**Comment by hanspettermalme** [comment] 2021-08-12 10:49
Hi Thanks alot for your feedback 👍. So by following these steps is that a supported method by Microsoft?  I get a warning after trying to add these there attributes. - Thanks 
![image](https://user-images.githubusercontent.com/63035217/129184598-b401c76d-6806-4100-ab3d-f4822cc393d9.png)

**Comment by cfcpreilly** [comment] 2021-08-12 13:21
@hanspettermalme That's a good question and I don't have a good answer for you I'm afraid. One thing I discovered during my investigation is that my AADC was out of date. I knew that AADC would auto-update, but I realized that it will only auto-update to the latest version that supports my OS. If you happen to be running AADC on anything less than Server 2016 you won't be on the latest version. It's possible all of this is fixed in a more recent version, so it may be worth checking the version you have before making changes that might not be supported.

**Comment by yogkumgit** [comment] 2021-09-08 10:42
@chrisda

**Comment by chrisda** [comment] 2021-09-17 18:04
I updated the topic to say (changes in bold):

> In hybrid environments, this cmdlet doesn't work on the following properties on synchronized room mailboxes: City, CountryOrRegion, GeoCoordinates, Phone, PostalCode, State, and Street. To modify these properties **except GeoCoordinates** on synchronized room mailboxes, use the Set-User or Set-Mailbox cmdlets in on-premises Exchange.

If/when code is ever fixed, I'll update the topic again.

Thanks for the feedback.

Closing

**Closed by chrisda** 2021-09-17 18:04 UTC
Labels: area:exchange, writer-input-required
