### ISSUE TITLE
process to connect to exchange online doesn't  work

### ISSUE THREAD

**Issue by Eric-ITaaS** [MicrosoftDocs/office-docs-powershell#6168] opened 2020-07-15 01:55 UTC
[Enter feedback here]

PS H:\> Connect-ExchangeOnline -Credential $UserCredential -ShowProgress $true

----------------------------------------------------------------------------
The module allows access to all existing remote PowerShell (V1) cmdlets in addition to the 9 new, faster, and more reliable cmdlets.

|--------------------------------------------------------------------------|
|    Old Cmdlets                    |    New/Reliable/Faster Cmdlets       |
|--------------------------------------------------------------------------|
|    Get-CASMailbox                 |    Get-EXOCASMailbox                 |
|    Get-Mailbox                    |    Get-EXOMailbox                    |
|    Get-MailboxFolderPermission    |    Get-EXOMailboxFolderPermission    |
|    Get-MailboxFolderStatistics    |    Get-EXOMailboxFolderStatistics    |
|    Get-MailboxPermission          |    Get-EXOMailboxPermission          |
|    Get-MailboxStatistics          |    Get-EXOMailboxStatistics          |
|    Get-MobileDeviceStatistics     |    Get-EXOMobileDeviceStatistics     |
|    Get-Recipient                  |    Get-EXORecipient                  |
|    Get-RecipientPermission        |    Get-EXORecipientPermission        |
|--------------------------------------------------------------------------|

To get additional information, run: Get-Help Connect-ExchangeOnline or check https://aka.ms/exops-docs

Send your product improvement suggestions and feedback to exocmdletpreview@service.microsoft.com. For issues related to the module, contact Microsoft support. Don't use the feedback alias for problems or support issues.
----------------------------------------------------------------------------

Import-PSSession : Data returned by the remote Get-FormatData command is not in the expected format.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\1.0.1\ExchangeOnlineManagement.psm1:454 char:40
+ ... oduleInfo = Import-PSSession $PSSession -AllowClobber -DisableNameChe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (:) [Import-PSSession], ArgumentException
    + FullyQualifiedErrorId : ErrorMalformedDataFromRemoteCommand,Microsoft.PowerShell.Commands.ImportPSSessionCommand
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell with modern authentication using V2 Module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment] 2020-07-16 20:03
Hello @Eric-ITaaS, how are you? For your inquiry I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

Thank you!

**Comment by yogkumgit** [comment] 2020-07-17 13:20
@dariomws  Thank you very much for the contribution and sharing this explanation. @Eric-ITaaS Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by 50monkeys** [comment] 2020-07-23 20:33
@Eric-ITaaS  This is a known issue going on right now. You can see details and Microsoft provided workarounds in this community post, which is monitored and updated by Microsoft: https://answers.microsoft.com/en-us/msoffice/forum/all/cannot-connect-to-exchange-online-via-powershell/25ca1cc2-e23a-470e-9c73-e6c56c4fbb46?page=1

**Comment by dariomws** [comment] 2020-07-24 16:56
Thank you @Eric-ITaaS and @50monkeys,

I cannot reproduce the error:
![image](https://user-images.githubusercontent.com/33589238/88415550-0e3ee900-cdb5-11ea-9e64-a9626e1864aa.png)

Did you try with "Connect-ExchangeOnline -UserPrincipalName <UPN> -ShowProgress $true"?

I want to make sure you get the proper assistance for this issue. Let's get you over to support who has the resources to find a resolution for this issue. We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information if it's required.

**Comment by yogkumgit** [comment] 2020-07-26 05:38
@dariomws  Thank you very much for the contribution and sharing this explanation. @Eric-ITaaS Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Closed by yogkumgit** 2020-07-26 05:38 UTC
Labels: area:exchange
