### ISSUE TITLE
StartAfter or CompleteAfter are not available

### ISSUE THREAD

**Issue by hamohsen** [MicrosoftDocs/office-docs-powershell#7351] opened 2021-03-01 15:22 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68325010-9605-22b4-4b6c-b61f332dc321
* Version Independent ID: 47ce5d33-5483-8c8e-2aa2-532178bf466a
* Content: [New-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-migrationbatch?view=exchange-ps&source=docs)
* Content Source: [exchange/exchange-ps/exchange/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by hamohsen** [comment] 2021-03-01 15:26
I've this parameter not working on (E2013 CU23 and E2019 CU2).. however they're available in below result:
Get-ManagementRoleEntry *\* -Parameters StartAfter | ft Name,Role
Please update the document on this parameter availability.

**Comment by chrisda** [comment] 2021-03-01 18:42
@hamohsen, normally, the older issue wins, but I accidentally started investigating in #7352, so I'm closing this issue as a duplicate of that. Let's continue the discussion there.

**Closed by chrisda** 2021-03-01 18:42 UTC
Labels: area:exchange
