### ISSUE TITLE
Receive 4 notifications in the newly created group/team inbox

### ISSUE THREAD

**Issue by yeshwanthjagannath** [MicrosoftDocs/office-docs-powershell#211] opened 2018-03-05 00:06 UTC
Once the team is created through the MicrosoftTeams PowerShell module, there are 4 notifications being sent out to the OfficeGroup mailbox in the background created for the Team. A sample screenshot is below:

![image](https://user-images.githubusercontent.com/8189744/36952513-00b77d96-1fc6-11e8-9fc5-f03024573448.png)

**Comment by kenwith** [comment] 2018-03-05 19:16
@islubin - do you know if this is expected behavior or what could be causing the 4 duplicate notifications?

**Comment by islubin** [comment] 2018-03-05 19:22
@yeshwanthjagannath and @kenwith - not expected behavior.  How often do you see this happening?

**Comment by yeshwanthjagannath** [comment] 2018-03-05 20:35
@islubin I see this happening every other time, it is either 3 or 4 notifications at a minimum.

**Comment by islubin** [comment] 2018-03-05 22:34
@yeshwanthjagannath we suspect this is related to the group creation rather than the "teamification".  Can you test creating a group and calling the new-team cmdlets to convert that group to a team and see if the notifications still occur?  These cmdlets are still in Beta so we'll make sure that this is integrated into our bug list for GA.

**Comment by kenwith** [comment] 2018-03-21 19:08
Thanks for update. Closing this out since it is being fixed for beta. Thanks for reporting!

**Closed by kenwith** 2018-03-21 19:08 UTC
