### ISSUE TITLE
Pages missing: CsTeamsShiftsPolicy, CsTeamsVDIPolicy, etc.

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/office-docs-powershell#7790] opened 2021-05-18 16:25 UTC
Hello,

Pages for the following Functions are missing:

```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-CsTeamsShiftsPolicy                            2.3.1      MicrosoftTeams
Function        Grant-CsTeamsShiftsPolicy                          2.3.1      MicrosoftTeams
Function        New-CsTeamsShiftsPolicy                            2.3.1      MicrosoftTeams
Function        Remove-CsTeamsShiftsPolicy                         2.3.1      MicrosoftTeams
Function        Set-CsTeamsShiftsPolicy                            2.3.1      MicrosoftTeams
Function        Get-CsTeamsVdiPolicy                               2.3.1      MicrosoftTeams
Function        Grant-CsTeamsVdiPolicy                             2.3.1      MicrosoftTeams
Function        New-CsTeamsVdiPolicy                               2.3.1      MicrosoftTeams
Function        Remove-CsTeamsVdiPolicy                            2.3.1      MicrosoftTeams
Function        Set-CsTeamsVdiPolicy                               2.3.1      MicrosoftTeams
Function        Get-CsTeamsVerticalPackagePolicy                   2.3.1      MicrosoftTeams
Function        Grant-CsTeamsVerticalPackagePolicy                 2.3.1      MicrosoftTeams
Function        New-CsTeamsVerticalPackagePolicy                   2.3.1      MicrosoftTeams
Function        Remove-CsTeamsVerticalPackagePolicy                2.3.1      MicrosoftTeams
Function        Set-CsTeamsVerticalPackagePolicy                   2.3.1      MicrosoftTeams
Function        Get-CsTeamsSurvivableBranchAppliancePolicy         2.3.1      MicrosoftTeams
Function        Grant-CsTeamsSurvivableBranchAppliancePolicy       2.3.1      MicrosoftTeams
Function        New-CsTeamsSurvivableBranchAppliancePolicy         2.3.1      MicrosoftTeams
Function        Remove-CsTeamsSurvivableBranchAppliancePolicy      2.3.1      MicrosoftTeams
Function        Set-CsTeamsSurvivableBranchAppliancePolicy         2.3.1      MicrosoftTeams
Function        Get-CsTeamsUpdateManagementPolicy                  2.3.1      MicrosoftTeams
Function        Grant-CsTeamsUpdateManagementPolicy                2.3.1      MicrosoftTeams
Function        New-CsTeamsUpdateManagementPolicy                  2.3.1      MicrosoftTeams
Function        Remove-CsTeamsUpdateManagementPolicy               2.3.1      MicrosoftTeams
Function        Set-CsTeamsUpdateManagementPolicy                  2.3.1      MicrosoftTeams
Function        Get-CsOnlineAudioConferencingRoutingPolicy         2.3.1      MicrosoftTeams
Function        Grant-CsOnlineAudioConferencingRoutingPolicy       2.3.1      MicrosoftTeams
Function        New-CsOnlineAudioConferencingRoutingPolicy         2.3.1      MicrosoftTeams
Function        Remove-CsOnlineAudioConferencingRoutingPolicy      2.3.1      MicrosoftTeams
Function        Set-CsOnlineAudioConferencingRoutingPolicy         2.3.1      MicrosoftTeams
Function        Get-CsTeamsWorkLoadPolicy                          2.3.1      MicrosoftTeams
Function        Grant-CsTeamsWorkLoadPolicy                        2.3.1      MicrosoftTeams
Function        New-CsTeamsWorkLoadPolicy                          2.3.1      MicrosoftTeams
Function        Remove-CsTeamsWorkLoadPolicy                       2.3.1      MicrosoftTeams
Function        Set-CsTeamsWorkLoadPolicy                          2.3.1      MicrosoftTeams

```

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e9c02c-2fa2-52b2-2898-71ddda3eaf21
* Version Independent ID: f5fbed81-ebc2-9dfa-d180-3704696cb3aa
* Content: [New-CsTeamsFeedbackPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamsfeedbackpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsTeamsFeedbackPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsTeamsFeedbackPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by DEberhardt** [comment] 2021-05-18 22:43
apologies, didn't cross-reference the Teams Module - the CsTeamsShiftsPolicy is documented in https://docs.microsoft.com/en-us/powershell/module/teams/?view=teams-ps - which reminds me, are the Documents now moving from Skype to Teams, now that they are exposed there?

**Comment by get-itips** [comment] 2021-08-23 15:07
Duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/7186

**Comment by yogkumgit** [comment] 2021-08-24 08:38
Closing will deal it in #7186

**Closed** 2021-08-24 08:38 UTC
Labels: duplicate, area:teams / skype, writer-input-required
