### ISSUE TITLE
Filtering issue with Get-SPOSite

### ISSUE THREAD

**Issue by MessagingAdmin** [MicrosoftDocs/office-docs-powershell#6431] opened 2020-08-28 12:40 UTC
Getting a syntax error in the filter expression when comparing a string that has  '-le' or '-eq' or '-gt '. My script to find out if a certain user had a mysite failed only for certain user. On investigating and after multiple combinations of names, I see that if the user's email id contained  a hyphen followed by 'le' or 'gt', command was throwing syntax error. Appears, like it is been treated as comparison operator. 

17:45 M:\> Get-SPOSite -IncludePersonalSite $true -Filter {Owner -eq 'matt-lee@abc.com'} -Template spspers#10
Get-SPOSite : Syntax error in the filter expression 'Owner -eq 'matt-lee@abc.com''.
At line:1 char:1
+ Get-SPOSite -IncludePersonalSite $true -Filter {Owner -eq 'matt-lee@a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SPOSite], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.GetSi
   te

17:45 M:\> Get-SPOSite -IncludePersonalSite $true -Filter {Owner -eq 'matt-gee@abc.com'} -Template spspers#10
Get-SPOSite : Syntax error in the filter expression 'Owner -eq 'matt-gee@abc.com''.
At line:1 char:1
+ Get-SPOSite -IncludePersonalSite $true -Filter {Owner -eq 'matt-gee@a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SPOSite], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.GetSi
   te

18:08 M:\> Get-SPOSite -IncludePersonalSite $true -Filter {Owner -eq 'matt-gte@abc.com'} -Template spspers#10
Get-SPOSite : Syntax error in the filter expression 'Owner -eq 'matt-gte@abc.com''.
At line:1 char:1
+ Get-SPOSite -IncludePersonalSite $true -Filter {Owner -eq 'matt-gte@a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SPOSite], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.GetSi
   te

18:08 M:\> Get-SPOSite -IncludePersonalSite $true -Filter {Owner -eq 'matt-eqe@abc.com'} -Template spspers#10
Get-SPOSite : Syntax error in the filter expression 'Owner -eq 'matt-eqe@abc.com''.
At line:1 char:1
+ Get-SPOSite -IncludePersonalSite $true -Filter {Owner -eq 'matt-eqe@a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SPOSite], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.GetSi
   te

**Comment by get-itips** [comment] 2020-08-31 12:22
Hello @MessagingAdmin 
Thanks for your feedback.
I was able to reproduce this, will try to pass this along as here we are limited to documentation issues and improvements.
Thank you

**Comment by get-itips** [comment] 2020-09-15 23:25
Hello @trent-green can you kindly tell me if the team is aware of this? Thanks

**Comment by get-itips** [comment] 2020-11-21 13:48
@trent-green Can you kindly confirm so we can close this issue? Thank you

**Comment by tseward** [comment] 2020-12-31 18:12
Using the latest module version, I was able to successfully run this.

```powershell
PS C:\WINDOWS\system32> Get-SPOSite -IncludePersonalSite $true -Filter {Owner -eq 'trevor.seward@tenantName.com'} -Template spspers#10

Url                                                                        Owner                        Storage Quota
---                                                                        -----                        -------------
https://tenantName-my.sharepoint.com/personal/trevor_seward_tenantName_com trevor.seward@tenantName.com       1048576
```

**Comment by get-itips** [comment] 2021-01-01 23:42
Hello @tseward
Did you try with an onwer username that contains "eq", "le" or "gt" ?

**Comment by tseward** [comment] 2021-01-02 21:12
@get-itips thanks, broken reading comprehension.

I opened a case with Microsoft on this and passed the issue to a PG contact, as well. This appears to be a service side issue as the XML passed by the cmdlet to the service is valid. It looks like the parser on the backend (i.e. SharePoint code) is not able to interpret the query properly.

**Comment by yogkumgit** [comment] 2021-01-04 13:58
@MessagingAdmin Thank you for reporting this feedback here. This list is focused on content issues and we want to make sure your immediate product issue does not get lost in this list. As Trevor has opened a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by get-itips** [comment] 2021-01-04 13:59
@tseward Trevor, that is just great. Thanks for reporting to the internal team.

**Closed by yogkumgit** 2021-01-04 13:59 UTC
Labels: area:spo-powershell
