### ISSUE TITLE
Provide more information about running the Page Diagnostic Tool. 

### ISSUE THREAD

**Issue by randyhammond** [MicrosoftDocs/office-docs-powershell#6163] opened 2020-07-14 16:57 UTC
When I run Invoke-SPOSiteSwap I am getting an error message stating that I need to run the Page Diagnostic Tool. I have run it (without any errors) numerous times using different accounts on different systems and I am still getting the message that I need to run it. I have engaged Microsoft Support for over a month and the problem still has not been resolved. 

Are there specific steps that need to be taken when running the Page Diagnostic Tool so that the results are communicated to the Invoke-SPOSiteSwap command?

**Comment by get-itips** [comment] 2020-07-17 13:12
Hello @randyhammond how are you?
For PDT I can provide this link https://docs.microsoft.com/en-us/office365/enterprise/page-diagnostics-for-spo but probably you already visited it.
There are no specifics steps in the PDT that I am aware of, I think in this case the best would be to continue with support services so they can determine the cause of the error preventing you from running the invoke on your tenant.
Thank you

**Comment by yogkumgit** [comment] 2020-07-20 07:51
@get-itips Thank you very much for the contribution and sharing this explanation. @randyhammond Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Closed by yogkumgit** 2020-07-20 07:51 UTC
Labels: area:spo-powershell

**Comment by gristy58** [comment] 2020-08-18 07:41
i think this should be reopen, i have expierenced it today as well after removing all errors, it is still no good!
