### ISSUE TITLE
Get-TeamsAppInstallation

### ISSUE THREAD

**Issue by alexl-2397** [MicrosoftDocs/office-docs-powershell#9425] opened 2022-05-13 09:31 UTC
I'm trying to run the Get-TeamsAppInstallation (and eventually Remove-TeamsAppInstallation) however I'm getting the error

```
`Get-TeamsAppInstallation : Error occurred while executing 
Code: Forbidden
Message: Missing scope permissions on the request. API requires one of 'TeamsAppInstallation.ReadForUser, 
TeamsAppInstallation.ReadWriteSelfForUser, TeamsAppInstallation.ReadWriteForUser'. Scopes on the request 'AppCatalog.ReadWrite.All, 
ChannelMember.ReadWrite.All, email, Group.ReadWrite.All, openid, profile, Reports.Read.All, User.Read.All'
InnerError:
  RequestId: 5d37069d-28e2-4e07-832f-52eb3dab9bd5
  DateTimeStamp: 2022-05-13T09:22:51
HttpStatusCode: Forbidden
At line:6 char:92
+ ... Installed = Get-TeamsAppInstallation -UserId $UserID -AppId $theAppID ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-TeamsAppInstallation], ApiException
    + FullyQualifiedErrorId : Microsoft.Teams.PowerShell.TeamsCmdlets.ErrorHandling.ApiException,Microsoft.Teams.PowerShell.TeamsCmdlets.GetTeamsA 
   ppInstallation
```
For background info I've accidentally deployed the Company Communicator App org-wide (https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide)
I used the ARM template to deploy this, however mistakenly kept the value for proactively install set to true. So now everyone has it, and I'm trying to mass-uninstall it for everyone.

I've been through and have set the API permissions to the user app registration and the graph app registration, however have had no luck.

**Comment by get-itips** [comment] 2022-05-17 18:22
Hello @alexl-2397 
Here, we are limited to documentation changes and improvements, I checked to see if we needed to adjust any article however, I could not reproduce, I recommend checking permissions and also try to run interactively (if you are not)
Hope this information helps you

**Comment by yogkumgit** [comment] 2022-05-24 05:51
@get-itips Thank you very much for the contribution and sharing this explanation. @alexl-2397 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2022-05-24 05:52 UTC
Labels: area:teams, doc-enhancement
