### ISSUE TITLE
Unable to have the pop-up when i try to connect through a powershell GUI

### ISSUE THREAD

**Issue by tig3r57** [MicrosoftDocs/office-docs-powershell#7335] opened 2021-02-24 13:58 UTC
Since beginning of this week, i'm no more able to use the command "connect-exchangeonline" if it's launch from a powershell GUI.
I don't have any issue with other command like connect-azuread

**Comment by dariomws** [comment] 2021-03-02 12:54
Hi @tig3r57, thank you for your feedback.

I couldn't reproduce the issue but try to minimize the Windows PowerShell window to see if you have a credential pop-up below it.

Also, please check that you are using the latest version of the Exchange Online PowerShell V2 module:
https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2

**Comment by yogkumgit** [comment] 2021-03-11 15:54
@dariomws Thank you very much for the contribution and sharing this explanation. @tig3r57 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-03-11 15:54 UTC
Labels: area:exchange
