### ISSUE TITLE
Documentation for New-MigrationBatch erroneous

### ISSUE THREAD

**Issue by rsedlacz** [MicrosoftDocs/office-docs-powershell#8197] opened 2021-08-17 12:54 UTC
Documentation for New-MigrationBatch erroneous:
"For example: -TargetDatabases @(MBXDB01,MBXDB02,MBXDB03)"

New-MigrationBatch -Local -Name Move-users -CSVData ([System.IO.File]::ReadAllBytes("C:\Migration\Move-users.csv"))  -TargetDatabases @(DAG19-DB01,DAG19-DB02,DAG19-DB03,DAG19-DB04) 
At line:1 char:148
\+ ... :\Migration\Move-users.csv"))  -TargetDatabases @(DAG19-DB01,DAG19-DB ...
\+                                                                 ~
Missing argument in parameter list.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68325010-9605-22b4-4b6c-b61f332dc321
* Version Independent ID: 47ce5d33-5483-8c8e-2aa2-532178bf466a
* Content: [New-MigrationBatch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-migrationbatch?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-MigrationBatch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MigrationBatch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2021-08-17 16:35
@rsedlacz, confirmed. The parameter type is MultiValuedProperty, so I confirmed it accepted simple comma-separated values like this:

```powershell
-TargetDatabases MBXDB01,MBXDB02,MBXDB03
```

I'm not sure why it was using that weird syntax that didn't work. It's had that non-working example since the Exchange 2013 era.

I updated the TargetDatabases and TargetArchiveDatabases parameter descriptions accordingly.

Thanks for the feedback.

Closing

**Closed by chrisda** 2021-08-17 16:35 UTC
Labels: area:exchange
