### ISSUE TITLE
New-PnPSite parameters are not found

### ISSUE THREAD

**Issue by Amysno** [MicrosoftDocs/office-docs-powershell#3901] opened 2019-08-28 13:23 UTC
Hello,
I have updated my PowerShell PnP module with Update-Module SharePointPnPPowerShell*.
So, normally, it should run New-PnpSite with -Title and -Url parameters.
Except, when I type those in my PowerShell Console, i have nothing shown.

This came to my attention after I got the so-documented following error :
```
New-PnPSite : IDX12729: Unable to decode the header '[PII is hidden]' as Base64Url encoded string. jwtEncodedString:
'[PII is hidden]'.
Au caractère C:\Users\XXX\Desktop\XXX\Scripts\CopieSite.ps1:70 : 9
+         New-PnPSite -Title $listItem["Title"] -Type CommunicationSite ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-PnPSite], ArgumentException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.NewSite
```
here is my full line for creating a site : 
`New-PnPSite -Title $listItem["Title"] -Type CommunicationSite -Url $listItem["URL"]`
The URL column from my SP List is a simple single line text column.

What did I do wrong ? Is it a bug from the module ?

**Comment by yogkumgit** [comment] 2019-08-28 14:52
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2019-09-02 18:28
Hello @Amysno 
Thanks for your feedback.
This issue system is specifically to address issues currently in documentation, besides that, I tested New-PnpSite with latest version the same way you are using it and I could not reproduce the error, so I could not identify any documentation update.
I see that you are using it inside an script, did you try to use it outside the script? did it work?
I would recommend checking that, hope this information helps you.

**Comment by yogkumgit** [comment] 2019-09-06 12:21
@get-itips  Thank you very much for the contribution and digging deep into it.  @Amysno We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2019-09-06 12:21 UTC
