### ISSUE TITLE
Get-CsOnlineUser in 3.1.1 seems to return a different set of properties compared with earlier versions

### ISSUE THREAD

**Issue by richardh-ncp** [MicrosoftDocs/office-docs-powershell#8991] opened 2022-02-22 10:37 UTC
I have previously used Get-CsOnlineUser in MicrosoftTeams 2.3.1 and 3.0.1. 

I have now used it in 3.1.1 and the property set returned seems different.

For example in 3.1.1 'ObjectID' doesn't seem to exist anyomre
FirstName and LastName dont seem to exist anymore. 'GivenName' is present, but no last name

'Identity' returns a different value.

**Comment by ckarawani** [comment] 2022-02-22 17:58
Maybe related @richardh-ncp, but if you get the user using `-Filter` instead, 

ex. `Get-CsOnlineUser -Filter {UserPrincipalName -eq 'jsmith@contoso.com'}`

It will return many of the missing/deprecated properties > 3.

**Comment by richardh-ncp** [comment] 2022-02-23 07:56
I have tried this with 3.1.1 and it does indeed seem to be the case.

Not very logical :(
Particularly when the same property (Identity) can return different values

Is this behaviour documented?
Is Get-CsOnlineUser being deprecated?

**Comment by vincentkurmi** [comment] 2022-02-23 08:18
Hi @richardh-ncp , I also reported the same problem, here https://github.com/MicrosoftDocs/office-docs-powershell/issues/8973. 
There are a few opened issues describing the same behaviors. It looks like many people complain about that.

**Comment by yogkumgit** [comment] 2022-02-24 11:53
@isrumnon

**Comment by yogkumgit** [comment] 2022-03-19 03:02
@isrumnon Please comment.

**Comment by isrumnon** [comment] 2022-03-21 09:13
Hi @richardh-ncp @vlethiec these changes are by design and have been documented here https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps

**Comment by Edgar81** [comment] 2022-04-06 12:10
@isrumnon I do understand that this is by design, but what's the logic behind removing the LastName field?

**Comment by sagius-pingco** [comment] 2022-04-07 14:59
> @isrumnon I do understand that this is by design, but what's the logic behind removing the LastName field, while still providing GivenName?

Completely agree with this @Edgar81. Especially considering AzureAD Module is being deprecated shortly... Why force users to use Microsoft.Graph.Users in addition to MicrosoftTeams just to pull a LastName? To that extent, there is a bucket load of attributes that are not relevant to Teams that are in the output of Get-CsOnlineUser at present.

If there is a way to upvote reintroduction of basic user properties in conjunction with the Teams specific properties, please point me in the right direction and I will follow that process.

Many thanks in advance.

**Comment by yogkumgit** [comment] 2022-04-08 04:46
@richardh-ncp Hope the comment by @isrumnon is helpful. We proceed here to close this issue. Thanks

**Comment by sagius-pingco** [comment] 2022-04-08 04:48
Hello @yogkumgit,

Can you please help answer my question? This is not ideal...

>If there is a way to upvote reintroduction of basic user properties in conjunction with the Teams specific properties, please point me in the right direction and I will follow that process.


Regards,
Sean

**Comment by yogkumgit** [comment] 2022-04-09 03:54
Here, we are limited to documentation fixes and improvements only. Expert has already shared his comment. Kindly approach support. Thanks.

**Closed** 2022-05-03 12:20 UTC
Labels: area:teams, support-request
