### ISSUE TITLE
The German Translation is not really good.

### ISSUE THREAD

**Issue by FlorianGrimm** [MicrosoftDocs/office-docs-powershell#1890] opened 2018-10-17 12:08 UTC
PNP - PowerShell is translated to Plug & Play-PowerShell.
Update-PnPApp is translated to Update & #8209; PnPApp.

IMHO better only the english version as a translation like this.

**Comment by AndreaBarr** [comment] 2018-10-18 21:30
@FlorianGrimm Where are you seeing the translation?

**Comment by VesaJuvonen** [comment] 2018-10-24 07:33
Translation issue is here - https://docs.microsoft.com/de-de/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps. This is due automatic translation process, which we have fixed on the normal dev docs, but apparently the issue still exists in the PowerShell side.

Same issue is there also for other automated translations - like Spanish -https://docs.microsoft.com/es-es/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps.... execpt for some reason it's correct in Russian - https://docs.microsoft.com/ru-ru/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps.

**Comment by VesaJuvonen** [comment] 2019-01-15 09:01
The issue is in the translation process which is done at the repository level. We did fix this exact same issues with API documentation while back, so it can be fixed, but we can't address that from the PnP PowerShell side, so @kenwith's coordination on this is needed.

**Comment by kenwith** [comment] 2019-01-15 16:45
@samanthaw - can help with translation issues and provide us guidance.

**Comment by kenwith** [comment] 2019-01-15 17:58
@FlorianGrimm - thank you for identifying the issue. The localization team is working on this and I am seeing a lot of emails to get it resolved. Apparently this was fixed before but has re-appeared. Also, the same translation affects all languages so they are working to get this resolved across all languages. Really appreciate your taking the time to open the issue you identified.

**Comment by kenwith** [comment] 2019-01-16 19:42
https://github.com/MicrosoftDocs/office-docs-powershell/pull/2505

**Comment by OfficeGlobal** [comment] 2019-02-26 09:24
The article was HumanTranslated, PnP is displayed correctly

Best Regards,
Michal

**Closed** 2019-02-26 18:37 UTC
Labels: area:docs
