### ISSUE TITLE
Need a "Please Notenote for 

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/office-docs-powershell#7032] opened 2021-01-06 17:08 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a1f9fa-7dd6-ebf1-3e64-ef47bd3962b2
* Version Independent ID: 5ea9bde3-9fe9-8ae1-0992-b12223c4d7c4
* Content: [New-SafeLinksPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-safelinkspolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-SafeLinksPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-SafeLinksPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2021-01-06 17:29
Closing. Basically, unfinished dupe of #7033

**Closed by chrisda** 2021-01-06 17:29 UTC
Labels: Microsoft submitter, area:exchange, duplicate
