### ISSUE TITLE
Update Applies to section

### ISSUE THREAD

**Issue by SultanRayes** [MicrosoftDocs/office-docs-powershell#8608] opened 2021-11-16 12:29 UTC
Please remove Exchange Server 2013, Exchange Server 2016 from Applies to section .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 461de863-05f8-4df2-af57-b5106b9b0cd5
* Version Independent ID: df907b31-c01c-ff6d-2161-85e4e77a626d
* Content: [Set-ClientAccessRule (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-clientaccessrule?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-ClientAccessRule.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-ClientAccessRule.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2021-11-16 18:18
@SultanRayes, the problem is: that cmdlet is available in Exchange 2013 and 2016. I'm positive that it doesn't work, but it is available.

**Comment by chrisda** [comment] 2021-11-18 19:14
Just to clarify: since the cmdlet is available in Exchange 2013 and Exchange 2016, I'm not going to remove those values from the 'Applies to:' metadata value.

The SYNOPSIS section states what's going on:

> This cmdlet is available or functional only in Exchange Server 2019 and in the cloud-based service.

Thanks for the feedback.

Closing

**Closed by chrisda** 2021-11-18 19:14 UTC
Labels: area:exchange, writer-input-required
