### ISSUE TITLE
Issue creating Call Queue with private channel

### ISSUE THREAD

**Issue by FunkyCat123** [MicrosoftDocs/office-docs-powershell#10759] opened 2023-04-24 16:30 UTC
[Enter feedback here]

I am using the following cmdlet to create a new call queue with "collaborative calling" using private channel. It works fine from admin portal, however using a script it requires use DistributionLists switch. Otherwise the command fails. I tried using parent team ID for the DistributionLists parameter. This lets the command to complete. However incoming calls goes out to all team members as opposed to private channel members only. When check UI (Teams Admin portal) it shows only the private channel in Call Answering section. But the main summary page list agents count as the number of all team members.
Please recommend how the command should be executed so that the call queue is setup with private channel only.

Here is the cmd I got at this point:

New-CsCallQueue -Name "NameTest" `
            -AgentAlertTime 30 `
            -OverflowAction SharedVoicemail `
            -OverflowActionTarget $VM_Group_ID `
            -OverflowThreshold 2 `
            -TimeoutThreshold 30 `
            -TimeoutAction SharedVoicemail `
            -TimeoutActionTarget $VM_Group_ID `
            -PresenceBasedRouting $false `
            -AllowOptOut $false `
            -OverflowSharedVoicemailTextToSpeechPrompt "Please leave a message and we will get back to you promptly" `
            -TimeoutSharedVoicemailTextToSpeechPrompt "Please leave a message and we will get back to you promptly" `
            -RoutingMethod Attendant `
            -LanguageId "en-US" `
            -UseDefaultMusicOnHold $true `
            -ChannelId $Channel_ID `
            -DistributionLists @($CssTeam.GroupId) `
            -ChannelUserObjectId $ServiceAccountObjectID `
            -verbose

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b26bf80-4e1f-4172-e003-29fd1a28928c
* Version Independent ID: 7d0d9c25-c6f1-4ae3-b4e3-3b6de536ffa3
* Content: [New-CsCallQueue (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/new-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/New-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by DMoenks** [comment] 2023-04-24 18:47
According to the [Call queue feature compatibility](https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=general-info#resources-for-complex-scenarios) overview, private channels don't seem to be supported when using call queues. Please see note 8 below the table.
Although the UI might look like the configuration has worked, it doesn't necessarily mean the result ends up as expected. As the result rather seems to match the documentation, I'd guess opening a support case might be a better approach instead of asking for a (non-supported) example to be added to the documentation.

**Comment by FunkyCat123** [comment] 2023-04-24 18:54
When "collaborative calling" was first released, the article had a specific notice about private channels not being supported. When I checked earlier this year that notes section no longer had the line item for private channels not being supported. I was also able to add private channel and test calling through a call queue successfully. 
Not sure when this restriction made it's way back in to the article... This is very frustrating when deploying automation. Also why is it technically possible in some tenants and only via Teams Admin portal, if it's not supported?
Those types of inconsistencies are make Teams voice a tough sell for large enterprises.

**Comment by get-itips** [comment] 2023-04-28 16:09
Hello @FunkyCat123 
As @DMoenks notes, at the moment Only standard channels are supported, please also see this note

>Known issue: Assigning private channels to call queues
When using a private channel calls will be distributed to all members of the team even if the private channel only has a subset of team members.
You may experience this problem when trying to assign a private channel to a call queue. This problem may occur even if the call queue previously had a private channel assigned or if the private channel was previously assigned to a call queue.
If you already have private channels assigned to call queue they will continue to work. This problem only affects new assignments.
Support is working on identifying the root cause of this problem and will plan an update to address this issue. At this time, it's estimated that this problem will be resolved during the second half of 2023 (July to November 2023).

Source https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=call-answering

**Closed by get-itips** 2023-04-28 16:09 UTC
Labels: area:teams / skype
