### ISSUE TITLE
Set-CsLisCivicAddress details in the document and background

### ISSUE THREAD

**Issue by jinbchoi** [MicrosoftDocs/office-docs-powershell#9795] opened 2022-08-12 16:45 UTC
[Enter feedback here]
The part not mentioned on the document is that the fact I observed which the certificate(.pfx) will be stored in the Personal Certificate Store instead of Local Machine in the process, which is related to the step when it comes to the PScmdlet Test-CsCivicAddress.
In the case for a large org which happens to have multiple admins for their SfB and the admin who didn't originally configure the  LIS provider with the Set-CsLisServiceProvider on the machine, the specific admin wouldn't be able to leverage the certificate for him/her personal certificate store and could end up with the error "Could not create SSL/TLS secure channel"

Just a though it would be something we want to provide the background in the document.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e505d937-c075-bab3-0103-ac5f93df9372
* Version Independent ID: 98b66f30-07a8-37b9-e82d-6cda847cd25c
* Content: [Set-CsLisServiceProvider (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cslisserviceprovider?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsLisServiceProvider.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsLisServiceProvider.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by jinbchoi** [comment] 2022-08-13 19:34
Correction: I meant to refer the PScmdlet Test-CsLisCivicAddress instead of Test-CsCivicAddress in the report

**Comment by get-itips** [comment] 2022-08-25 15:36
Duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/9797

**Closed by get-itips** 2022-08-25 15:36 UTC
Labels: area:teams / skype
