### ISSUE TITLE
Correct Sytax for the second Identity placeholder in Add-MailboxFolderPermission

### ISSUE THREAD

**Issue by ddexter26** [MicrosoftDocs/office-docs-powershell#7481] opened 2021-03-23 17:17 UTC
While running the below Command, we kept on getting an Error:
Add-MailboxFolderPermission -Identity User1@somedomain.com:\Contacts -AccessRights Editor -User User2@somedomain.com

Error: `**The Sharing policy doesn't allow you to grant certain permissions to users on ContactsFolder folder**`

The below change in the command fixed the issue:
Add-MailboxFolderPermission -Identity User1@somedomain.com:\Contacts -AccessRights Editor -User User2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1a893c8-66de-1f8a-f8d2-aa573379e778
* Version Independent ID: 1c32c637-d003-820c-594f-a9adc9c353d9
* Content: [Add-MailboxFolderPermission (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/add-mailboxfolderpermission?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Add-MailboxFolderPermission.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2021-03-24 20:52
@ddexter26, I tried it in an Exchange Online tenant and it worked:

```powershell
PS C:\Users\jdoe> Add-MailboxFolderPermission -Identity user1@contoso.com:\Contacts -AccessRights Editor -User user2@contoso.com

FolderName           User                 AccessRights                           SharingPermissionFlags
----------           ----                 ------------                           ----------------------
Contacts             User 2        {Editor}
```

In your case, for the value of the User parameter, is that email address the user's PrimarySMTPAddress and is that email address unique in your org?

**Comment by chrisda** [comment] 2021-04-08 17:14
Closing due to the fact that the topic works as described. Based on my brief research, similar strange issues are explained by duplicate values of unique user properties that aren't supposed to allow duplicates. @ddexter26, if you ever find out what the problem is, feel free to report back here.

**Closed by chrisda** 2021-04-08 17:14 UTC
Labels: area:exchange
