### ISSUE TITLE
Unacceptable delays

### ISSUE THREAD

**Issue by danielbigras** [MicrosoftDocs/office-docs-powershell#5321] opened 2020-04-17 18:38 UTC
When will Add-TeamUser/Add-TeamChannelUser update Teams in real time? One of the main reason to use PowerShell is to save time. And if we can't update Teams in real time, with Add-TeamUser, Add-TeamChannelUser, it's pointless. Is there a plan to make them update Teams in real time? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da0c53f2-1c62-14f6-6371-f54bf86b0c24
* Version Independent ID: aac162db-a9c0-fbfb-dd40-526e94d3bef8
* Content: [Add-TeamUser (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/add-teamuser?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/Add-TeamUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/Add-TeamUser.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment] 2020-04-20 10:58
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2020-04-20 19:11
Hello @danielbigras Daniel 👍 How are you?
Here, we are limited to address issues with documentation, said that, I was able to get in contact with the team and they told me that they need more detail to understand the issue you are facing, so they ask if you can kindly share more details sending an email to teamscmdlets at microsoft.com
Thank you

**Comment by danielbigras** [comment] 2020-04-20 19:21
Thank you Andres. Wow, didn't expect a reply so soon. Will do. But it's a known issue, and the documentation claims that these commands have very long delays.

**Comment by get-itips** [comment] 2020-04-20 19:31
> Thank you Andres. Wow, didn't expect a reply so soon. Will do. But it's a known issue, and the documentation claims that these commands have very long delays.

Indeed, however, please do not hesitate in sharing your details in spite of it being a current known issue.

**Comment by danielbigras** [comment] 2020-04-20 19:32
Yes, will do, I'm not closing this ticket. If I can help them fix that problem, it will be important to share.

**Comment by get-itips** [comment] 2020-04-20 20:21
@danielbigras 
Daniel,
Agree with you, I invite you to reply to this exact issue if you get further info from the team that could change documentation, as the issues can always be re-opened.
Thank you

PS: You probably know it and the email I shared with you should be better in this case however I didn't want to miss mentioning [UserVoice](https://microsoftteams.uservoice.com/search?filter=ideas&query=add-teamuser) too.

**Comment by yogkumgit** [comment] 2020-04-21 12:13
@get-itips  Thank you very much for the contribution and sharing this explanation. @danielbigras 
Hope this comment is helpful for you. As suggested, when documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by danielbigras** [comment] 2020-04-21 12:46
Why close the ticket? I didn't even have time to discuss with the dev team.

**Comment by vibharathi** [comment] 2020-04-21 13:07
@danielbigras  - is this something that u experience always with your tenant? How long does a user added with Add-TeamUser typically take to show up on your UX?

**Comment by danielbigras** [comment] 2020-04-21 14:07
@vibharathi Hello. In your documentation for Add-TeamUser, the description mentions "up to several hours", therefore I presume it's a known issue. And when we search online, it's a common problem.

**Comment by kenwith** [comment] 2020-04-21 15:43
I don't see any issue for the documentation here. If I am misunderstanding please let me know.

Any response here automatically opens the issue again so it will get back on my radar to make a doc update if I am wrong in closing it.

For product problems the best mechanism is support since there is an official path to validate and open bugs for the product team. In this case, someone from the product team responded here and I would recommend to follow up with them directly. @danielbigras if you would shoot me an email and I will loop in @vibharathi since she already engaged with you and responded. My email is  kenwith at microsoft.com.

**Comment by danielbigras** [comment] 2020-04-21 16:09
Hello, it's in your documentation for the Add-TeamUser command: 

https://docs.microsoft.com/en-us/powershell/module/teams/add-teamuser?view=teams-ps

"The command will return immediately, but the Teams application will not reflect the update immediately. The Teams application may need to be open for up to several hours before changes are reflected."

I'm not sure it's a bug, I think it's a known limitation. And I'm asking when that limitation will be removed. Because adding 30+ members to a Team, manually, it's a pain. With a CSV, it would amazing.

**Comment by bwhittaker69** [comment] 2020-04-25 01:13
very heavy delays, over 30+ hours now for team member assignments via powershell

**Comment by danielbigras** [comment] 2020-04-25 15:56
30 hours, that's really bad. When are they going to fix this? We can't use that.

**Comment by kenwith** [comment] 2020-04-27 16:19
I have checked with the product team and this level of delay is not expected behavior. Please open a service support request in your tenant so that they can track down what might be causing the delay. The support engineers also have an official mechanism to open a bug with the product team when they validate with you the problem. Please go ahead and loop me in with the support engineer if you want and I can provide the info I tracked down that this is not expected behavior.

I wish we could provide support and product fixes here however this issue list is for documentation. I know if I were you, and I have been exactly in your position, I would not like the response to open a support ticket. However, the support engineers have tools and experience and are best equipped to track down problems with the products. If there is something I can improve in the documentation please don't hesitate to respond and reopen this issue.

**Comment by danielbigras** [comment] 2020-04-27 18:20
Isn't it your product? You document the Add-TeamUser command that there are major delays. Not sure why I should be contacting Microsoft. It's a problem for everyone, not just me.

**Comment by kenwith** [comment] 2020-04-27 22:46
I confirmed with product team that the delay can be between 24 and 48 hours. Updated the documentation with this information here: https://github.com/MicrosoftDocs/office-docs-powershell/pull/5395

**Comment by kenwith** [comment] 2020-04-27 22:48
Also, more information about the delay is documented here: https://docs.microsoft.com/en-us/graph/teams-create-group-and-team

**Comment by kenwith** [comment] 2020-04-27 22:53
Also, just wanted to add to this thread that the product team is aware of the delay and do not find it acceptable either and they are working on a resolution. I will update documentation when delay changes. For now I want to make sure the documentation matches the behavior people will experience.

**Comment by danielbigras** [comment] 2020-04-28 12:50
Mr Withee. I feel we did a full circle. We all know it takes many hours. It's documented in the Add-TeamUser command. And we all feel that it makes this module pretty much useless. We use PowerShell to save time. That's what is unacceptable.

**Closed** 2020-04-28 16:01 UTC
Labels: area:teams

**Comment by kenwith** [comment] 2020-04-28 16:04
The documentation is correct now. Thank you for pushing on this. When I said "several hours" I did not mean such a long delay. I was wrong and found out yesterday that the delay was 24 to 48 hours. Which is technically "several hours" but feels misleading. I want the documentation to reflect what is experienced which is why I updated it. I will update again when timing is updated in product.
