### ISSUE TITLE
Get-CsTeamsMeetingPolicy errors

### ISSUE THREAD

**Issue by inseu** [MicrosoftDocs/office-docs-powershell#7855] opened 2021-05-31 11:39 UTC
Hello, 
I am trying to run this Get-CsTeamsMeetingPolicy cmdlet in the organization environment with proxy settings.

No errors when run this:
Connect-MicrosoftTeams
The service account has MFA enabled. 

For some reason I get this message: 
Get-CsOnlineSession : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The client cannot connect to the destination specified in the request. Verify that the 
service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, 
run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig". For more information, see the about_Remote_Troubleshooting Help topic.
At ...\WindowsPowerShell\Modules\MicrosoftTeams\2.3.1\net472\SfBORemotePowershellModule.psm1:63 char:22

What am I missing here? 

Thanks for your help
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf19cb0-37fa-e1a4-20aa-5fe2c23d600e
* Version Independent ID: 6fa9a9b5-024b-677b-6c0b-3dba1c03602f
* Content: [Get-CsTeamsMeetingPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csteamsmeetingpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsTeamsMeetingPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsTeamsMeetingPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by inseu** [comment] 2021-05-31 12:59
I followed this documentation: 
https://docs.microsoft.com/en-US/microsoftteams/teams-powershell-move-from-sfbo 
Also checked WinRM settings running winrm get winrm/config/client/auth
I have enabled Basic authentication

**Comment by get-itips** [comment] 2021-06-07 14:05
Hello @inseu how are you?
I could not reproduce it to see if we have to fix the article. I could connect using `Connect-MicrosoftTeams` and an MFA account.
Make sure to only use one version of the Teams Ps module. If the issue persists I would suggest to open a support ticket directly from your tenant. 

Also please be aware that 

> I followed this documentation:
https://docs.microsoft.com/en-US/microsoftteams/teams-powershell-move-from-sfbo
Also checked WinRM settings running winrm get winrm/config/client/auth
I have enabled Basic authentication

Is specific to that scenario.

Hope this information helps you,

**Comment by inseu** [comment] 2021-06-07 19:49
Thank you, @get-itips I am also able to use Connect-MicrosoftTeams without issues and with MFA account. The problem is when I use the skype online connection cmdlets like Get-CsTeamsMeetingPolicy or Get-CsUser. Does this work for you? 
I opened a support ticket and waiting an answer but I think I am not the only one with this issue currently. See this article: https://office365itpros.com/2021/05/13/teams-updated-powershell-module/

**Comment by get-itips** [comment] 2021-06-08 11:40
> Thank you, @get-itips I am also able to use Connect-MicrosoftTeams without issues and with MFA account. The problem is when I use the skype online connection cmdlets like Get-CsTeamsMeetingPolicy or Get-CsUser. Does this work for you?
> I opened a support ticket and waiting an answer but I think I am not the only one with this issue currently. See this article: https://office365itpros.com/2021/05/13/teams-updated-powershell-module/

Hello @inseu how are you?
It has been reported and the team behind the module is aware.

**Comment by inseu** [comment] 2021-06-08 12:07
@get-itips Great! thank you. Looking forward to receiving your comments.

**Comment by yogkumgit** [comment] 2021-06-10 11:08
@get-itips Thank you very much for the contribution and sharing this explanation. @inseu Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-06-10 11:08 UTC
Labels: area:teams / skype
