### ISSUE TITLE
Exchange isn't a selectable API permission

### ISSUE THREAD

**Issue by cclayton18** [MicrosoftDocs/office-docs-powershell#6865] opened 2020-11-17 19:51 UTC
In Step 2 we are told to select Exchange (shown in the screenshot under legacy APIs) and select Exchange.ManageAsApp, but no such card or permission is available to select.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#setup-app-only-authentication)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2020-11-17 21:25
Confirmed. Looking into it.

**Comment by Smiliman** [comment] 2020-11-18 13:51
@chrisda Thanks for your investigation - same confusion about missing Exchange.ManageAsApp here.

**Comment by borismilincic** [comment] 2020-11-19 15:58
I found the Exchange API when I changed to the tab "APIs my organization uses" and searched for the API ID (00000002-0000-0ff1-ce00-000000000000 in this case). This should be reflected in the article.

Other question: As this was listed in the "Supported legacy APIs" section before, is there a date when this will stop working? If so, where is it documented? Is there a way to use other APIs when using a service principal to manage Exchange Online?

**Comment by ronnyholtmaat** [comment] 2020-11-19 16:40
> I found the Exchange API when I changed to the tab "APIs my organization uses" and searched for the API ID (00000002-0000-0ff1-ce00-000000000000 in this case). This should be reflected in the article.
> 
> Other question: As this was listed in the "Supported legacy APIs" section before, is there a date when this will stop working? If so, where is it documented? Is there a way to use other APIs when using a service principal to manage Exchange Online?

That's probably only the case when you already are using the Legacy API. When you are **not using the Legacy Exchange API,** - in myt case - then it is **not** possible to select it. (also not under API's my organization uses).

Is there a Microsoft Graph API Alternative for App-only authentication for unattended scripts in the EXO V2 module?
Or Microsoft Graph API Alternative for Exchange.ManageAsApp API permissions?

Or, how do we go about setting up App-only authentication for unattended scripts in the EXO V2 module without the Exchange Legacy API and with Microsoft Graph API

**Comment by michevnew** [comment] 2020-11-21 19:40
@chrisda @yogkumgit apparently this is because of the deprecation announcement for the Outlook REST APIs. The steps @borismilincic outlined above will be the way to add permissions going forward it seems.

P.s. Please dont forget to also update any document detailing app creation for OAuth authentication.

**Comment by ronnyholtmaat** [comment] 2020-11-23 08:23
I can confirm that the steps @borismilincic described work. In addition to that, step 5 also needs an update.

App Role permissions (for example, Exchange Administrator) can only be bound to Groups, not to the App Registration directly (anymore?). So i created a new group, gave it permissions and added the app registration. This feature is in 'preview' it says...

**Comment by decturau** [comment] 2020-12-02 02:48
I agree that editing the manifest works but interested to know what to use moving forward as the API has been deprecated?

**Comment by JeremyTBradshaw** [comment] 2021-01-05 19:48
@decturau has a perfect point/question that deserves an answer.

**Comment by chrisda** [comment] 2021-01-05 20:00
Still seeking answers. When I know, I'll update the topic.

**Comment by joshfria** [comment] 2021-01-27 19:24
Any update here? We are looking to use Cert based auth very soon if possible.

**Comment by chrisda** [comment] 2021-01-27 19:31
Closing in. I'm told the current UI is based on Azure AD Premium P1 licenses while the new Preview UI is based on Azure AD Premium P2 licenses. Can anyone confirm or deny?

Also, @ronnyholtmaat (or anyone) I need clarification on this statement:

> App Role permissions (for example, Exchange Administrator) can only be bound to Groups, not to the App Registration directly (anymore?). So I created a new group, gave it permissions and added the app registration.

Created a group: done. Gave the group permissions: done. But where/how do you add the app registration to the group?

**Comment by joshfria** [comment] 2021-01-27 19:38
We have P2 across the board and I do not see Exchange in the UI. I'm pretty sure it was there 6 months ago though when I first looked into this.

**Comment by chrisda** [comment] 2021-01-27 19:53
@joshfria, do the semi-recently updated steps in [Step 2](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#step-2-assign-api-permissions-to-the-application) help? Those steps (manually editing the manifest) should work.

It's [Step 5](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2#step-5-assign-a-role-to-the-application) where the topic doesn't match the current P2 (Preview) UI.

**Comment by JeremyTBradshaw** [comment] 2021-01-27 23:13
@chrisda @ronnyholtmaat I found that to add the app to the Exchange Administrator role group (only referred to as Role in AAD, I had to use PowerShell as of late because only groups are available to do so in the GUI anymore.  I used `Add-AzureADDirectoryRoleMember -ObjectId <Exchange Administrator ID> -RefObjectId <Enterprise Apps: registered app's ObjectId>`

**Comment by chrisda** [comment] 2021-01-29 22:34
I just completed a major overhaul of [the topic](https://docs.microsoft.com/powershell/exchange/app-only-auth-powershell-v2) with lots of screenshots to match the current UI. I agree that several weeks ago when I started, something was amiss; Step 5 didn't work at all as described, and I couldn't figure out how to proceed. Whatever mojo the Azure AD team was working through seems to have cleared up. At least for me in my tenant.

Please comment here if any of the steps don't match your UI. Also be aware: these instructions are NOT written for PIM; PIM has a different click path and slightly different UI. Notice none of the new screenshots have PIM in them.

Also see related issues #7068 and #7113.

**Comment by decturau** [comment] 2021-01-29 22:44
@chrisda i think the intial request was open regarding API permissions rather than RBAC (Step 2, not step 5). The doc updated step 2 advising to edit the manifest (which works). However the concern is more around the Outlook v2.0 REST API will stop working on November 2022. 

So yes, today we can configure it as per the doc and connect. But when that API stops working, i sense the apps will as well with access denied.

**Comment by chrisda** [comment] 2021-02-23 20:09
This issue has been resolved. Nothing to report about what to do when the REST API stops working next year.

Thanks for the feedback.

Closing

**Closed by chrisda** 2021-02-23 20:09 UTC
Labels: area:exchange
