### ISSUE TITLE
What module is is this in

### ISSUE THREAD

**Issue by fatherjack** [MicrosoftDocs/office-docs-powershell#3764] opened 2019-07-29 20:07 UTC
Module link (Module: exchange at top of page) goes to a dead link / 404 - https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/?view=exchange-ps.

What module is this command in please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3aa0b9-dbc1-075e-901f-fa091ceff700
* Version Independent ID: f764ed33-552b-d2b6-6089-f01fcd91c19d
* Content: [Set-MailboxAutoReplyConfiguration (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailboxautoreplyconfiguration?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/mailboxes/Set-MailboxAutoReplyConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/mailboxes/Set-MailboxAutoReplyConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment] 2019-07-30 12:02
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2019-07-31 22:46
Duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/3620

**Comment by get-itips** [comment] 2019-08-14 12:04
Hello @fatherjack as this is also mentioned in another issue (referenced here in my last message) we will proceed closing this one, please follow up on the other one.

**Comment by get-itips** [comment] 2019-08-20 13:58
Hello @fatherjack I can confirm that a bug has been created internally at Microsoft to address this issue.
Updates of the progress will be handled at the referenced #3620 issue.
Thank you

**Comment by yogkumgit** [comment] 2019-08-21 10:40
@get-itips  Thank you very much for the contribution and sharing this explanation. @fatherjack 
Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment] 2019-08-21 10:40
@officedocsbot close

**Closed by yogkumgit** 2019-08-21 10:40 UTC
Labels: area:docs, area:exchange
