### ISSUE TITLE
can't open new-csonlinesession when connected to Teams powershell via ApplicationID

### ISSUE THREAD

**Issue by bsj17** [MicrosoftDocs/office-docs-powershell#6737] opened 2020-10-23 12:40 UTC
> Hello @bender86
> How are you?
> Those errors are probably related to the method you used to generate the certificate (See the invalid provider error)
> 
> I tested the cmdlet to see if any documentation change was needed, as here we are limited to documentation issues, and I could connect successfully when I followed this [other article](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-authenticate-service-principal-powershell#create-service-principal-with-self-signed-certificate) specially the Ps example used for generating the self-signed cert.
> 
> I hope this info helps you.

I can confirm described method in [article](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-authenticate-service-principal-powershell#create-service-principal-with-self-signed-certificate) works.
I can successfully connect  to Teams using certificate and appID, however if I try to connect to SfB online this fails:

New-CsOnlineSession : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following
error message : The WinRM client cannot process the request. The authentication mechanism requested by the client is no
t supported by the server or unencrypted traffic is disabled in the service configuration. Verify the unencrypted traff
ic setting in the service configuration or specify one of the authentication mechanisms supported by the server.  To us
e Kerberos, specify the computer name as the remote destination. Also verify that the client computer and the destinati
on computer are joined to a domain. To use Basic, specify the computer name as the remote destination, specify Basic au
thentication and provide user name and password. Possible authentication mechanisms reported by server: For more inform
ation, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ New-CsOnlineSession
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], PSRemotingTransportException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession

New-CsOnlineSession : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following
error message : The WinRM client cannot process the request. The authentication mechanism requested by the client is no
t supported by the server or unencrypted traffic is disabled in the service configuration. Verify the unencrypted traff
ic setting in the service configuration or specify one of the authentication mechanisms supported by the server.  To us
e Kerberos, specify the computer name as the remote destination. Also verify that the client computer and the destinati
on computer are joined to a domain. To use Basic, specify the computer name as the remote destination, specify Basic au
thentication and provide user name and password. Possible authentication mechanisms reported by server: For more inform
ation, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ New-CsOnlineSession
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-CsOnlineSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Open.Te
   ams.SfbOnline.CsSession.NewCsOnlineSession

_Originally posted by @bsj17 in https://github.com/MicrosoftDocs/office-docs-powershell/issues/5008#issuecomment-715304671_

**Comment by get-itips** [comment] 2020-10-30 12:03
Hello @bsj17 
What parameters are you exactly using with New-CsOnlineSession? are you using one of the examples found [here](https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinesession?view=skype-ps) ?
Thanks

**Comment by bsj17** [comment] 2020-10-30 12:51
Using following 
$sfbSession = New-CsOnlineSession
Import-PSSession $sfbSession

**Comment by get-itips** [comment] 2020-10-30 18:51
Ok so you are providing Credentials to SfB's New-CsOnlineSession?

**Comment by bsj17** [comment] 2020-10-30 19:04
No.  New-CsOnlineSession should pick-up token generated by Connect-MicrosoftTeams -CertificateThumbprint <certTumbp> -ApplicationId <AppID>-TenantId <TenantID>.

If I login interactivly with Connect-MicrosoftTeams then New-CsOnlineSession does pick token. Issue is when using AppID as security principal

**Comment by get-itips** [comment] 2020-10-30 21:28
> No. New-CsOnlineSession should pick-up token generated by Connect-MicrosoftTeams -CertificateThumbprint "cert thumprint" -ApplicationId "app id guid"-TenantId "tenat id guid".
> 
> If I login interactivly with Connect-MicrosoftTeams then New-CsOnlineSession does pick token. Issue is when using AppID as security principal
> 
> Module version
> Name : MicrosoftTeams
> Version : 1.1.6

Ok, i am not sure if that you are trying to do, is supposed to work, as the method described [here](https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install#sign-in) is using interactive logon.

Will try to do my own tests to verify if we need to adjust the documentation.
@tameemansari can you help on this one? I appreciate.

**Comment by bsj17** [comment] 2020-10-30 22:46
The goal is to use this with unattended script. How are we going to automate script if this will not work? :-)

**Comment by get-itips** [comment] 2020-10-31 15:36
> The goal is to use this with unattended script. How are we going to automate script if this will not work? :-)

Branko, how are you? what I am saying is that maybe it is not yet released the use of CertificateThumbprint + ApplicationId in combination with New-CsOnlineSession, that is what I will try to confirm. 

I could reproduce the scenario.

Thanks

**Comment by bsj17** [comment] 2020-11-02 09:23
Thanks @get-itips for looking into this.

**Comment by yogkumgit** [comment] 2020-11-09 14:32
@get-itips Thank you very much for the contribution and sharing this explanation. @bsj17 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by heintonny** [comment] 2021-01-17 20:28
**Hi @yogkumgit: Do you have any update on this requirement?**

I also need to use the New-CsOnlineSession comandlet in PowerShell module MicrosoftTeams from Azure Automation, and I can't get the authentication to work when I use ApplicationId to authenticate the Connect-MicrosoftTeams session.

The Azure Automation account have a managed Identity which I granted "Teams Service Administrator" role and "User Administrator" role.

**This part works good:**
```
# Get Azure Run As Connection Name
$connectionName = "AzureRunAsConnection"

# Get the Service Principal connection details for the Connection name
$servicePrincipalConnection = Get-AutomationConnection –Name $connectionName         

# Logging in to Azure AD with Service Principal
Connect-AzureAD –TenantId $servicePrincipalConnection.TenantId `
    –ApplicationId $servicePrincipalConnection.ApplicationId `
    –CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint

# Simple command to confirm connection and authentication
$guests = Get-AzureADUser -Filter "UserType eq 'Guest'"  -All $True | Select-Object ObjectId
Write-Output "We have $($guests.count) guests accounts in our directory"
```

**... but, the New-CsOnlineSession commandlet is still not supported when signing in with ApplicationId (failed).**
```
Count guest accounts in directory
We have 173 guests accounts in our directory

New-CsOnlineSession : One or more errors occurred.: Unable to find an entry point named 'GetPerAdapterInfo' in DLL 
'iphlpapi.dll'.
At line:28 char:1
+ New-CsOnlineSession
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], CmdletInvocationException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
 
New-CsOnlineSession : One or more errors occurred.: Unable to find an entry point named 'GetPerAdapterInfo' in DLL 
'iphlpapi.dll'.
At line:28 char:1
+ New-CsOnlineSession
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], AadAuthenticationFailedException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
 
New-CsOnlineSession : One or more errors occurred.
At line:28 char:1
+ New-CsOnlineSession
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], AggregateException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
 
New-CsOnlineSession : Unable to find an entry point named 'GetPerAdapterInfo' in DLL 'iphlpapi.dll'.
At line:28 char:1
+ New-CsOnlineSession
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], EntryPointNotFoundException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
 
Connect-MicrosoftTeams : One or more errors occurred.: Unable to find an entry point named 'GetPerAdapterInfo' in DLL 
'iphlpapi.dll'.
At line:28 char:1
+ New-CsOnlineSession
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MicrosoftTeams], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Open.Teams.CommonLibrary.AadAuthenticationFailedException,Microsoft.Open.Teams.C
ommonLibrary.ConnectMicrosoftTeams
```

**Comment by tinsheep** [comment] 2021-01-23 00:20
@heintonny did you get a resolution on this? why was this closed because it is not supported? thanks!

**Comment by adpe** [comment] 2021-05-03 09:57
Hi @get-itips 

I'm facing the same problem. Can we please re-open this issue?

**Comment by yogkumgit** [comment] 2021-05-05 14:43
@get-itips

**Comment by get-itips** [comment] 2021-05-05 15:43
Hello everyone, as this is not a documentation issue (here we are limited to documentation fixes, improvements, typos, etc) I suggest opening a support ticket directly from your tenant. Thank you all

**Closed** 2021-06-28 14:25 UTC
Labels: area:teams / skype
