### ISSUE TITLE
Subnet length

### ISSUE THREAD

**Issue by vnewbaker-bw** [MicrosoftDocs/office-docs-powershell#5261] opened 2020-04-07 17:53 UTC
There is no mask defined for this command, how is the client subnet determined accurately without that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6825b30-7029-3e2f-90d5-7451242132d9
* Version Independent ID: e7df1f32-cdfc-718c-bc7d-c47b0fa4def0
* Content: [Get-CsOnlineLisSubnet (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinelissubnet?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineLisSubnet.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsOnlineLisSubnet.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @junya
* Microsoft Alias: **junya**

**Comment by yogkumgit** [comment] 2020-04-08 10:24
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2020-04-15 17:18
Hello @kaishuipinggai Jundong, can you please shed some light here on the way the cmdlet determines the mask? I appreciate
Also, I see that the GitHub login metadata for you on this and other cmdlets is not correct.

**Comment by get-itips** [comment] 2020-04-29 15:15
@kaishuipinggai Jundong, Can you kindly reply to my inquiry? Thank you

**Comment by get-itips** [comment] 2020-05-12 13:35
@tomkau Tom, can you help here? Thanks

**Comment by kaishuipinggai** [comment] 2020-05-14 18:01
Hi sorry for the late response I might have missed this one.
So for the length and mask, we don't specify them in this commandlet. This is kind of by design since we agreed within the team to only let the tenant admin input the subnet, that is good enough for the functionality. The Lis subnet is mapping with the location information, with the location ID, with the same purpose of finding the location information by subnet/WirelessAccessPoint/Port/Switch.

**Comment by get-itips** [comment] 2020-05-14 18:13
Thanks @kaishuipinggai Jundong for that explanation.
I hope @vnewbaker-bw it clarifies to you.

**Comment by kaishuipinggai** [comment] 2020-05-14 18:38
Forget to add:
Let me give one example, assume the following is a valid input into our service to query for retrieving the LocationInfo:

{
    "tenantid": "ffffffff-ffff-ffff-ffff-ffff0000ffff",
    "publicIp": "100.100.100.200",
    "networkinformation": {
      "ipv4": "200.100.222.111",
      "subnetLengthIpv4": "24",
      "bssid": "02-15-03-49-CF-6D",
      "e911": [
        {
          "chassisId": "12345",
          "portId": "8"
        }
      ]
    }
  }

So internally what happens is, when a Microsoft Teams app user logs in, it brings the current client's IPv4 address "200.100.222.111" and his subnetlength, and we DO the masking and then use "200.100.222.0" to see if we find any records that Tenant Admin have once input by using "Set-CsOnlineLisSubnet -Subnet 200.100.222.0". If it finds the match based on the same subnet then it will return the correct location information for "200.100.222.0". Otherwise, it will return not found or not a valid request and send it back to the Teams client.

**Comment by vnewbaker-bw** [comment] 2020-05-14 19:28
Thanks for the clarification, that is what I wanted to know

**Comment by yogkumgit** [comment] 2020-05-15 10:08
@get-itips and @kaishuipinggai  Thank you very much for the contribution and sharing this explanation. @vnewbaker-bw Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-05-15 10:08 UTC
Labels: area:teams / skype
