### ISSUE TITLE
Role Assignment for Registered App displays Error Message

### ISSUE THREAD

**Issue by johnholliday** [MicrosoftDocs/office-docs-powershell#8854] opened 2022-01-25 14:54 UTC
Following the steps in this article results in an error when attempting to grant admin consent.  The article should explain that the user must click the "Enterprise application" link at the bottom of the page.

```
Grant consent failed with error: Claim is invalid: c97b873f-f59f-49aa-8a0e-52b32d762124 does not exist on resource application 00000002-0000-0ff1-ce00-000000000000. [cykiIH9996kFa8pv36jfoC]
```
The final step to add role assignments to the newly registered app does not work.  The page displays an error message at the top: "Required fields are missing or invalid".  This is misleading.  The article should explain that you have to ignore the error and click "Next >" at the bottom of the page to provide justification for adding the role assignment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2cfafdf-cbe9-2ffe-eabe-becc66d51728
* Version Independent ID: 4a46c8a8-dc70-d877-271e-6679c465a6d5
* Content: [App-only authentication](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#step-1-register-the-application-in-azure-ad)
* Content Source: [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/app-only-auth-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-01-26 21:26
Closing as duplicate of #8853

**Closed by chrisda** 2022-01-26 21:26 UTC
Labels: duplicate, area:exchange
