### ISSUE TITLE
Configure telephony to Microsoft Teams

### ISSUE THREAD

**Issue by terblas** [MicrosoftDocs/office-docs-powershell#5379] opened 2020-04-23 21:09 UTC
Hello, I want to configure the Teams tenant to assign a phone number to my users but when I run the Set-CsUser i get an error saying the OnPremLineURI cannot be found, The user has the phone system license and the office 365 F3 license, I tested in other tenants and I dont get the same error. Does anybody know why I am getting the error?

PS C:\Users\Administrator> Set-CsUser -Identity user@domain -EnterpriseVoiceEnabled $true -HostedVoiceMail $true -OnPremLineURI tel:+52XXXXXXXXXX
Set-CsUser : A parameter cannot be found that matches parameter name 'OnPremLineURI'.
At line:1 char:95

... priseVoiceEnabled $true -HostedVoiceMail $true -OnPremLineURI tel:+52 ...
                                               ~~~~~~~~~~~~~~
CategoryInfo : InvalidArgument: (:) [Set-CsUser], ParameterBindingException
FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Rtc.Management.AD.Cmdlets.SetOcsUserCmdlet

**Comment by yogkumgit** [comment] 2020-04-24 10:53
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2020-04-30 14:09
Hello @terblas how are you?
I could not reproduce to see if we have to impact any documentation, as here we are limited to documentation issues, please kindly open a support ticket directly in your tenant.
Thank you

**Comment by yogkumgit** [comment] 2020-05-01 11:33
@get-itips Thank you very much for the contribution and sharing this explanation. @terblas 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Closed** 2020-05-01 11:33 UTC
Labels: area:teams

**Comment by onehit** [comment] 2020-10-02 15:22
In case anyone else runs into this issue, we resolved it by adding the "Skype for Business Administrator" role to the admin user - despite being Teams Only tenant-wide, "Teams Service Administrator" was not enough to get this property when connecting to the online connector.

**Comment by get-itips** [comment] 2020-10-05 13:47
Thanks for leaving your feedback @onehit

**Comment by sasi8819** [comment] 2021-05-02 14:55
I'm also facing issue. 


PS C:\windows\system32> Set-CsUser -Identity user@domain.com  -OnPremLineURI tel:+44XXXXXXX -EnterpriseVoiceEnabled $true -HostedVoiceMail $true
Set-CsUser : A parameter cannot be found that matches parameter name 'Identity'.
At line:1 char:12
+ Set-CsUser -Identity user@domain.com -OnPremLineURI tel:+44XXXXX ...
+            ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-CsUser], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-CsUser

**Comment by ruudvanstrijp** [comment] 2021-05-05 11:07
@sasi8819 Do you happen to just have upgraded the MicrosoftTeams module to 2.3?
I have the same issue since upgrading from 1.1.6 to 2.3 this morning. The new Set-CsUser command somehow has '-id' instead of '-identity', and it has no access to my Teams tenant: "Set-CsUser : Access Denied.".

I have installed a new VM, where I did the following tests:
- Set-CsUser in Powershell: Command not found
- Install-Module -Name MicrosoftTeams -Force -Scope AllUsers
- Set-CsUser is now found, but only has -id as parameter, and not -identity. When I try to run it, it tells me I need to connect to MS Teams first using Connect-Microsoft Teams (which is to be expected)
- Connect-MicrosoftTeams
- Set-CsUser -id 'firstname.lastname@domain.com' Response:  "Set-CsUser : Access Denied."

If this is the case, this would be a major bug in the new 2.3 module. Can please double check my findings?

**Comment by VincentCheng-Hatch** [comment] 2021-05-17 17:25
The issue is caused by version 2.3.
The command does not take -identity parameter. Instead is uses -id parameter.

I reverted to version 2.0.0 of the teams module and all is good now.

#check module version installed
Get-InstalledModule MicrosoftTeams

#uninstall ver 2.3
Uninstall-Module MicrosoftTeams

#install version 2.0.0
Install-Module -Name MicrosoftTeams -RequiredVersion 2.0.0

--------------------------

If anyone figured how to make this work on ver2.3, let us know.
