### ISSUE TITLE
Powershell Command on this page is wrong

### ISSUE THREAD

**Issue by Vleugelsjef** [MicrosoftDocs/office-docs-powershell#6592] opened 2020-09-24 07:15 UTC
Hi,
Documentation on this page is not correct. The purple note says:
"If you've already installed the EXO V2 module, the previous command will work as written. If you haven't already installed the module, you can install and load the latest public version of the module in one step by running the command: Import-Module -Name ExchangeOnlineManagement."

The command needs to be Install-Module -Name ExchangeOnlineManagement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2020-09-24 17:25
@Vleugelsjef, confirmed. See issue [6565]<https://github.com/MicrosoftDocs/office-docs-powershell/issues/6565> for background, which turns out to be incorrect or I misunderstood. I uninstalled the module from my PC, and then ran the command with the following result:

```powershell
PS C:\WINDOWS\system32> Import-Module -Name ExchangeOnlineManagement
Import-Module : The specified module 'ExchangeOnlineManagement' was not loaded because no valid module file was found
in any module directory.
At line:1 char:1
+ Import-Module -Name ExchangeOnlineManagement
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ExchangeOnlineManagement:String) [Import-Module], FileNotFoundExce
   ption
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

I'll remove the note from the topics.

Thanks for the feedback.

Closing

**Closed by chrisda** 2020-09-24 17:25 UTC
Labels: area:exchange
