### ISSUE TITLE
The hyperlink of SharePoint Management Shell is in the wrong position in a Japanese article.

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/office-docs-powershell#6095] opened 2020-07-07 09:36 UTC
The link is in the light blue marker currently.
Based on the original article, I think it is better to replace to the yellow part.

https://docs.microsoft.com/ja-jp/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps
![image](https://user-images.githubusercontent.com/13634805/86758840-168de900-c07f-11ea-972e-8b647c00b362.png)

[Enter feedback here]

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05b23d72-33ed-a6a1-a442-a5e5cf039f9f
* Version Independent ID: 4247cf37-3667-2007-7251-46ed80f58ef5
* Content: [Get started with the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps&source=docs)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment] 2020-07-08 08:04
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2020-07-13 14:47
@officeglobal Can you kindly handle this intl issue? thank you

**Comment by yogkumgit** [comment] 2020-07-22 06:08
@OfficeGlobal Please update the status.

**Comment by OfficeGlobal** [comment] 2020-07-23 11:38
@kefujino , @yogkumgit the article was HumanTransalted and published live

**Comment by get-itips** [comment] 2020-07-23 12:48
> @kefujino , @yogkumgit the article was HumanTransalted and published live

Hello @OfficeGlobal 
Do you refer to this https://docs.microsoft.com/ja-jp/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps ?
I am not finding a ja-jp version of the article on the repo, did you find it? it looks like engine translated. Thank you

**Comment by OfficeGlobal** [comment] 2020-07-24 06:59
Hello @get-itips , yes the article https://docs.microsoft.com/ja-jp/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps was HumanTranslated and published live. 

**JPN repository:** https://github.com/MicrosoftDocs/office-docs-powershell.ja-JP/blob/live/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md

![image](https://user-images.githubusercontent.com/47977325/88367372-e5eec480-cd8b-11ea-86af-1c60bb20928a.png)

**Comment by get-itips** [comment] 2020-07-24 12:23
> Hello @get-itips , yes the article https://docs.microsoft.com/ja-jp/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps was HumanTranslated and published live.
> 
> **JPN repository:** https://github.com/MicrosoftDocs/office-docs-powershell.ja-JP/blob/live/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
> 
> ![image](https://user-images.githubusercontent.com/47977325/88367372-e5eec480-cd8b-11ea-86af-1c60bb20928a.png)

@OfficeGlobal 
Thanks for the information, did not know about that metadata value, it will be useful for future reference.
It seems that repo is private. cc @yogkumgit

**Comment by get-itips** [comment] 2020-07-28 12:19
Hello @kefujino 
I can confirm this was internally handled and fixed, you should see the change soon when the page gets published.
Thanks

**Comment by yogkumgit** [comment] 2020-08-06 07:57
@get-itips  Thank you very much for the contribution and sharing this explanation. @kefujino Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-08-06 07:57 UTC
Labels: area:spo-powershell
