### ISSUE TITLE
New-MailboxSearch -Name "Hold-tailspintoys" -SearchQuery    

### ISSUE THREAD

**Issue by s4vishwa** [MicrosoftDocs/office-docs-powershell#7994] opened 2021-06-28 14:15 UTC
-SearchQuery is not recognized as a cmdlet when running new-mailboxsearch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f39864e-398c-ad3a-129a-e1ca0b7af51e
* Version Independent ID: 17a7cf02-08f6-5eea-2e4e-842902278904
* Content: [New-MailboxSearch (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-mailboxsearch?view=exchange-ps#outputs)
* Content Source: [exchange/exchange-ps/exchange/New-MailboxSearch.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/New-MailboxSearch.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by s4vishwa** [comment] 2021-06-28 14:18
![image](https://user-images.githubusercontent.com/42575304/123652218-19d33500-d7fa-11eb-803e-65f733bee07d.png)

**Comment by chrisda** [comment] 2021-06-29 18:09
@s4vishwa, I'm closing this as a duplicate of #7993

**Closed by chrisda** 2021-06-29 18:09 UTC
Labels: area:exchange, duplicate
