### ISSUE TITLE
This page is unusable

### ISSUE THREAD

**Issue by ickthwart** [MicrosoftDocs/office-docs-powershell#6878] opened 2020-11-20 05:29 UTC
The table is much wider than the page width making it almost impossible to navigate as the horizontal scroll bar for the table is right at the bottom of the screen.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce35226-b40b-3c9f-a37f-585b84aa129e
* Version Independent ID: ac9953e2-769a-c115-b1c6-e6f6fc940db2
* Content: [Filterable properties for the Filter parameter](https://docs.microsoft.com/en-us/powershell/exchange/filter-properties?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/filter-properties.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/filter-properties.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2020-11-20 18:14
@ickthwart, I hear you. The RecipientFilter topic has the same problem:

<https://docs.microsoft.com/powershell/exchange/recipientfilter-properties>

If you click anywhere in the table, you can use the Left and Right arrow keys to scroll horizontally.

I think the problem is amplified by the 'column' on the right that narrows the page to hold the **Is this page helpful?** and **In this article** elements for the entire height of the page.

![image](https://user-images.githubusercontent.com/33166947/99833655-36e2af80-2b17-11eb-9398-19ea4ec83430.png)

I'll see if there's anything that can be done from an HTML/page rendering perspective (likely some CSS thing that forces text to break mid-word), but I'm not optimistic.

**Comment by ickthwart** [comment] 2020-11-23 02:50
Thanks Chris.
Even if just the 'Comments' column could be made narrower, that would help. As it stands, that column alone is wider than the display area (on my 1920 screen) so scrolling left and right to read that is just painful. I bet the page author had a super hi-res screen......
Thanks
Paul

**Comment by chrisda** [comment] 2021-02-23 21:51
Apparently, nothing can be done to narrow the columns or the table. The only option is to dismantle the table into a list, or use left and right arrow keys to scroll horizontally.

Thanks for the feedback.

Closing

**Closed by chrisda** 2021-02-23 21:51 UTC
Labels: area:exchange
