### ISSUE TITLE
Taxonomy field with multiple value's possible

### ISSUE THREAD

**Issue by JonEOffice** [MicrosoftDocs/office-docs-powershell#971] opened 2018-05-07 11:19 UTC
Then use the following example:
$Taxvalue = "15c4c4e4-4b67-4894-a1d8-de5ff811c791","16c4c4e4-4b67-4894-a1d8-de5ff811c792"
Set-PnPDefaultColumnValues -List Documents -Field TaxKeyword -Value $Taxvalue
No other way is accepted since for the taxonomy fields.
If you use a semicolon (;) it does not get split. For the other value types the semicolon does work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d78ff9-623e-2a39-bf30-1e8cbfcb5b84
* Version Independent ID: 9776e287-5b18-df0e-4130-2237ffee595a
* Content: [Set-PnPDefaultColumnValues (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpdefaultcolumnvalues?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPDefaultColumnValues.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPDefaultColumnValues.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment] 2018-05-08 20:01
@VesaJuvonen a PnP cmdlet for you.

**Comment by erwinvanhunen** [comment] 2018-06-11 08:57
@JonEOffice I am unfortunately not able to reproduce this. As you state, the value needs to be separated with a comma, otherwise PowerShell will think of it as a string instead of a multi-value.  If the issue still stands with the latest version of PnP PowerShell, can you please create an issue at https://github.com/sharepoint/pnp-powershell/issues so we can follow up there?

**Comment by VesaJuvonen** [comment] 2018-06-11 10:10
Closed based on the update from @erwinvanhunen as PR is merged.

**Closed by VesaJuvonen** 2018-06-11 10:10 UTC
Labels: area:pnp-powershell
