### ISSUE TITLE
Diagnostic parameter no longer available

### ISSUE THREAD

**Issue by murrato1** [MicrosoftDocs/office-docs-powershell#1408] opened 2018-07-11 02:38 UTC
In the latest version of the Exchange Online Powershell Module there is no -Diagnostic or -DiagnosticArgument parameter.  Instead, there is a -DiagnosticInfo parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549910d8-771a-2c38-c750-77f563b54878
* Version Independent ID: b956cdcb-3c3b-edd3-80b1-9573128a7414
* Content: [Get-MoveRequestStatistics (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/get-moverequeststatistics?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/move-and-migration/Get-MoveRequestStatistics.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/move-and-migration/Get-MoveRequestStatistics.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2018-07-12 19:24
@murrato1, I confirmed that _Diagnostic_ and _DiagnosticArgument_ parameters are available only in on-premises Exchange, and that the _DiagnosticInfo_ parameter is only available in Exchange Online.

When you use the _DiagnosticInfo_ parameter, is it a switch that doesn't require a value? What does it do for you. From what I can tell, _DiagnosticInfo_ is available in Exchange Online on these additional cmdlets:

- Get-MailboxFolderStatistics

- Get-MailboxImportRequestStatistics

- Get-MailboxRestoreRequestStatistics

- Get-MigrationBatch

- Get-MigrationEndpoint

- Get-MigrationStatistics

- Get-MigrationUserStatistics

- Get-PublicFolderMailboxMigrationRequestStatistics

- Get-PublicFolderMigrationRequestStatistics

- Get-SyncRequestStatistics

Yet it isn't defined like a traditional parameter.

**Comment by AndreaBarr** [comment] 2018-09-20 22:50
@murrato1 Thank you for this feedback

It looks like Chris addressed this issue. I am going to close this issue. If the issue is not resolved please reopen the issue.

**Closed by AndreaBarr** 2018-09-20 22:50 UTC
Labels: area:exchange
