### ISSUE TITLE
Invalid Authentication issue again!!

### ISSUE THREAD

**Issue by yeshwanthjagannath** [MicrosoftDocs/office-docs-powershell#1206] opened 2018-06-08 15:32 UTC
Again being faced with the below error:

New-Team : Error occurred while executing 
Code: InvalidAuthenticationToken
Message: Access token validation failure.
InnerError:
  RequestId: f55a9e67-e00e-4264-a119-7e22f19e9438
  DateTimeStamp: 2018-06-08T15:29:39
HttpStatusCode: InvalidAuthenticationToken

At line:15 char:10
+ $group = New-Team -DisplayName $teamname -alias $alias -AccessType Pr ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Team], ApiException
    + FullyQualifiedErrorId : 
Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdlets.PowerShell.Custom.NewTeam

This time the powershell is provisioned as an Azure runbook and this error is being thrown every time. Any leads?

**Comment by kenwith** [comment] 2018-06-08 16:49
@yeshwanthjagannath - I am not sure on this one but want to make sure this gets resolved for you ASAP. Would you please open a service request in your tenant admin? Here is a quick video: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs. Let's keep this open until resolved.

**Comment by yeshwanthjagannath** [comment] 2018-06-13 21:22
@kenwith  - Did some more digging on this issue and found that when i execute in Windows PowerShell with the cmdlet: Connect-MicrosoftTeams, i get all four attributes as shown in the first part of the image.

However, when i do same on Azure Runbook, i do not see the TenantDomain attribute being returned from the cmdlet: Connect-MicrosoftTeams. Maybe this could be a lead? 

Please take a look at the images and let me know. This is causing a big gap in our automation process to provision teams and need help with resolving this at the earliest.

![image](https://user-images.githubusercontent.com/8189744/41378793-103bea7e-6f15-11e8-8c7a-712949ecbf2d.png)

**Comment by kenwith** [comment] 2018-06-13 21:30
Linking this issue too: https://github.com/MicrosoftDocs/office-docs-powershell/issues/156

@SamCosby - FYI that support case coming through on this and I can get any info back into the docs.

**Comment by kenwith** [comment] 2018-06-13 21:55
@yeshwanthjagannath - thanks for looping me on support case. I will follow and get that knowledge back into the docs for the community. Appreciated.

**Comment by yeshwanthjagannath** [comment] 2018-06-13 22:53
@kenwith - Thank you, look forward to a faster resolution on this.

**Comment by SamCosby** [comment] 2018-06-14 11:52
@yeshwanthjagannath - I've seen this before caused by a CA policy applied. Can you check to see if your account has any CA policies applied and if so, remove for testing to validate if it's that?

**Comment by kenwith** [comment] 2018-06-26 19:10
@yeshwanthjagannath - were you able to get this resolved? can we close this and anything that you can think should be added to the docs?

**Comment by kenwith** [comment] 2018-08-13 23:18
I am going to close this out. I think this was taken care of with a support ticket.

**Closed by kenwith** 2018-08-13 23:18 UTC
Labels: area:teams
