### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by cwaddzz** [MicrosoftDocs/office-docs-powershell#10727] opened 2023-04-13 10:37 UTC
[Enter feedback here]

Following the instruction to install the powershell necessary to manage Exchange online

Install the Exchange Online PowerShell module
To install the module for the first time, complete the following steps:

Install or update the PowerShellGet module as described in [Installing PowerShellGet](https://learn.microsoft.com/en-us/powershell/scripting/gallery/installing-psget).

The link gives a  404 error

![image](https://user-images.githubusercontent.com/68278590/231733876-75e1b3ca-92c8-4e81-9f23-dbb2202cd2a0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module and V3 module](https://learn.microsoft.com/en-gb/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-and-maintain-the-exchange-online-powershell-module)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**
*

**Comment by chrisda** [comment] 2023-04-13 16:37
@cwaddzz, if you Bing/Google search for "installing PowerShellGet", that article is the first hit, but the link also 404's.

So, something is definitely wrong. Perhaps the problem is transient (will be fixed)?

**Comment by yogkumgit** [comment] 2023-04-27 11:39
@cwaddzz hope link is working for you now. Proceed to close this. Thanks

**Closed** 2023-04-27 11:39 UTC
Labels: area:exchange
