### ISSUE TITLE
Description about UseDatabaseRetentionDefaults is inadequate

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/office-docs-powershell#7411] opened 2021-03-12 02:43 UTC
Description about UseDatabaseRetentionDefaults is inadequate, or totally wrong. 

```
-UseDatabaseRetentionDefaults
This parameter is available or functional only in on-premises Exchange.

The UseDatabaseRetentionDefaults parameter specifies whether the mailbox uses the MailboxRetention attribute value that's configured on the mailbox database. This value controls how long deleted mailboxes are kept in the database before they are permanently removed (purged). The default value is 30 days. Valid values are:

$true: The mailbox uses the MailboxRetention value that's configured on the mailbox database. This is the default value.
$false: When the mailbox is deleted, it's retained indefinitely.
```

AFAIK it contains some problems such as:

1. The parameter is for deleted **items**, NOT for deleted **mailboxes**. The corresponding GUI is below and highlighted by yellow. The image is copied from [this page.](https://docs.microsoft.com/en-us/exchange/recipients/user-mailboxes/deleted-item-retention-and-recoverable-items-quotas?view=exchserver-2019) 

![image](https://user-images.githubusercontent.com/6519947/110883936-957ea400-8327-11eb-8c6a-31e7c34efe46.png)

2. If the value set to `$true`,  then the mailbox refers to DeletedItemRetention on their MailboxDatabase setting, NOT refers to MailboxRetention which defines the retention period for deleted mailboxes on the database.
3. If the value set to `$false`, then the mailbox refers to RetainDeletedItemsFor on their Mailbox setting, and it does not mean mailbox retention. RetainDeletedItemsFor corresponds to "Keep deleted items for (days)" on the above image and highlighted by green.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f835af-5905-368a-df68-6646782ad807
* Version Independent ID: 153ce2d2-dab5-9c8f-c511-ee3bc8ee2dbc
* Content: [Set-Mailbox (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2021-03-13 00:28
@hishikitetsuya, interesting catch. From what I can tell, that parameter has been incorrectly described (reference to the  MailboxRetention property) since Exchange 2010 (at least). Any semi-recent edits (likely by me) simply expanded upon this error, which made the error even more obvious..

I updated the parameter description based on your recommendation to match the UI:

> This parameter is available or functional only in on-premises Exchange.
> 
> The UseDatabaseRetentionDefaults parameter specifies whether the retention settings for items in the Recoverable Items folder in the mailbox are determined by the settings on the mailbox or the corresponding settings on the mailbox database. Valid values are:
> 
> - $true: The mailbox uses the applicable retention settings that are configured on the mailbox database. Any corresponding settings that are configured on the mailbox are ignored. This is the default value.
> - $false: The mailbox uses its own values for the applicable retention settings. Any corresponding settings that are configured on the mailbox database are ignored.
>
> The following retention settings are affected by this parameter:
>
> - DeletedItemRetention
> - RetainDeletedItemsUntilBackup


I also confirmed an issue that supposedly only affects Exchange 2010 and 2013 but also affects Exchange 2016 and Exchange 2019, so I added information about it:

> **Note**: If you set the RetainDeletedItemsUntilBackup parameter on the mailbox database to the value $true when the value of the UseDatabaseRetentionDefaults parameter on a mailbox is also $true (the default value), the value of the UseDatabaseRetentionDefaults property in the output of the Get-Mailbox cmdlet will erroneously appear as False. To verify the value of the UseDatabaseRetentionDefaults property on the mailbox, do the following steps in the Exchange Management Shell:
> 
> - Run the following command: `Import-Module ActiveDirectory`.
> - Replace \<Alias\> with the Alias value of the mailbox, and run the following command: `Get-ADUser <Alias> -Properties mDBUseDefaults | Format-List mDBUseDefaults`.

I also did other updates (mostly consistency) to other related and semi-related parameters in Set-Mailbox and Set-MailboxDatabase.

Thanks for the feedback.

Closing

**Closed by chrisda** 2021-03-13 00:28 UTC
Labels: Microsoft submitter, area:exchange
