### ISSUE TITLE
Teams Channel and Chat

### ISSUE THREAD

**Issue by zcvele** [MicrosoftDocs/office-docs-powershell#4788] opened 2020-01-30 06:15 UTC
This document has a placeholder for Teams Channel and Chat Policy settings , ref "This parameter is reserved for internal Microsoft use."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f61f69-e089-e3aa-f862-cf3fd29e15ce
* Version Independent ID: c3ef7379-c76e-9274-66f9-1e196d8c3407
* Content: [Set-RetentionCompliancePolicy (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-retention/set-retentioncompliancepolicy?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-RetentionCompliancePolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-retention/Set-RetentionCompliancePolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment] 2020-01-30 09:09
@officedocsbot assign @yogkumgit

**Comment by chrisda** [comment] 2020-01-31 18:04
@zcvele, are you saying these parameters are available to you and they work as expected?

**Comment by zcvele** [comment] 2020-01-31 19:29
Hi Chris

I did initial test and they were working in my test tenant. We should check all of them including multivalve entry.

My Microsoft alias is zoranc

Thank You

Thank You

Zoran
________________________________

**Comment by dariomws306** [comment] 2020-02-01 15:08
Hi @zcvele and @chrisda,

If you want I can help with this issue. I have been doing some testing and these parameters seems to be available to use but when I try to use any of the TeamsChannelLocation parameter I get:
"Only mailboxes are supported. The recipient "AdeleV@xxxxxxxxxxx.com" is of the type MailUser"

When I run Get-Recipient on Security & Compliance Center PowerShell all my UserMailbox accounts appear as MailUser. When I run Get-Recipient on Exchange Online PowerShell they appear as UserMailbox.

Also, I think we can take description for these parameters from New-RetentionCompliancePolicy and modify them for each Add or Remove variable.

Parameters list:
AddTeamsChannelLocation
AddTeamsChannelLocationException
AddTeamsChatLocation
AddTeamsChatLocationException
RemoveTeamsChannelLocation
RemoveTeamsChannelLocationException
RemoveTeamsChatLocation
RemoveTeamsChatLocationException


Thanks!

**Comment by yogkumgit** [comment] 2020-02-03 16:29
@chrisda Can Andres help you here. Please confirm. Thanks

**Comment by dariomws306** [comment] 2020-02-03 19:11
> @chrisda Can Andres help you here. Please confirm. Thanks

I think you meant Dario.

**Comment by yogkumgit** [comment] 2020-02-04 09:36
@dariomws306  yes, you are right. :)

**Comment by yogkumgit** [comment] 2020-02-11 13:30
@chrisda Please reply, Thanks

**Comment by chrisda** [comment] 2020-02-19 00:32
Confirmed that all Teams related parameters work, so I updated the descriptions accordingly.

Thanks for the feedback.

Closing.

**Comment by zcvele** [comment] 2020-02-19 00:58
Thank You Chris

Zoran Cvetkovic
Sr. Program Manager
Mobile: +1 416.576.2872
[cid:image001.jpg@01D1188D.834B2390]

**Closed** 2020-02-19 01:02 UTC
Labels: area:exchange

**Comment by dariomws306** [comment] 2020-02-19 14:36
Thank you Chris!!

**Comment by JeremyTBradshaw** [comment] 2020-03-13 12:53
Hi @dariomws @chrisda , I have (or the company that I'm doing work for does) the same issue where I can't successfully use -AddTeamsChannelLocationException, because the SC&C sees my mailboxes as MailUsers.  I assume SC&C is using a synced directory for this stuff, which surely makes sense / is the design, but I am not sure how this issue has been closed since the issue is still there.

You simply can't use the parameters that require the target users to be mailboxes, not MailUsers.

Did I miss something?  Thanks in advance.
