### ISSUE TITLE
MacOS support is broken - references should be removed.

### ISSUE THREAD

**Issue by slabber** [MicrosoftDocs/office-docs-powershell#7328] opened 2021-02-21 07:32 UTC
[Enter feedback here]
MacOS support is broken.  It is widely reported in the community.  References to MacOS support should be removed until MacOS support is fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [About the Exchange Online PowerShell V2 module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-and-maintain-the-exo-v2-module)
* Content Source: [exchange/docs-conceptual/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online-powershell-v2.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by navgupta1208** [comment] 2021-02-22 16:39
Hi @slabber 

Can you share more details about the MAC OS version which you are using ?

**Comment by slabber** [comment] 2021-02-23 07:19
Big Sur.  But this issue is present since Homebrew removed openssl 1.0.  Powershell core still ships with libmi.dylib from OMI that links to homebrew openssl 1.0.

Any fresh install of MacOS combined with following the instructions on this page to install Powershell will result in a broken installation.  EXO module will always error regarding missing WSMan due to the broken library above.

See https://github.com/PowerShell/PowerShell/issues/11188 amongst others.

**Comment by slabber** [comment] 2021-02-23 07:33
If you want a full explanation then try reading this excellent blog post.
https://www.bloggingforlogging.com/2020/08/21/wacky-wsman-on-linux/

Basically one arm of Microsoft (powershell) relies on another (OMI) and OMI has deprecated powershell support and they refuse to fix any issues.  If they continue to refuse and the powershell team do not find another implementation of WSMan then MacOS support can never be claimed.

**Comment by chrisda** [comment] 2021-02-23 18:17
Closing as duplicate of #7327

**Closed by chrisda** 2021-02-23 18:17 UTC
Labels: area:exchange, duplicate
