### ISSUE TITLE
TypeError: undefined has no properties after Add-PnPClientSidePage

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/office-docs-powershell#5433] opened 2020-04-30 18:42 UTC
I used Add-PnPClientSidePage -Name "newpage" -LayoutType "SingleWebPartAppPage"
It shows:
PageTitle            :
Sections             : {}
Controls             : {}
LayoutType           : SingleWebPartAppPage
ThumbnailUrl         :
KeepDefaultWebParts  : False
Context              : OfficeDevPnP.Core.PnPClientContext
PagesLibrary         : SitePages
PageListItem         : Microsoft.SharePoint.Client.ListItem
DefaultSection       : OfficeDevPnP.Core.Pages.CanvasSection
CommentsDisabled     : False
PageHeader           : OfficeDevPnP.Core.Pages.ClientSidePageHeader
PageId               : 18
SpaceContent         :
SupportedUILanguages : {1033, 1031, 1036, 2108...}
htmlWriter           :

but when I open it to edit, it shows:
**TypeError: undefined has no properties
in t in t in o in t in t in t in t in t in section in div in div in t in Styledt in t in o in t in t in t**
and there is no way to edit it
I am using the latest.
Any idea why?

**Comment by yogkumgit** [comment] 2020-05-01 11:13
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2020-05-05 12:48
Hello @Ofer-Gal  Miguel how are you?  👍

I will need to kindly ask you to visit [this other repo](https://github.com/SharePoint/PnP-PowerShell/) to open PnP issues/questions. PnP cmdlets are maintained by the community, a member of it will pick it up there. Thank you!

**Comment by VesaJuvonen** [comment] 2020-05-05 15:21
This is by design as all app pages should have an web part associated to it. Process is documented in the following documentation together with the video demo - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages

Not an issue in PnP PowerShell as such, so closing the issue.

**Closed by VesaJuvonen** 2020-05-05 15:21 UTC
Labels: area:pnp-powershell, status:by-design, type:question
