### ISSUE TITLE
Get-CsCallQueue returns only 100 call queues

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/office-docs-powershell#5022] opened 2020-03-04 09:52 UTC
Hi,
Is it only me who have the following problem:
```
PS C:\> Get-CsCallQueue | Measure-Object
.
.
.
Count : 100
```

Assuming of course you have more than 100 Call Queues? I tested this on test tenant which is not at the moment available anymore.

**Comment by yogkumgit** [comment] 2020-03-04 11:49
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2020-03-14 18:40
Hello @Petri-X 
While I set up my lab for this, what happens if you run

> Get-CsCallQueue -Skip 100

Thanks

**Comment by Petri-X** [comment] 2020-03-16 17:19
The command:
**Get-CsCallQueue -WarningAction silentlycontinue  | ft  name**

Returns:
```
Name
----
Testi101
Testi102
.
.
Testi199
Testi200
```

**Get-CsCallQueue -WarningAction silentlycontinue -Skip 2 | ft  name**

Returns:
```
Name
----
Testi103
Testi104
.
.
Testi201
Testi202
```

Still maximum 100.

Here is the command to create 200 queues:
**101..300 | % { New-CsCallQueue -Name "Testi$($_)" -UseDefaultMusicOnHold $true } | ft name**
That is working with trial tenants.

**Comment by get-itips** [comment] 2020-03-16 19:49
@Petri-X 
Ok thanks for that.
I could verify that, that is by design of the cmdlet, and the same is for many other -Cs cmdlets. I will propose thru a PR the addition of some information to notify the user about this.
Thank you

**Comment by Petri-X** [comment] 2020-03-17 07:41
No, it is not correct and default behavior.

The documentation for [Get-CsCallQueue](https://docs.microsoft.com/en-us/powershell/module/skype/get-cscallqueue?view=skype-ps) says:

```
-Skip
Default value: | 0
```
And having 100 as a default would be very strange when none of other CMDLets have it.

**Comment by get-itips** [comment] 2020-03-17 15:13
@Petri-X 
The default, when not specifying Skip, is 100 results. I am not saying that the default value of Skip parameter is 100.

These cmdlets also have the same behavior
_Get-CsOnlineDialInConferencingUserInfo
Get-CsOnlineVoiceUser
Get-CsOnlineDialInConferencingUserInfo_

**Comment by Petri-X** [comment] 2020-03-17 15:24
So we are reading this statement differently:
![image](https://user-images.githubusercontent.com/43988151/76871417-b5de6480-6873-11ea-85ba-90b23c8e8704.png)


Also Get-CsOnlineVoiceUse says also:

> -Skip
> Specifies the number of users to skip. If you used the First parameter to return the first 50 users and wanted to get another 50, you could use -Skip 50 to avoid returning the first 50 you've already reviewed. **The default is 0**.

Or at least I cannot see "100" on these :)

**Comment by get-itips** [comment] 2020-03-17 15:54
> So we are reading this statement differently:
> ![image](https://user-images.githubusercontent.com/43988151/76871417-b5de6480-6873-11ea-85ba-90b23c8e8704.png)
> 
> Also Get-CsOnlineVoiceUse says also:
> 
> > -Skip
> > Specifies the number of users to skip. If you used the First parameter to return the first 50 users and wanted to get another 50, you could use -Skip 50 to avoid returning the first 50 you've already reviewed. **The default is 0**.
> 
> Or at least I cannot see "100" on these :)

What happens if you specify -Skip without a number?

**Comment by Petri-X** [comment] 2020-03-17 18:05
@get-itips 
Would you like be so nice and share what did you expected to happen?

```
PS C:\> Get-CsCallQueue -WarningAction silentlycontinue -Skip | ft name
Get-CsCallQueue : Missing an argument for parameter 'Skip'. Specify a parameter of type 'System.Object' and try again.
At line:1 char:49
+ Get-CsCallQueue -WarningAction silentlycontinue -Skip | ft name
+                                                 ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-CsCallQueue], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Get-CsCallQueue
```

You still not believe this is a pure bug in module?

**Comment by get-itips** [comment] 2020-03-17 18:18
> @get-itips
> Would you like be so nice and share what did you expected to happen?
> 
> ```
> PS C:\> Get-CsCallQueue -WarningAction silentlycontinue -Skip | ft name
> Get-CsCallQueue : Missing an argument for parameter 'Skip'. Specify a parameter of type 'System.Object' and try again.
> At line:1 char:49
> + Get-CsCallQueue -WarningAction silentlycontinue -Skip | ft name
> +                                                 ~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Get-CsCallQueue], ParameterBindingException
>     + FullyQualifiedErrorId : MissingArgument,Get-CsCallQueue
> ```
> 
> You still not believe this is a pure bug in module?

@Petri-X 
Of Course !
If you run Get-CsCallQueue without parameters, that is what is called "default behaviour" and the default, running that without parameters, is outputting 100 results, do you agree?
So, I added that behavior to the article thru a Pull Request. I think this was intended and designed as a feature, as there is a -Skip and -First parameters, and we can also find the same on other cmdlets.
If you feel this is a bug and should be changed, kindly please fill a request [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwj1oLKUj6LoAhUsCrkGHeKcCsIQFjAAegQIBxAC&url=https%3A%2F%2Fmicrosoftteams.uservoice.com%2F&usg=AOvVaw2ki3ljq8xpzxo6JePy4jb-) as here we are limited to documentation changes.

Thank you.

**Comment by Petri-X** [comment] 2020-03-17 19:12
@get-itips 
No, I do not agree, sorry :)

What in your mind means "Default value: 0" on the documentation? For me that means, if I do not define the value & parameter then CMDLet is using the default value, in this case "-skip 0".

You could also think about, how many queues you are expecting to get when you run:
`Get-CsCallQueue -WarningAction silentlycontinue -Skip 0 | ft name`


Have you tested this by your own? As I shared, it is very easy to create 200 queues.

**Comment by get-itips** [comment] 2020-03-17 19:50
@Petri-X Now we understand each other, I will propose changing the default value for the Skip parameter and together with the other already merged pr, I consider this complete.
Thanks for your feedback.

**Comment by yogkumgit** [comment] 2020-03-18 06:31
@get-itips  Thank you very much for the contribution and updating the documentation with PR. @Petri-X Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-03-18 06:31 UTC
