### ISSUE TITLE
Get-UserPhoto not available in ExchangeOnlineManagement 2.0.6

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/office-docs-powershell#9124] opened 2022-03-17 19:17 UTC
Hi,

It looks like ```Get-UserPhoto``` cmdlet became unavailable in the PowerShell module ```ExchangeOnlineManagement 2.0.6```
![image](https://user-images.githubusercontent.com/5260172/158878865-571dc20c-f666-4b87-b77c-41c154705da8.png)

However. it **does**  appear in ```ExchangeOnlineManagement 2.0.5```
![image](https://user-images.githubusercontent.com/5260172/158878680-6afee2d7-4187-449e-9a58-21128845b2cf.png)

Just wondering if you can get in touch with the concerned team regarding this issue?

Thanks in advance,
Yuriy

**Comment by chrisda** [comment] 2022-03-28 17:31
Closing as duplicate of #9123

**Closed by chrisda** 2022-03-28 17:31 UTC
Labels: duplicate, area:exchange
