### ISSUE TITLE
When creating multiple channels within a newly created team. The folders are not created in SharePoint Online

### ISSUE THREAD

**Issue by markgort86** [MicrosoftDocs/office-docs-powershell#4937] opened 2020-02-20 10:51 UTC
I've got a PowerShell script to create a new Microsoft Team. After this i create multiple channels with this PowerShell command. But after this process is completed there are no folders visible in SharePoint Online. They are created after opening the files tab within Microsoft Teams. Can someone explain me this behavior? Or is this a bug in the New-TeamChannel command-let? 

I can deliver the scripts i use to create a new team and some channels after the team is created. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd44b411-4b59-b90f-0b82-ad0a87652854
* Version Independent ID: 2c52cc4e-47a1-be0d-8860-1011adf061fd
* Content: [New-TeamChannel (teams)](https://docs.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps#feedback)
* Content Source: [teams/teams-ps/teams/New-TeamChannel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/teams-ps/teams/New-TeamChannel.md)
* Service: **teams-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by yogkumgit** [comment] 2020-02-20 12:11
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2020-02-22 13:15
Hello @markgort86 Mark, how are you? hope you are doing good. 👍 

As here we are limited to documentation changes, I tried to reproduce running New-TeamChannel to see if any change was needed to the article for that cmdlet, and I could not reproduce what you are describing, the folder was created right after I ran the cmdlet.
My recommendation is, be sure to run the latest stable version of the Teams PowerShell module and if it persists, open a support ticket directly on your tenant, they will be able to assist you in that case.

Thank you!

**Comment by yogkumgit** [comment] 2020-02-24 13:10
@get-itips  Thank you very much for the contribution and sharing this explanation. @markgort86 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by markgort86** [comment] 2020-02-25 08:07
@get-itips Thanks for you're explanation, first i check if i got the latest version of the PowerShell module. After that i try to reproduce my issue. If it still exist i raise a support ticket from my tenant.

**Closed** 2020-02-25 08:07 UTC
Labels: area:teams
