### ISSUE TITLE
TEAMS : D911

### ISSUE THREAD

**Issue by tommyjh** [MicrosoftDocs/office-docs-powershell#9770] opened 2022-08-08 05:24 UTC
The Teams powershell 2.6+ module until 4 seemed to have major issues with LIS database population.  Seems fixed.
But we have no way to actually validate information anymore....
test-csonlineliscivicaddress is no longer valid.
Anything we put in powershell shows 'validated' even though it isn't.
Places can't have their own lat/long.
This seems reckless as test calls to 911 fail on civic addresses even though they are 'validated'.
Anyone listening?
BTW even going thru the web interface some addresses fail to lookup.  You own BING and know lat/long on locations and still can't validate?
Please route this TEAMS wise - even your feedback site is routing to a general area.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2b13d68-e036-6d24-1d8b-68026ede5bd1
* Version Independent ID: d4d5c92d-cc9a-259e-ef82-d090330f5641
* Content: [Test-CsOnlineLisCivicAddress (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by get-itips** [comment] 2022-08-11 17:00
Hello @tommyjh 
How are you?
Here, we are limited to documentation/articles fixes and improvements (like missing parameters, adjust examples, typos and so on)
For your scenario the best would be to open a support request from your tenant.
Either way, I'll try to pass this feedback on.

**Comment by yogkumgit** [comment] 2022-08-12 12:33
@get-itips Thank you very much for the contribution and sharing this explanation. @tommyjh Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-08-12 12:33 UTC
Labels: area:teams / skype, support-request

**Comment by JensTrier** [comment] 2022-08-23 07:12
@tommyjh thanks for the feedback.

Yes, the entered address will display as Validated. The way and emergency call is routed based on the emergency address type is described here https://docs.microsoft.com/en-us/microsoftteams/emergency-calling-dispatchable-location#emergency-address-classification-and-routing

It is by design that a place inherits the lat/lon from the corresponding civic address. Think of this as the civic address being the building address and the place is a location within the same building/entrance, i.e. 3rd floor east.
