### ISSUE TITLE
Get-Team met httrequestException

### ISSUE THREAD

**Issue by xuegao0112** [MicrosoftDocs/office-docs-powershell#6691] opened 2020-10-15 16:29 UTC
Hi team,

I met this issue when I run the script below in Automation；

### **Error:**
10/15/2020 7:53:41 AM 	 Error 	 Get-Team : BadGateway in /teams/ endpoint
At line:9 char:13
+ $AllTeams = Get-Team -GroupID "xxx"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Team], HttpRequestException
    + FullyQualifiedErrorId : System.Net.Http.HttpRequestException,Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeam
 
**Script**:

$credentil = Get-AutomationPSCredential -Name "xxx"
Connect-MicrosoftTeams -Credential $credential
Write-Output "Started" 
$AllTeams = Get-Team -GroupID "cxxx"
Write-Output $AllTeams
Disconnect-MicrosoftTeams

And I have same script in another AA account and they all works well. 
And I foudn this issue:https://social.microsoft.com/Forums/SECURITY/en-US/e5aa0935-abc3-4897-a03e-c586287ac99b/powershell-badrequest?forum=msteams

Could you help fix it? Thanks.

**Comment by get-itips** [comment] 2020-10-22 13:05
Duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/6690

**Closed** 2020-10-27 13:31 UTC
Labels: area:teams
