### ISSUE TITLE
Removing more than one file

### ISSUE THREAD

**Issue by pierrecoach** [MicrosoftDocs/office-docs-powershell#2450] opened 2019-01-09 12:53 UTC
I came here to remove outdated files matching a pattern (testdata*.xlsx)
The examples are trivial and not enough
Let me suggest to add examples fitting a scenario, compbining commands, like
1) execute caml query to find
 outdated files (with a real date, not just 'your date here')
2) execute the remove on the CAML result

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c71852-b29d-30f8-e279-20c4dbb5e01f
* Version Independent ID: 78ced12f-e034-d3a5-0a49-a2bc3e4d0e50
* Content: [Remove-PnPFile (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpfile?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPFile.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nenonix** [comment] 2019-01-10 10:31
Thank you for the suggestion and for contributing to better documents. I will consult with my team and get back to you about the issues you raise.

**Comment by kenwith** [comment] 2019-01-14 19:19
@nenonix - these SharePoint Patterns and Practices (PnP) cmdlets are unique in that there is a vibrant community located over at  github.com/sharepoint  ..  the cmdlets are in this repo so that they are surfaced alongside the regular in-product cmdlets but that community at github.com/sharepoint is where PnP is located. For these PnP ones let's ask @VesaJuvonen what he recommends.. maybe @pierrecoach should post it to the github.com/sharepoint Issues list? Or @nenonix can post this issue there for you and then close this one?

Whatever we come up with let's incorporate it into the team Wiki that is helping handle all of the GitHub doc issues coming in...

**Comment by kenwith** [comment] 2019-01-14 19:19
Also, FYI @AndreaBarr

**Comment by yogkumgit** [comment] 2019-04-05 18:52
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2019-04-30 17:32
Hello @pierrecoach thanks for your feedback.
I tested in my lab based on your suggestion and I can confirm that Remove-PnpFile does not yet accept pipelined input (for example to use maybe Get-PnpFile, and this one, does not yet supports CAML queries)

As you may know, this issue resource is to report specifically issues in documentation, and I see, based on the description that you give, that might be more suitable for a feedback or user voice resource, as you may know also, Sharepoint PnP is community driven, I encourage you look here for that kind of resources https://docs.microsoft.com/en-us/sharepoint/dev/community/community

Hope this information helps you.

**Comment by yogkumgit** [comment] 2019-05-01 13:06
@get-itips  Thank you very much for the contribution and sharing this explanation. @pierrecoach 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment] 2019-05-01 13:06
@officedocsbot close

**Closed by yogkumgit** 2019-05-01 13:06 UTC
Labels: area:docs, area:pnp-powershell

**Comment by giveitaGo** [comment] 2019-11-06 17:36
@kenwith I visited the PnP Powershell project on GitHub, and the documentation page points back here.
https://github.com/SharePoint/PnP-PowerShell/tree/master/Documentation

Furthermore, as the OP said, the samples are very basic here and in the PnP community. Also, the documentation here doesn't mention what the -Force or -Recycle switches actually do.  I can play around and figure it out, but I'd rather be informed via good documentation. Thanks and Cheers!

**Comment by kenwith** [comment] 2019-11-06 17:53
@giveitaGo - sorry, I know the PnP documentation being here is very confusing. The PnP references work differently than the regular Office cmdlet references. The way the PnP references are set up is that the 'source of truth' for the documentation for them is inside of the code file for the cmdlet. For this one, it is here: https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Files/RemoveFile.cs

What the PnP community leaders do is that after a release they export the reference content from the PnP source code and then copy it over here. When they do that any changes that were merged here would be overwritten. 

I believe the original goal with this process was to surface the PnP cmdlet references here alongside the regular Office PowerShell references. But it has caused a lot of confusion because the 'source of truth' for the Office PowerShell references are here in GitHub but for PnP cmdlet's it is over in the cmdlet source code for each cmdlet.

**Comment by giveitaGo** [comment] 2019-11-06 18:45
Interesting and good to know. Thanks for the quick responses - super helpful.
