### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/office-docs-powershell#5688] opened 2020-05-25 01:11 UTC
(https://go.microsoft.com/fwlink/?LinkID=187810).
see the online documentation at https://go.microsoft.com/fwlink/p/?LinkId=251831 (https://go.microsoft.com/fwlink/p/?LinkId=251831).
Please fix these links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ac87fde-0d91-d0cc-6c9e-444917652bec
* Version Independent ID: 10d9bf8c-a1ab-1cfe-c831-127d9d924fd2
* Content: [Remove-SPODataConnectionSetting (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spodataconnectionsetting?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODataConnectionSetting.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODataConnectionSetting.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment] 2020-05-25 10:32
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2020-06-02 19:15
duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/5609

**Closed** 2020-06-03 11:04 UTC
Labels: area:spo-powershell
