### ISSUE TITLE
New-CsApplicationAccessPolicy returns 404

### ISSUE THREAD

**Issue by hoang-phan** [MicrosoftDocs/office-docs-powershell#8021] opened 2021-07-05 04:59 UTC
I am trying to use the Microsoft Graph API to create OnlineMeetings here
https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http

But when configuring application access policy as instructed here:

https://docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy

We got a 404 error:

```
New-CsApplicationAccessPolicy -Identity OnlineMeetings-Link -AppIds "xxx-xxx-xxx" -Description "xxxx Local"      

Get-CsOnlineSession: /Users/xxx/.local/share/powershell/Modules/MicrosoftTeams/2.3.1/netcoreapp3.1/SfBORemotePowershellModule.psm1:63

Line |
  63 |      $remoteSession = & (Get-CsOnlineSessionCommand)
     |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The remote server returned an error: (404) Not Found.

Invoke-Command: /Users/xxx/.local/share/powershell/Modules/MicrosoftTeams/2.3.1/netcoreapp3.1/SfBORemotePowershellModule.psm1:22959

 Line |
22959 |  …    -Session (Get-PSImplicitRemotingSession -CommandName 'New-CsApplic …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Cannot validate argument on parameter 'Session'. The argument
      | is null or empty. Provide an argument that is not null or
      | empty, and then try the command again.
```

I am an admin of the work/school account, and I have done all setup prerequisites:

https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install
https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell?view=o365-worldwide

I have all admin permissions to perform PowerShell cmdlet:

<img width="544" alt="Screen Shot 2021-07-05 at 6 49 56 AM" src="https://user-images.githubusercontent.com/7765168/124419763-5bc72280-dd88-11eb-8b68-eb39b883f981.png">

**Environment:**

```
PowerShell version: 7.1.3, installed with homebrew
MicrosoftTeams module version: 2.3.1
OS: Mac Mojave 10.14.6
```

I have no firewall, VPN/proxy enabled. The same issue happens when I tried it in the default PowerShell of Windows 10 VM on VirtualBox.

What should I do to get around this issue?

**Comment by get-itips** [comment] 2021-07-06 18:03
Hello @hoang-phan how are you?

Please be aware that, here we are limited to documentation issues and improvements. Said that, tried to reproduce in case we needed to adjust any documentation.

Please be aware that currently, the recommended version to run Teams PowerShell is 5.1

> Microsoft Teams PowerShell module is currently supported for use with PowerShell 5.1 on Windows.

Source https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install

So instead of opening PowerShell 7, you need to open Windows PowerShell (5.1) and also, have you run 

`Connect-MicrosoftTeams`

 before the New-CsApplicationAccessPolicy?

Hope this information helps you,

**Comment by hoang-phan** [comment] 2021-07-06 23:04
Hi @get-itips ,

I have also tried this on Windows 10 Virtual machine, which runs Windows PowerShell 5.1, and ran `Connect-MicrosoftTeams` successfully before doing the command. But this issue still happened.

Thanks for letting me know that I might have posted this to the wrong place. Would you please advise the repo I should post this issue to get the right support?

**Comment by get-itips** [comment] 2021-07-07 00:18
Hello @hoang-phan how are you?
I understand, as I could not reproduce, the best in this situation would be to open a support ticket from your tenant, they will be able to help you in your specific scenario.
Thank you

**Comment by yogkumgit** [comment] 2021-07-14 07:23
@get-itips Thank you very much for the contribution and sharing this explanation. @hoang-phan Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-07-14 07:23 UTC
Labels: area:teams / skype, support-request
