### ISSUE TITLE
Set-MailboxCalendarConfiguration | OnlineMeetingsByDefaultEnabled Attribute

### ISSUE THREAD

**Issue by Karthikeyan44** [MicrosoftDocs/office-docs-powershell#8761] opened 2022-01-06 14:03 UTC
[Hi Team, User level setting for OnlineMeetingsByDefaultEnabled attribute using the command "Set-MailboxCalendarConfiguration -Identity user1@contoso.com –OnlineMeetingsByDefaultEnabled $false/$true" is not taking effect. Though the command completes without any error but the setting is not taking effect for individual users. We had disable the OnlineMeetingsByDefaultEnabled attribute at org level ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9153892d-ff85-6117-7566-3ce55fff57c9
* Version Independent ID: 463efb5b-6bb0-97eb-bd51-f2e12cefc703
* Content: [Set-MailboxCalendarConfiguration (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxcalendarconfiguration?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Set-MailboxCalendarConfiguration.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-01-06 17:23
@Karthikeyan44, are you saying the current documentation is incorrect?

- OnlineMeetingsByDefaultEnabled in Set-MailboxCalendarConfiguration:

  Valid values are:

  - $true: All meetings are online by default.
  - $false: All meetings are not online by default.
  - $null: The value of the OnlineMeetingsByDefaultEnabled parameter on the Set-OrganizationConfig cmdlet (the organizational setting) is used.

- OnlineMeetingsByDefaultEnabled in Set-OrganizationConfig:

  Valid values are:

  - $true: All meetings are online by default.
  - $false: All meetings are not online by default.
  - $null: If the organization value has not been specified, the default behavior is for meetings to be online.

  You can override this setting on individual mailboxes by using the OnlineMeetingsByDefaultEnabled parameter on the Set-MailboxCalendarConfiguration cmdlet.

It might be the case where meetings must be online at the org level ($true or possibly $null), at which point you can disable online meetings at the individual mailbox level. It's unusual to be able to disable something at the org level, but then enable it at the individual level; it's usually the other way around.

**Comment by Karthikeyan44** [comment] 2022-01-06 17:26
Documentation is correct, but the individual mailbox setting to “$false” was not working. We tested with few mailboxes and waited around 24 hours but still by default Teams meeting was included in every calendar invite.

**Comment by chrisda** [comment] 2022-01-06 17:33
@Karthikeyan44, your best way forward is to open a support case to see if this is a bug or is by design. Report back here with the results.

**Comment by Karthikeyan44** [comment] 2022-01-06 17:38
Hi Chris, I did opened support case#28882165, they agreed this could be a bug for the new feature as per MC267584. Asked me to submit feedback.

**Comment by Karthikeyan44** [comment] 2022-01-06 18:09
Yup, I get it. Documentation is good, I am sure it’s a bug on command. I think there is confusion where to update feedback, as I see, this forum is for document, which is not an issue. I will follow up Microsoft contacts.

I apologize for the confusion here. Thanks Chris!

**Comment by yogkumgit** [comment] 2022-01-08 04:52
@Karthikeyan44 If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-01-08 04:52 UTC
Labels: area:exchange, doc-enhancement
