### ISSUE TITLE
cmdlets are not persisted when executed in sequence too quickly

### ISSUE THREAD

**Issue by ckarawani** [MicrosoftDocs/office-docs-powershell#9366] opened 2022-04-28 18:02 UTC
Hello, is there any documentation around what the delay should be when performing back to back cmdlets with TPM? 

We are noticing that when perform grant commands in sequence (say Granting different policies to a user). If we execute them too quickly in sequence, the changes are sometimes not persisted.

**Comment by pbafna03** [comment] 2022-04-29 05:52
Hi @ckarawani,

Would suggest raising a support request with details on the Teams PowerShell Module version used, Specific cmdlets & the user(s) this persistence issue happened with. Team can check and suggest accordingly.

**Comment by yogkumgit** [comment] 2022-04-29 09:41
@ckarawani Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ckarawani** [comment] 2022-04-29 10:42
@yogkumgit this behaviour is consistent across  multiple tenants and is been noticed since I can remember (since 2.3.1 at least). 

I think it needs to be documented if the cmdlets do not support chaining or should not be run sequentially without some form of delay.

**Comment by f0oster** [comment] 2022-05-01 13:18
> been noticed since I can remember (since 2.3.1 at least).

Just to point out, I have a noticed the same behaviour in my tenant.

**Comment by pbafna03** [comment] 2022-05-05 16:59
Hi @ckarawani & @f0oster, 

Can you please try this scenario now with the latest Teams PowerShell Version and confirm? There have been improvements recently on this. 

Also, this behavior is not expected with the latest versions, so if you still see any issues - would suggest raising a support request with the details around the tenant and the cmdlets used etc. for the team to check. 

@yogkumgit - No documentation changes for this are needed at this time. 

Regards,

**Comment by ckarawani** [comment] 2022-05-05 19:03
hey @pbafna03, are there specific resources I can send pwsh transcripts to?
365 Support has communicated multiple times to us that they do not support TPM for Pwsh and they can only really support uses cases revolving web administration via browser. 

From what I can tell, it's still present on the older commands that are still recycling the older Sfb commands such as the "Grant" commands for policies, but I can certainly put some time to confirm this.

**Comment by pbafna03** [comment] 2022-05-05 19:15
Hi @ckarawani ,

Grant commands for policies have also gone through modernization in the latest versions. 

If you still notice this with the latest versions, best is to report via Support only - https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide. Can reference that the issue is being faced with the Teams PowerShell Module latest version #, so that it reaches the relevant team.

**Closed** 2022-05-06 03:59 UTC
Labels: support-request

**Comment by ckarawani** [comment] 2022-05-18 02:33
hey @f0oster, just wanted to circle back on this. I cannot reproduce this problem anymore using latest TPM 4.3.0 as I
have successfully chained a bunch of Grant commands which were correctly persisted immediately.  Thank you @pbafna03 for the follow up on this and sorry it took a while to get back to you.

**Comment by f0oster** [comment] 2022-05-18 06:37
> hey @f0oster, just wanted to circle back on this. I cannot reproduce this problem anymore using latest TPM 4.3.0 as I have successfully chained a bunch of Grant commands which were correctly persisted immediately. Thank you @pbafna03 for the follow up on this and sorry it took a while to get back to you.

Thanks for the info. I'll be sure to test also.
