### ISSUE TITLE
Connect-IPPSSession: A parameter cannot be found that matches parameter name 'CertificateThumbprint'

### ISSUE THREAD

**Issue by ValeSayfa** [MicrosoftDocs/office-docs-powershell#9270] opened 2022-04-12 11:58 UTC
The following command is not working:
https://docs.microsoft.com/powershell/module/exchange/connect-ippssession

```powershell
Connect-IPPSSession -CertificateFilePath "/.../..../certificate.pfx" -CertificatePassword (ConvertTo-SecureString -String "....." -AsPlainText -Force) -AppID "......."  -Organization "..."                   
Connect-ExchangeOnline: A parameter cannot be found that matches parameter name 'CertificateThumbprint'.
```

I'm running powershell on linux (I have also tested it under Ubuntu):

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Linux 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The following modules are installed:

```
Get-InstalledModule  

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.3.0                PSWSMan                             PSGallery            Module to install and manage the forked WSMan client libraries for Linux and macOS.…
2.0.6-Preview5       ExchangeOnlineManagement            PSGallery            This is a Public Preview release of Exchange Online PowerShell V2 module.…
```

**Comment by chrisda** [comment] 2022-04-19 17:58
@ValeSayfa, the Connect-IPPSSession cmdlet is baked into the v2.0.6-Preview5 version of the module itself, and is definitely present, at least in Windows PowerShell v7.2.2.

Common parameters removed:

```powershell
PS C:\Users\chrisda> (Get-Command Connect-IPPSSession).parameters | FT Key

Key
---
AppId
AzureADAuthorizationEndpointUri
BypassMailboxAnchoring
Certificate
CertificateFilePath
CertificatePassword
CertificateThumbprint
CommandName
ConnectionUri
Credential
DelegatedOrganization
FormatTypeName
InformationAction
InformationVariable
Organization
Prefix
PSSessionOption
UserPrincipalName
```

Your best way forward is to send email to the EXO V2 Module support alias at: exocmdletpreview[at]service[dot]microsoft[dot]com.

Regular support channels won't be able to help because the module is still in Preview.

**Comment by yogkumgit** [comment] 2022-04-20 04:39
@ValeSayfa Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-04-20 04:39 UTC
Labels: area:exchange, support-request

**Comment by jkaluza-rapid7** [comment] 2022-06-30 11:55
Is there a workaround for that problem?

**Comment by chrisda** [comment] 2022-06-30 16:39
@jkaluza-rapid7, as described earlier in this issue, your best and only option until v2.0.6 goes public is to send email to the EXO V2 Module support alias at: exocmdletpreview[at]service[dot]microsoft[dot]com.

**Comment by rudesome** [comment] 2022-09-12 11:31
i can confirm since version: v2.0.6-Preview8 am able to connect to IPPSSession with certificate and appid on pwsh core.

There are only a few (new?) commands available, am hoping they soon add all the (old) commands.. for me especially the compliance search commands are essential.
