### ISSUE TITLE
Remove Skype for Business Server 2019 from all the 'Applies To" sub-header/section.

### ISSUE THREAD

**Issue by NeeranjanShettar** [MicrosoftDocs/office-docs-powershell#1924] opened 2018-10-19 18:40 UTC
The Persistent Chat role isn’t applicable for Skype for Business Server 2019 as it has deprecated. However, the articles still shows the several Persistent chat related cmdlets are applicable to Skype for Business Server 2019. This is incorrect, and the users will fall into confusion. Hence, I would suggest removing Skype for Business Server 2019 from the “Applies to” section or Add the Note within the articles saying as below.

Note : The Persistent chat in Skype for Business Server 2019 is deprecated and running this cmdlet will be applicable only to Lync Server 2013 / Skype for Business Server 2015 Persistent chat in the co-existence environment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6322fc9e-8974-bde3-20c7-19fc98040aa3
* Version Independent ID: b9234665-84a1-067c-29e4-d40c32c2a79a
* Content: [Remove-CsPersistentChatMessage (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/remove-cspersistentchatmessage?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Remove-CsPersistentChatMessage.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Remove-CsPersistentChatMessage.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment] 2018-10-19 18:57
@NeeranjanShettar  This is a duplicate of issue https://github.com/MicrosoftDocs/office-docs-powershell/issues/1920. I am closing this issue as a duplicate.

**Closed by AndreaBarr** 2018-10-19 18:57 UTC
