### ISSUE TITLE
Poor Help Docs

### ISSUE THREAD

**Issue by Nehru88** [MicrosoftDocs/office-docs-powershell#962] opened 2018-05-03 07:58 UTC
This Documentation is not helpful as in the old Documentation, Where we get the clear details on Input data .
Example "ObjectIds" stats its accepts a variety of objects, such as mailbox aliases, Send connector names, and so on, But clearly satating which all accepted. Not sure why Microsoft turned this way. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d36d45d-79cf-5ce9-0627-01bd4b8282c8
* Version Independent ID: 374a916d-f89d-99a3-c331-d9282c3825ed
* Content: [Search-AdminAuditLog (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/search-adminauditlog?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-AdminAuditLog.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/policy-and-compliance-audit/Search-AdminAuditLog.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by maxkoryukov** [comment] 2018-05-04 13:50
Unfortunately, I don't know what is _"The Old Documentation"_, but I can't find the **cmdlet reference** in the _new_ documentation.

**Comment by chrisda** [comment] 2018-05-07 17:25
@maxkoryukov, I think you're referring to the lack of manually maintained 'link farm' topics like "Exchange Online Cmdlets" or "Exchange 2016 Cmdlets"? There aren't topics like that on docs.microsoft.com because we're working on a way to filter the list of Exchange PowerShell related topics and cmdlet reference topics based on audience selection (Exchange 2010/2013/2016, Exchange Online, Office 365 Security & Compliance Center, or Exchange Online Protection). It's taking longer that we'd like, but it's definitely coming.

Thanks for the feedback.

**Comment by maxkoryukov** [comment] 2018-05-11 21:16
@chrisda, thank you for the answer! I don't want to be offensive, even knowing, that this is not a free open source project. And I too don't like comments with complaints. I want to apologize for my previous comment;)

And I hope you will publish such documentation soon!

**Comment by AndreaBarr** [comment] 2018-09-20 18:46
@Nehru88 Thank you for this feedback

It looks like Chris answered your questions. I am going to close this issue. If the issue is not resolved please reopen the issue.

**Closed by AndreaBarr** 2018-09-20 18:46 UTC
Labels: area:exchange
