### ISSUE TITLE
Not mentioned about maximum allowed filter parameters.

### ISSUE THREAD

**Issue by PrashanthReddy7** [MicrosoftDocs/office-docs-powershell#7471] opened 2021-03-22 10:21 UTC
Hi Team,

What is the limit for filter parameters ?
We are having issues with the filter parameter for Get-user, untill last week it was able to filter with 59 Guids.
Now we are getting the below attached error, about maximum limit.

What could be the maximum limit for Get-user filter with GUID?

![GetUser Filter Error](https://user-images.githubusercontent.com/63856494/111975230-a33ee100-8b00-11eb-81f5-b5ab8e539f00.JPG)

Get-User -resultsize unlimited -filter {ExternalDirectoryObjectId -eq 'd21c807e-dc28-42b5-9451-281628697592' -or ExternalDirectoryObjectId -eq '233d8fb8-4cf3-4111-9de9-67e4d6a09f65'}

**Comment by PrashanthReddy7** [comment] 2021-03-25 10:20
@yogkumgit Could you please let me know if any feedback.

**Comment by get-itips** [comment] 2021-03-31 20:07
Hello @PrashanthReddy7 how are you?
As here we are limited to documentation changes, I tried to reproduce to check if we needed to adjust [Get-User](https://docs.microsoft.com/en-us/powershell/module/exchange/get-user?view=exchange-ps) article, you did not specify if you are running the cmdlet against an Exchange Server or Exchange Online,  specifically against Exchange Online and Exchange Server 2019 I could not reproduce, I was able to specify more than 59 guids. 
Hope this information helps you.

**Comment by PrashanthReddy7** [comment] 2021-04-01 14:14
Hi @get-itips ,
I am good, thank you, Hope you are also doing good !!

I am having this issue in Exchange Online.
Even with 59 guids it was worked for me untill last week, now we are getting exceeds maximum allowed number limits,  then I have reduced it 40, then it worked.
So, there is no documentation, how the maximum limit can be calculated, characters or input parameters ?
I feel that, it’s not a static limit, its changing periodically.
If yes, could you please let me know how we can calculate the maximum input parameters

**Comment by get-itips** [comment] 2021-04-01 17:57
Hello @PrashanthReddy7 
Thanks for asking, doing good.
As I could not reproduce, the best thing in this scenario in my opinion would be to open a support ticket directly from your tenant, so your inquiry can reach the team behind the module and a support engineer can help in the matter to determine the limits.
Thank you

**Comment by yogkumgit** [comment] 2021-04-06 16:39
@get-itips Thank you very much for the contribution and sharing this explanation. @PrashanthReddy7 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-04-06 16:39 UTC

**Comment by chrisda** [comment] 2021-04-08 17:18
@dariomws for visibility.

**Comment by dariomws** [comment] 2021-04-09 06:59
Thank you @chrisda!
