### ISSUE TITLE
Disable-Mailbox -PermanentlyDisable doesn't seem match the documentation

### ISSUE THREAD

**Issue by chscott** [MicrosoftDocs/office-docs-powershell#5681] opened 2020-05-22 21:15 UTC
Steps:

1. Remove user's license
2. Run Disable-Mailbox -PermanentlyDisable
3. Add back user's license

My expectation is that, since -PermanentlyDisable was used, the user will get a new mailbox. Instead, the user gets the same mailbox that was "permanently" disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb358499-22a0-fa5c-c577-540de0049ddc
* Version Independent ID: 1c7960eb-3661-e96c-a9d7-18218256d6a1
* Content: [Disable-Mailbox (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/disable-mailbox?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Disable-Mailbox.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Disable-Mailbox.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment] 2020-05-25 10:31
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment] 2020-05-25 19:24
Hi @chscott, thank you for your feedback and help us to improve docs.microsoft.com.

I cannot reproduce this issue. If I remove the Exchange license (or all licenses) and then I try to run Disable-Mailbox I get:
![image](https://user-images.githubusercontent.com/33589238/82838233-eeb53e00-9ea1-11ea-83a0-5dd91fa13a67.png)

Looks like the mailbox is hard-deleted, not soft-deleted. There is more information about this behaviour here:
https://support.microsoft.com/help/3158794/no-soft-deleted-mailbox-after-license-removal-in-office-365
I think this parameter is useful when you are running a hybrid environment and you have a 30 days period grace to enable an Exchange license before the mailbox is deleted. In this case, if you need to remove the mailbox before the period grace, you can use this parameter to remove it permanently.

More information about mailbox recovery:
https://support.microsoft.com/help/20804/mailbox-recovery-in-exchange-online

**Comment by yogkumgit** [comment] 2020-05-26 10:50
@dariomws  Thank you very much for the contribution and sharing this explanation. @chscott 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-05-26 10:51 UTC
Labels: area:exchange
