### ISSUE TITLE
Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message

### ISSUE THREAD

**Issue by bijaykush** [MicrosoftDocs/office-docs-powershell#7813] opened 2021-05-21 14:49 UTC
I am using this command to connect Microsoft Teams through PowerShell 7.1.3 **OR** PowerShell  5.1.

Step 1
Connect to first domain (bijay@abc.com)
```
Import-Module MicrosoftTeams
$userCredential = Get-Credential
Connect-MicrosoftTeams -Credential $userCredential
```
Result: Connected Successfully:
![image](https://user-images.githubusercontent.com/11793622/119152839-65165d00-ba70-11eb-8b1f-66076095750f.png)

Step 2
Hit the command to get online application instance of the tenant:
`Get-CsOnlineApplicationInstance`

Result: Retrieved all the app instances successfully

Step 3
Connect to second domain (bijay@xyz.com) in the same PowerShell
```
Import-Module MicrosoftTeams
$userCredential = Get-Credential
Connect-MicrosoftTeams -Credential $userCredential
```
Result: Connected successfully

Step 4:
Hit the command to get the application instances again:
`Get-CsOnlineApplicationInstance`

Error Result: _Processing data from remote server api.interfaces.records.teams.microsoft.com failed with the following error message:_
![image](https://user-images.githubusercontent.com/11793622/119154168-a1968880-ba71-11eb-8a07-be7222b4860d.png)

Now in the above steps, if I use **Disconnect-MicrosoftTeams** command after step 2, I get the expected result.

I am doing all this through C# .Net and Asp.Net Core. SDK: **Microsoft.PowerShell.SDK**
Code Snippet

```
scriptContents.AppendLine("Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process");
            scriptContents.AppendLine($"$MicrosoftTeamsConnectorPath = Get-Item -Path {microsoftTeamsModulePath}");
            scriptContents.AppendLine("Import-Module $MicrosoftTeamsConnectorPath -verbose");
            scriptContents.AppendLine("Disconnect-MicrosoftTeams");
            scriptContents.AppendLine("$SecureStringPassword = ConvertTo-SecureString $Password -AsPlainText -Force");
            scriptContents.AppendLine("$Credential = New-Object System.Management.Automation.PSCredential -argumentlist 
            $UserName, $SecureStringPassword");
            scriptContents.AppendLine("Connect-MicrosoftTeams -Credential $Credential");
            
            using (PowerShell ps = PowerShell.Create())
            {
                    ps.AddScript(scriptContents.ToString());
                    ps.AddParameters(scriptParameters);

                    ps.Streams.Error.DataAdded += Error_DataAdded;
                    ps.Streams.Warning.DataAdded += Warning_DataAdded;
                    ps.Streams.Information.DataAdded += Information_DataAdded;

                    var pipelineObjects = await ps.InvokeAsync().ConfigureAwait(false);

                  if (ps.Streams.Error.Count > 0)
                    {
                        
                    }
                   else
                    {
                    }
           }
```
**Main Concern/Question:** 
When I run the application script locally, Steps 1 to 4 works fine by using Disconnect-MicrosoftTeams but it does not works when I host it on Azure App Service.
Error on Application Insight:
![image](https://user-images.githubusercontent.com/11793622/119154881-52048c80-ba72-11eb-8066-397c20634d99.png)

**What is the best way to remove the previous MicosoftTeams session (step 1 to 2) so that step 3 to 4 would work?
Is there anything I am missing while deploying it to Azure app service?**

**Note: I want the PowerShell to work for multiple domains with Microsoft Teams module commands like Get-CsOnlineApllicationInstance when hosted as a .NET core OR .NET framework web API on Azure App Service**

Any help would be appreciated?

**Comment by bijaykush** [comment] 2021-05-25 18:17
@yogkumgit Hi Do you have any update on this?

**Comment by bijaykush** [comment] 2021-05-25 18:29
Hi @DEberhardt
I saw that you have similar issue as posted on this issue [7058](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7058). You mentioned to cleanly closing existing sessions. And I think the issue I mentioned here is somewhat similar to yours.
Could you please have a look at this issue and let me know what is the way to cleanly close the existing sessions?

**Comment by jmcarthurcorr** [comment] 2021-05-27 17:54
I am getting this same error in PowerShell 5.1, using the Get-CSOnlineUser cmdlet from both normal and admin PS shells on Win10.

**Comment by DEberhardt** [comment] 2021-05-27 19:25
Hello,
yes, I had the same issue, but that was on v1.1.6 (or v1.1.10-preview) of the Module MicrosoftTeams.
I have no issues on v2.3.1 as the session is created with `Connect-MicrosoftTeams`.

If you haven't updated to v2.3.1 please do so :)

**Comment by jmcarthurcorr** [comment] 2021-05-27 20:13
I opened #7842 as I do have these issues on v2.3.1

**Comment by bijaykush** [comment] 2021-05-28 08:00
@DEberhardt 
I am using the latest MS Teams module i.e. 2.3.1 

Every things works perfectly when I run the code locally on VS 2019 with Disconnect-MicrososftTeams but it does not work when deployed in Azure App Service.
Seems like previous session of MS Teams is still not closed when sending next request for second tenant. And if I hit the request for first tenant, it works again.
Cross domain is not working when deployed with Disconnect Microsoft Teams.

**Comment by DEberhardt** [comment] 2021-05-29 13:25
Interesting.
I have not encountered an issue for this yet on 2.3.1.

Then again, I am using the Windows Terminal and open a new session for each Tenant I need to connect to - keeps it clean and separated as the session can now stay open for longer than an hour (thankfully :D)

I may be able to test this next week somewhen, but the volatility with the session is worrying...

**Comment by valpvt** [comment] 2021-06-03 14:05
Hello there,
Same issue with `Grant-CsTeamsVideoInteropServicePolicy -PolicyName BlueJeansServiceProviderEnabled -Identity $user.UserPrincipalName` 
I tried with MFA-enabled and non-MFA admin accounts without success.
`Get-CsUserPolicyAssignment -Identity $user.UserPrincipalName` works though... I don't get it

**Comment by DEberhardt** [comment] 2021-06-05 23:00
The issue is around the Session created in the background to the Teams API.
CmdLets using the old SkypeOnline interface will require a PsSession to be created (after using a command you can run `Get-PsSession` to see it has been created for you).
We seem to be tapping in a bug here with this session. I have written [`Assert-MicrosoftTeamsConnection`](https://github.com/DEberhardt/TeamsFunctions/blob/main/docs/Assert-MicrosoftTeamsConnection.md) to figure out whether the Session was correctly created.

Current Workaround:
Restart PowerShell session and connect from scratch.

**Comment by get-itips** [comment] 2021-06-07 13:31
Hello @bijaykush how are you? Hope you are doing good.
Here, we are limited to documentation issues, for your inquiry the best would be to open a support ticket directly from your tenant.
Similar issues had already been reported, please see [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7713#issuecomment-840566884) and [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7464#issuecomment-811248583)
Hope this information helps you,

**Comment by jmcarthurcorr** [comment] 2021-06-07 15:00
> 
> 
> The issue is around the Session created in the background to the Teams API.
> CmdLets using the old SkypeOnline interface will require a PsSession to be created (after using a command you can run `Get-PsSession` to see it has been created for you).
> We seem to be tapping in a bug here with this session. I have written [`Assert-MicrosoftTeamsConnection`](https://github.com/DEberhardt/TeamsFunctions/blob/main/docs/Assert-MicrosoftTeamsConnection.md) to figure out whether the Session was correctly created.
> 
> Current Workaround:
> Restart PowerShell session and connect from scratch.

I wish I had known about this module before I wrote my own tooling. Super userful @DEberhardt!

**Comment by kshah1999** [comment] 2021-06-07 15:48
@DEberhardt : Can you please provide some details on how you connect from scratch to PowerShell as you described as Current Workaround?

When I execute Get-PsSession, I get nothing and need to know how to create the session in this case to execute the script that was running before.

**Comment by bijaykush** [comment] 2021-06-08 03:40
> from

Thank you @DEberhardt for your suggestion. Does it mean that we need to restart the PowerShell and connect it from scratch programmatically when hosted in Azure App Service?
Because we are facing this issue only when hosted in Azure App service? Locally its working fine i.e. session is being refreshed easily.

**Comment by bijaykush** [comment] 2021-06-08 03:41
> The issue is around the Session created in the background to the Teams API.
> CmdLets using the old SkypeOnline interface will require a PsSession to be created (after using a command you can run `Get-PsSession` to see it has been created for you).
> We seem to be tapping in a bug here with this session. I have written [`Assert-MicrosoftTeamsConnection`](https://github.com/DEberhardt/TeamsFunctions/blob/main/docs/Assert-MicrosoftTeamsConnection.md) to figure out whether the Session was correctly created.
> 
> Current Workaround:
> Restart PowerShell session and connect from scratch.

Thank you @DEberhardt for your suggestion. Does it mean that we need to restart the PowerShell and connect it from scratch programmatically when hosted in Azure App Service?
Because we are facing this issue only when hosted in Azure App service? Locally its working fine i.e. session is being refreshed easily.

**Comment by DEberhardt** [comment] 2021-06-09 19:41
To elaborate, I am using a PowerShell window, ISE or the new Windows Terminal to create a session (`Connect-Me` if you fancy using TeamsFunctions :)) - I have to close the window to re-initialize the session when running into this issue.

That said, I have not had it myself since updating to MicrosoftTeams v2.3.1

It may also be influenced by the connection method. I myself always use the `-AccountId` when connecting.

**Comment by yogkumgit** [comment] 2021-06-10 10:44
@get-itips Thank you very much for the contribution and sharing this explanation. @bijaykush Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2021-06-10 10:45 UTC
Labels: area:teams, support-request
