### ISSUE TITLE
Descriptions of parameters are missing from document. Set-OWAMailboxPolicy.

### ISSUE THREAD

**Issue by jprknight** [MicrosoftDocs/office-docs-powershell#11108] opened 2023-07-26 19:10 UTC
The resource is missing multiple descriptions in https://learn.microsoft.com/powershell/module/exchange/set-owamailboxpolicy

{{ Fill AdditionalAccountsEnabled Description }}
{{ Fill AllowedOrganizationAccountDomains Description }}
{{ Fill BookingsMailboxDomain Description }}
{{ Fill ChangeSettingsAccountEnabled Description }}
{{ Fill ItemsToOtherAccountsEnabled Description }}
{{ Fill MessagePreviewsDisabled Description }}
{{ Fill ShowOnlineArchiveEnabled Description }}

These are seen instead of the actual data.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 022da80e-29cd-f6b5-aa00-48e2d16c4be8
* Version Independent ID: c3353c03-e416-f693-104f-6b6f5955b721
* Content: [Set-OwaMailboxPolicy (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2023-07-26 21:23
@jprknight, empty parameter descriptions are a known commodity. Availability of a parameter and functionality of that parameter are two different issues. A more detailed explanation of the problem is [here](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

So, can you comment officially on the availability and/or functionality of these parameters? Or are you simply reporting them as empty?

**Comment by jprknight** [comment] 2023-07-26 21:27
We were reporting them as unexpectedly empty. It looks to us that the data is missing.

**Comment by chrisda** [comment] 2023-07-26 21:34
@jprknight, as explained in that link, all I can verify is availability of the parameters. Whether it's supposed to be available or whether it works for customers (not DC Ops personnel) are different issues, I have no idea who to ask, and no one ever notified me about those new parameters or what they're for.

We should continue this discussion in email.

**Comment by yogkumgit** [comment] 2023-07-27 15:03
@jprknight Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2023-07-27 15:03 UTC
Labels: Microsoft submitter, Empty parameter description
