### ISSUE TITLE
Provide a product drop-down that contextually changes the documentaion

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/office-docs-powershell#1055] opened 2018-05-18 15:22 UTC
In the "Applies to" section it'd sure be nice to have a drop-down box at the top with a per-product choice, such as "Exchange Server 2010" or "Exchange Online" than changes the subsequent content that applies only to that product.

I know it's a big ask, but the current shotgun approach to just throwing up all of the documentation that MAY or MAY NOT apply to a certain product makes it a guessing game that get old really quickly.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f0166e-7855-9525-c93a-da83f82e48a8
* Version Independent ID: 1808c549-b2cf-cd24-559c-7ef30642b08a
* Content: [Add-DistributionGroupMember (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/add-distributiongroupmember?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/Add-DistributionGroupMember.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/Add-DistributionGroupMember.md)
* Service: **exchange-powershell**
* Product: **unspecified**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2018-05-18 16:34
@bingoglossy you've described exactly what we're planning to implement. It was part of the overall migration plan, to be lit up after the topics were on docs.microsoft.com. It's just taking a lot longer to make it work than we originally anticipated.

Thanks for the feedback.

**Comment by bingoglossy** [comment] 2018-05-18 16:43
Chris, thanks much! I already mentioned it to MS on a few PSS cases I've
had. I know it's a HUGE amount of work to get that granular, but it'll be
sweet when it's done.

**Comment by AndreaBarr** [comment] 2018-09-20 18:52
@bingoglossy Thank you for this feedback

It looks like Chris has addressed your request and answered your question. I am going to close this issue. If the issue is not resolved please reopen the issue.

**Closed by AndreaBarr** 2018-09-20 18:52 UTC
Labels: area:exchange
