### ISSUE TITLE
What is MTREnabled?

### ISSUE THREAD

**Issue by grahammw** [MicrosoftDocs/office-docs-powershell#9387] opened 2022-05-04 10:04 UTC
There is no information on this cmdlet as to what it does? Pleasef can you explain this in more detail about this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af332a3-efc1-49aa-24c2-64b5031a2420
* Version Independent ID: f47bc209-aa9e-f337-1cfa-b8a727a9f780
* Content: [Set-Place (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-place?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-Place.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-Place.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-05-04 17:44
Closing as duplicate of [9284](https://github.com/MicrosoftDocs/office-docs-powershell/issues/9284).

**Closed by chrisda** 2022-05-04 17:44 UTC
Labels: duplicate, area:exchange
