### ISSUE TITLE
Call Queue Greeting Message attribute

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#10227] opened 2022-12-08 21:40 UTC
I have a call queue in O365 that has a greeting message defined.  When I query the call queue with PowerShell, I do not see any attributes that contain this value (Albequerque greeting)

PS D:\Docs\PS\SFBO> $o=Get-CsCallQueue -Identity 896fd4e4-6d18-495a-964f-5771ddacba5d | Select *
WARNING: No Distribution Lists or Users added to callqueue. There will be no agents to call.
PS D:\Docs\PS\SFBO> $o

TenantId                                             : a5c32d43-5d6f-41a1-a3da-1390153869b6
Name                                                 : Albequerque
Identity                                             : 896fd4e4-6d18-495a-964f-5771ddacba5d
RoutingMethod                                        : LongestIdle
DistributionLists                                    : {}
Users                                                : {}
DistributionListsLastExpanded                        : 12/8/2022 8:12:57 PM +00:00
Agents                                               : {}
AllowOptOut                                          : True
ConferenceMode                                       : False
PresenceBasedRouting                                 : False
AgentsCapped                                         : False
AgentsInSyncWithDistributionLists                    : True
AgentAlertTime                                       : 20
LanguageId                                           : en-US
OverflowThreshold                                    : 34
OverflowAction                                       : DisconnectWithBusy
OverflowActionTarget                                 :
OverflowSharedVoicemailTextToSpeechPrompt            :
OverflowSharedVoicemailAudioFilePrompt               :
OverflowSharedVoicemailAudioFilePromptFileName       :
EnableOverflowSharedVoicemailTranscription           : False
EnableOverflowSharedVoicemailSystemPromptSuppression : False
TimeoutThreshold                                     : 1080
TimeoutAction                                        : Disconnect
TimeoutActionTarget                                  :
TimeoutSharedVoicemailTextToSpeechPrompt             :
TimeoutSharedVoicemailAudioFilePrompt                :
TimeoutSharedVoicemailAudioFilePromptFileName        :
EnableTimeoutSharedVoicemailTranscription            : False
EnableTimeoutSharedVoicemailSystemPromptSuppression  : False
WelcomeMusicFileName                                 :
UseDefaultMusicOnHold                                : True
MusicOnHoldFileName                                  :
Statistics                                           : {Current queue size = 0}
ApplicationInstances                                 : {}
ChannelId                                            :
OboResourceAccounts                                  : {}
AuthorizedUsers                                      : {}
ChannelUserObjectId                                  :
OboResourceAccountIds                                :
StatusRecords                                        : {}
Description                                          :
MusicOnHoldFileDownloadUri                           :
MusicOnHoldResourceId                                :
WelcomeMusicFileDownloadUri                          :
WelcomeMusicResourceId                               :
TimeoutActionTargetId                                :
TimeoutActionTargetType                              :
OverflowActionTargetId                               :
OverflowActionTargetType                             :

PS D:\Docs\PS\SFBO> $o.DistributionLists
PS D:\Docs\PS\SFBO> $o.Users
PS D:\Docs\PS\SFBO> $o.Agents
PS D:\Docs\PS\SFBO> $o.ApplicationInstances
PS D:\Docs\PS\SFBO> $o.OboResourceAccounts
PS D:\Docs\PS\SFBO> $o.AuthorizedUsers
PS D:\Docs\PS\SFBO> $o.StatusRecords
PS D:\Docs\PS\SFBO>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2523879-a846-25cf-c296-1f8b27b8c8dd
* Version Independent ID: 9a704476-5542-7035-b2fd-4463dbfa755f
* Content: [Get-CsCallQueue (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/get-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by shivtorov** [comment] 2022-12-12 08:54
the same as #10200

**Comment by get-itips** [comment] 2022-12-22 17:12
duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/10200

**Closed by get-itips** 2022-12-22 17:12 UTC
Labels: area:teams / skype
