### ISSUE TITLE
 -TelephoneNumber is an invalid parameter

### ISSUE THREAD

**Issue by sir-wally** [MicrosoftDocs/office-docs-powershell#4572] opened 2019-12-19 20:55 UTC
Set-CsOnlineApplicationInstance -Identity autoattendant@&lt;omitted&gt; -TelephoneNumber &lt;omitted&gt;
A parameter cannot be found that matches parameter name 'TelephoneNumber'.

    + CategoryInfo          : InvalidArgument: (:) [Set-CsOnlineApplicationInstance], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Rtc.Management.Hosted.PlatformService.ApplicationInstance.SetCsOn
   lineApplicationInstanceCmdlet
    + PSComputerName        : &lt;omitted&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afaf5510-5002-f560-8cd3-122839d7abad
* Version Independent ID: 0ed4badd-3a93-90a3-84e9-b2270eda84a5
* Content: [Set-CsOnlineVoiceApplicationInstance (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceapplicationinstance?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsOnlineVoiceApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineVoiceApplicationInstance.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @
* Microsoft Alias: **Danny Levin**

**Comment by yogkumgit** [comment] 2019-12-20 13:22
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2019-12-20 15:29
Hello @sir-wally 
Want to confirm with you that you followed all the steps outlined in [this guide](https://docs.microsoft.com/en-us/microsoftteams/manage-resource-accounts), specially acquiring service numbers and assigning a license

Thanks

**Comment by JubeeGankin** [comment] 2020-01-02 13:50
I have the same problem.  I have followed the steps in the linked guide but -telephonenumber is not a valid parameter.  The closest option is OnpremPhoneNumber but as my number isn't on prem, that doesn't seem like the right option.

**Comment by get-itips** [comment] 2020-01-03 20:38
Hello @tomkau can you shed some light here?
Thanks

**Comment by JubeeGankin** [comment] 2020-01-03 20:42
It actually has changed its behavior today.  -telephonenumber is now an option.  My issue has been resolved, maybe Wally's will be as well now?

**Comment by get-itips** [comment] 2020-01-03 20:44
> It actually has changed its behavior today. -telephonenumber is now an option. My issue has been resolved, maybe Wally's will be as well now?

Well, some settings in O365 have some delay to apply, so maybe it was that. Let's see if works for @sir-wally now. Thanks for your feedback @JubeeGankin

**Comment by yogkumgit** [comment] 2020-01-07 15:18
@tomkau Please reply to the query. Thanks.

**Comment by get-itips** [comment] 2020-04-15 12:08
> Set-CsOnlineApplicationInstance -Identity autoattendant@<omitted> -TelephoneNumber <omitted>
> A parameter cannot be found that matches parameter name 'TelephoneNumber'.
> 
> ```
> + CategoryInfo          : InvalidArgument: (:) [Set-CsOnlineApplicationInstance], ParameterBindingException
> + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Rtc.Management.Hosted.PlatformService.ApplicationInstance.SetCsOn
> ```
> 
> lineApplicationInstanceCmdlet
> + PSComputerName : <omitted>
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: afaf5510-5002-f560-8cd3-122839d7abad
> * Version Independent ID: 0ed4badd-3a93-90a3-84e9-b2270eda84a5
> * Content: [Set-CsOnlineVoiceApplicationInstance (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceapplicationinstance?view=skype-ps)
> * Content Source: [skype/skype-ps/skype/Set-CsOnlineVoiceApplicationInstance.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsOnlineVoiceApplicationInstance.md)
> * Service: **skypeforbusiness-powershell**
> * GitHub Login: @
> * Microsoft Alias: **Danny Levin**

Hello @sir-wally Reviewing old open issues I just realized that you ran Set-csOnlineApplicationInstance but the article you opened the issue is Set-CsOnlineVoiceApplicationInstance and that is the cmdlet I made the successful test.

Set-CsOnlineApplicationInstance **does not have** a TelephoneNumber parameter

**Comment by yogkumgit** [comment] 2020-04-16 11:09
@get-itips  Thank you very much for the contribution and sharing this explanation. @sir-wally 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-04-16 11:09 UTC
Labels: area:skype
