### ISSUE TITLE
Get-Sposite -limit all not returning all properties

### ISSUE THREAD

**Issue by waqas105** [MicrosoftDocs/office-docs-powershell#4510] opened 2019-12-05 20:53 UTC
Scenario: I am trying to get property of HubSiteID for each site collections. 
very strange issue with Get-SPO site

1st (this scenario is working as expected):
 $site = get-sposite -identity https://tenant url/sites/abc
$site.HubSiteId
- the above command return the guid of hub site id if above site associated with hub. But  00000000-0000-0000-0000-000000000000 if no association at all. 

But if ran the below example which is against all site collections then it will return 00000000-0000-0000-0000-000000000000 for all sites even for the sites which are associated with HUB.
$allsites = Get-SPOSite -Limit All
foreach($site in $allsites)
{
   $site.HubSiteId
}
am i doing something wrong or is their anything missing or bug?

**Comment by yogkumgit** [comment] 2019-12-06 07:59
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2019-12-09 11:22
Hello @waqas105 
Usually that is by design for performance matters.
You could use this as a workaround, it is slower, but it will show you the HubSiteId associated

```
$sitec= Get-SpoSite -limit ALL
foreach($s in $sitec){
	$site=get-sposite -Identity $s.Url
	$site.HubSiteId
}
```

**Comment by yogkumgit** [comment] 2019-12-09 12:52
@get-itips  Thank you very much for the contribution and sharing this explanation. @waqas105 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by waqas105** [comment] 2019-12-09 13:53
Thank you @yogkumgit and @get-itips for explanation. I already using the same workaround just need the clarification about this. yes it is very slow when I am processing 10K+ sites.

**Closed** 2019-12-09 14:00 UTC
Labels: area:spo-powershell
