### ISSUE TITLE
Teams cmdlets not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by gpriest-github** [MicrosoftDocs/office-docs-powershell#8066] opened 2021-07-16 14:49 UTC
```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.1971
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1971
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Desired Behaviour**

The command will complete as documented in the Cisco Documentation: 

https://www.cisco.com/c/en/us/td/docs/voice_ip_comm/cloudCollaboration/spark/hybridservices/calendarservice/cmgt_b_deploy-spark-hybrid-calendar-service/cmgt_b_deploy-spark-hybrid-calendar-service_chapter_0111.html

**Actual Behaviour** 

When running cmdlet's New-CsVideoInteropServiceProvider command I'm receiving the following error:

```
The term 'New-CsVideoInteropServiceProvider' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (New-CsVideoInteropServiceProvider:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : api.interfaces.records.teams.microsoft.com
```

**Investigation Completed**

The following Commands have been run

```
Install-Module MicrosoftTeams -AllowClobber -Force
Import-Module MicrosoftTeams
Get-Command -Module MicrosoftTeams

<snip>
Function        New-CsVideoInteropServiceProvider                  2.3.1      MicrosoftTeams
</snip>
```

What am I missing?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cad4e456-4179-ba17-94ba-dc25a334b27c
* Version Independent ID: 019ec793-3edb-056a-973d-32e0acb05ff3
* Content: [New-CsVideoInteropServiceProvider (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csvideointeropserviceprovider?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsVideoInteropServiceProvider.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsVideoInteropServiceProvider.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by gpriest-github** [comment] 2021-07-21 07:55
I've had no feedback on this I would like to know at least what the next steps are. I've already logged an MS Support case, who simply pointed me at this article.

**Comment by get-itips** [comment] 2021-07-23 13:47
Hello @gpriest-github how are you?
I tried to reproduce to see if we needed to adjust any documentation but I could not, both with GA and Public Preview versions.
My recommendations would be: be sure to be running only one version of the Teams Ps module (also check you have not still SfBOnline module installed)
Hope this information helps you.

**Comment by gpriest-github** [comment] 2021-07-23 14:02
I can confirm that the SkypeForBusiness module isn't installed. Are there any particular permissions required to run this module command - for example Global Admin?

```
get-module
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Binary     2.3.1      MicrosoftTeams                      {Add-TeamUser, Connect-MicrosoftTeams, Disconnect-Microsof...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...
```

**Comment by get-itips** [comment] 2021-07-23 14:17
@gpriest-github Will make some tests to try to confirm, but I could guess Teams Administrator as a minimum, what role are you assigned to? Thanks

**Comment by gpriest-github** [comment] 2021-07-23 14:20
This is the confusing thing. I have tried to do this in my test tenant and the command works successfully as Teams Admin, but in my production tenant as Teams Admin I receive the error. I've logged a call with MS Premier support and they are pushing me down the "Oh, it's because you're not a GA", which I don't believe because I have it working in the lab. I'm at an impasse with support until I reproduce this with a GA role assigned to my admin account. 

However, I'm curious if there is any logging on the command I can try and check. Is it trying to reach a different URL to complete.

**Comment by get-itips** [comment] 2021-07-23 16:25
@gpriest-github I made some tests, tried to use the cmdlet with a Teams Administrator but couldn't.

**Comment by gpriest-github** [comment] 2021-07-26 08:52
If this is a requirement of running the cmdlet, can the documentation for this be amended to include that GA permissions are required?

**Comment by get-itips** [comment] 2021-07-26 13:27
Hello @gpriest-github how are  you? Made further tests, and I could run the cmdlet if the user has both _Teams Administrator_ &
_Skype for Business Administrator_ roles assigned.

**Comment by gpriest-github** [comment] 2021-07-26 14:34
I can confirm that that works. What will be the situation as of next Monday when SkyforBusiness is no longer GA?

**Comment by yogkumgit** [comment] 2021-07-29 11:00
@get-itips

**Comment by DEberhardt** [comment] 2021-08-13 09:27
Piggy-backing on this thread to inquire whether we could clarify what the "Skype for Business Administrator" roles is now needed for (I am wondering for a while now whether I still need the role or not...).

Since moving the PowerShell commands to the MicrosoftTeams Module (and connection through `Connect-MicrosoftTeams`) I have not had use to activate this role for any commandlet.
This one may be one of the few which may need it? (Should they, shouldn't they?)

Maybe something for this [page](https://docs.microsoft.com/en-us/MicrosoftTeams/using-admin-roles)? (Funnily, it doesn't mention the Skype Role any longer...)

**Comment by get-itips** [comment] 2021-08-23 15:17
> I can confirm that that works. What will be the situation as of next Monday when SkyforBusiness is no longer GA?

I tested again, the behavior is the same I can confirm.

@yogkumgit you can close this thread now. thanks

**Comment by yogkumgit** [comment] 2021-08-24 08:52
@get-itips Thank you very much for the contribution and sharing this explanation. @gpriest-github Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2021-08-24 08:52 UTC
Labels: area:teams / skype, doc-enhancement
