### ISSUE TITLE
LdapFilter / Attributes Not Yet Supported

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#9498] opened 2022-06-01 20:35 UTC
I just downloaded version 4.4.1 of the MicrosoftTeams module and during testing, I notice I get an error when I attempt to use the LdapFilter parameter (knowing that Microsoft has plans on deprecating it).  I also notice if I execute

(Get-Command Get-CsOnlineUser).Parameters

LdapFilter shows up as a parameter

Is this a glitch or is this the start of the deprecation of this parameter?

Also, we truly need to use some kind of filtering capability and see that the OnPremHostingProvider and OnPremLineUri attributes show the value of Not Yet Supported and your documentation indicates these are temporarily unavailable in the output.  Any ETA on when these attributes will be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008ec10-a056-d8bb-bb4e-b4690a84adfd
* Version Independent ID: 2dcb78d9-7f36-208e-0989-184905d73011
* Content: [Get-CsOnlineUser (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Get-CsOnlineUser.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by sarollins** [comment] 2022-06-06 15:32
The OnPrem attributes are not fully supported yet.  If I pipe the results to a filter, they are not available, which makes no sense as the Get-CsOnlineUser will just be sending all the data as is and the Where clause shouldn’t be manipulating any data.

Get-CsOnlineUser | Where {$_.Identity -like '0*'} | Select Identity,OnPrem*


Identity                     : 06a7064b-0976-4edf-b7ca-f85b11cd85dc
OnPremEnterpriseVoiceEnabled :
OnPremHostingProvider        : Not Yet Supported.
OnPremLineUri                : Not Yet Supported.
OnPremOptionFlags            :
OnPremSIPEnabled             :
OnPremSipAddress             : Not Yet Supported.

But, if I use the -Identity filter, they are present

Get-CsOnlineUser -Identity '06a7064b-0976-4edf-b7ca-f85b11cd85dc' | Select Identity,OnPrem*


Identity                     : 06a7064b-0976-4edf-b7ca-f85b11cd85dc
OnPremEnterpriseVoiceEnabled : False
OnPremHostingProvider        :
OnPremLineUri                :
OnPremOptionFlags            :
OnPremSIPEnabled             : False
OnPremSipAddress             :

And, a call with no filtering of any kind also does not return these values

Get-CsOnlineUser | Select Identity,OnPrem*

Identity                     : 6f7f25af-cfa7-450c-8e4d-61d968fc20f5
OnPremEnterpriseVoiceEnabled :
OnPremHostingProvider        : Not Yet Supported.
OnPremLineUri                : Not Yet Supported.
OnPremOptionFlags            :
OnPremSIPEnabled             :
OnPremSipAddress             : Not Yet Supported.

This is still with 4.4.1 and after a login refresh

**Comment by get-itips** [comment] 2022-06-06 19:59
I understand that is the current behavior when filtering, correct me if I am wrong @isrumnon

**Comment by isrumnon** [comment] 2022-06-07 05:06
Hi @sarollins can you please share your tenant ID with me so I can check from my end whether your org is enabled for these attributes? my ID - isrumnon@microsoft.com
Hi @get-itips it was expected behavior but we've deployed a change to enable them 

Note: I will delete this post assuming you have received a mail for this comment due to privacy reasons (on sharing my mail ID)

**Comment by isrumnon** [comment] 2022-06-08 10:49
@yogkumgit I have responded to this in a separate thread. @sarollins let us know if we are good to close this ticket

**Comment by yogkumgit** [comment] 2022-10-20 12:03
@isrumnon Gentle reminder.

**Comment by sarollins** [comment] 2022-10-20 12:24
We still have clients seeing Not Yet Supported in the OnPremLineUri attribute.  Is this related to a specific version of the Teams module?

**Comment by isrumnon** [comment] 2022-10-21 13:17
@sarollins we display OnPremLineUri  for specific customers on a case by case basis. If required plz email me the target tenantID and we'll have it enabled. Either that or you can just raise a support ticket stating the requirement along with the target tenantID

**Comment by yogkumgit** [comment] 2022-10-24 03:23
@isrumnon Thank you very much for sharing this explanation. @sarollins Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-10-24 03:23 UTC
Labels: area:teams / skype, support-request
