### ISSUE TITLE
Depending on the PSSession the command `Get-AdminAuditLogConfig` returns different values

### ISSUE THREAD

**Issue by baartch** [MicrosoftDocs/office-docs-powershell#8933] opened 2022-02-09 06:41 UTC
I executed `Get-AdminAuditLogConfig` in a script, where I had two remote sessions opened, one with `Connect-ExchangeOnline` and the second with `Connect-IPPSSession`. These are both from the EXOv2 module. And both sessions provide this command, but they don't return the same values:

```powershell
PS C:\> Get-PSSession

 Id Name            Transport ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            --------- ------------    ------------    -----         -----------------     ------------
  1 ExchangeOnline… WSMan     outlook.office… RemoteMachine   Opened        Microsoft.Exchange       Available
  2 ExchangeOnline… WSMan     che01b.ps.comp… RemoteMachine   Opened        Microsoft.Exchange       Available

PS C:\> Invoke-command -Session $(Get-PSSession 1) -ScriptBlock {Get-AdminAuditLogConfig | select-object UnifiedAuditLogIngestionEnabled}

UnifiedAuditLogIngestionEnabled PSComputerName        RunspaceId
------------------------------- --------------        ----------
                           True outlook.office365.com ae9eb96d-1949-4396-8a49-8d6bb15f9e37

PS C:\> Invoke-command -Session $(Get-PSSession 2) -ScriptBlock {Get-AdminAuditLogConfig | select-object UnifiedAuditLogIngestionEnabled}

UnifiedAuditLogIngestionEnabled PSComputerName                              RunspaceId
------------------------------- --------------                              ----------
                          False che01b.ps.compliance.protection.outlook.com 03454c9b-f0e2-4c95-8798-504cdf710761
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12092dd4-4226-8d65-987a-14119277bc28
* Version Independent ID: 8cb30ac7-81f3-14d1-7d8a-142b06d647c4
* Content: [Get-AdminAuditLogConfig (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/get-adminauditlogconfig?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Get-AdminAuditLogConfig.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Get-AdminAuditLogConfig.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by baartch** [comment] 2022-02-09 08:27
Ok, now I see, when I compare the Distinguished Names that are returned, the object from `Connect-IPPSSession` is some default configuration. That's why this one is wrong...

```powershell
PS C:\> $(Invoke-command -Session (Get-PSSession 1) -ScriptBlock {Get-AdminAuditLogConfig | Select-Object DistinguishedName}).DistinguishedName
CN=Admin Audit Log Settings,CN=Global Settings,CN=Configuration,CN=mytenant.onmicrosoft.com,CN=ConfigurationUnits,DC=CHEP278A001,DC=PROD,DC=OUTLOOK,DC=COM

PS C:\> $(Invoke-command -Session (Get-PSSession 2) -ScriptBlock {Get-AdminAuditLogConfig | Select-Object DistinguishedName}).DistinguishedName
CN=Default,CN=Configuration,CN=mytenant.onmicrosoft.com,OU=Microsoft Exchange Hosted Organizations,DC=FFO,DC=extest,DC=microsoft,DC=com

```

**Comment by chrisda** [comment] 2022-02-19 00:09
@baartch, so are we OK to close this issue?

**Comment by yogkumgit** [comment] 2022-02-20 12:39
@baartch If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by baartch** [comment] 2022-02-21 06:13
> @baartch, so are we OK to close this issue?

To me, this seems to be a bug in the session opened with `Connect-IPPSSession`. As I have no clue, how to submit this to the ones who develop this, I opened a issue here. I thought that maybe you guys can handle this.
I know now how to deal with this, but I'm quiet sure others will face this issue too. If this settles it for you, then so be it.

**Comment by chrisda** [comment] 2022-03-04 19:13
@baartch, after looking closely at this, I would say the behavior that you're describing is expected. The Exchange Online PowerShell and Security & Compliance Center PowerShell environments are fundamentally different: different endpoints to connect, located in different AD forests in the datacenters, no mailbox objects available at all in SCC PowerShell, etc. You're welcome to open a support case about this, but they'll likely resolve it as 'By Design'.

Thanks for the feedback.

Closing

**Closed by chrisda** 2022-03-04 19:13 UTC
Labels: area:exchange, doc-enhancement
