### ISSUE TITLE
Set-CsUser not working in Microsofteams PowerShell Module Version 2.3.0

### ISSUE THREAD

**Issue by Philipp-Zumdohme** [MicrosoftDocs/office-docs-powershell#7706] opened 2021-05-03 13:31 UTC
Hello,

today I wanted to use the updated module to enable the enterprise voice features for new colleagues.
When I am trying to use the commands:

Import-Module MicrosoftTeams
Connect-MicrosoftTeams
Set-CsUser -Identity $upn -EnterpriseVoiceEnabled $true -HostedVoiceMailbox $true

It is not working:
It does not accept the parameter "-Identity".
When I use autocomplete it only tells me there is a parameter "-Id" and not "-Identity".
If I try to use "-Id" with the the other Parameters, it does not accept "$true".
If I try to use the command without "$true", I get an "Access Denied" error.

I tried this from several machines.
Could reproduce the error on all.
Removing the MicrosoftTeams Module Version 2.3.0 and installing 2.0.0 "resolves" the issue.

**Comment by lansalot** [comment] 2021-05-04 16:35
Same here - access denied. The grief we're having trying to do what should be a simple thing, it's just unreal. Tried different versions, tried to find a working New-CSOnlineSession, nothing appears to be as it should.

You'd think you could just download the module, Connect-MicrosoftTeams and change it. Nope !

**Comment by boerspeter** [comment] 2021-05-05 05:26
came here to tell this, had to revert to 2.0.0 because we're not able to enable Enterprise Voice for Teams users in latest release

**Comment by VRADDB** [comment] 2021-05-05 06:04
Same issue, install-MicrosoftTeams installs version 2.3.0 by default there are no release notes of this version as of yes.
Set-CsUser cmdlet (and maybe others) are not working properly or documentation is missing if the parameters have changed.

Uninstalling this version and installing v2.0.0 did work for me.

**Comment by FooBarr1868** [comment] 2021-05-05 07:41
Same issue exactly as described by OP and resolved by the same method. Thanks.

**Comment by ruudvanstrijp** [comment] 2021-05-05 11:09
I have the same issue since upgrading from 1.1.6 to 2.3 this morning. The new Set-CsUser command somehow has '-id' instead of '-identity', and it has no access to my Teams tenant: "Set-CsUser : Access Denied.".

I have installed a new VM, where I did the following tests:
- Set-CsUser in Powershell: Command not found
- Install-Module -Name MicrosoftTeams -Force -Scope AllUsers
- Set-CsUser is now found, but only has -id as parameter, and not -identity. When I try to run it, it tells me I need to connect to MS Teams first using Connect-Microsoft Teams (which is to be expected)
- Connect-MicrosoftTeams
- Set-CsUser -id 'firstname.lastname@domain.com' Response:  "Set-CsUser : Access Denied."

If this is the case, this would be a major bug in the new 2.3 module.

**Comment by get-itips** [comment] 2021-05-13 13:27
Hello everyone here
I can confirm that version 2.3.1 of the Teams PowerShell module reverts back to `-Identity` in `Set-CsUser` as the current documentation for the article details.
Hope this information helps you.

**Comment by yogkumgit** [comment] 2021-05-14 12:28
@get-itips Thank you very much for the contribution and sharing this explanation. @Philipp-Zumdohme Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-05-14 12:28 UTC
Labels: area:teams
