### ISSUE TITLE
Teams 4.3.1 Get-CSOnlineUser incorrect InterpretedUserType

### ISSUE THREAD

**Issue by paulsysadmin** [MicrosoftDocs/office-docs-powershell#9453] opened 2022-05-20 07:40 UTC
Checking the user on older versions of the Teams Module produces AADConnectEnabledOnlineTeamsOnlyUser

Same user on 4.3.1 now showing as DirSyncEnabledOnlineTeamsOnlyUser

**Comment by isrumnon** [comment] 2022-05-20 10:31
@paulsysadmin I'll get back to you on this by Monday eod

**Comment by isrumnon** [comment] 2022-05-30 18:29
Hi @paulsysadmin the pre-fix "AADConnectEnabledOnline" in the IUT value has now been renamed to "DirSyncEnabledOnline"
We're updating documentation to reflect the same

**Comment by paulsysadmin** [comment] 2022-05-31 06:36
Thanks @isrumnon . Did I miss something ?  I thought DirSync was deprecated and long since replaced by AADConnect ?

**Comment by yogkumgit** [comment] 2022-05-31 08:38
@isrumnon

**Comment by isrumnon** [comment] 2022-06-06 11:37
Hi @paulsysadmin DirSync is deprecated only for TeamsOnly organizations but still remains for Tenants that are Hybrid (have an OpPremise deployment)

**Comment by paulsysadmin** [comment] 2022-06-06 17:22
Hi @isrumnon I am aware of that as we are still a hybrid and we use AAD Connect to synchronise objects to Azure. My question is why in all previous versions of the module are the InterpretedUserTypes using AADConnect and now in 4.3.1 they have been switched to DirSync ? 

Dirsync was replaced by AADConnect several years ago. Am I missing something ?

**Comment by yogkumgit** [comment] 2022-06-14 08:46
@isrumnon

**Comment by yogkumgit** [comment] 2022-07-11 04:58
@isrumnon Please comment. Thanks

**Comment by shivtorov** [comment] 2022-07-11 05:21
@isrumnon, do you know if any work is in progress to fix incorrect InterpretedUserType values reported by Get-CsOnlineUser, when it is used *without* `-Identity` parameters. It is broken since v.3.x.x

Taking into account that v.2.6.0 stopped connecting to our tenants mid June, we have no viable means to use this very useful `InterpretedUserType` value. (Querying `Get-CsOnlineUser` one-by-one is not an option when dealing with tenants containing even just a few thousand users)

**Comment by isrumnon** [comment] 2022-07-11 11:41
Hi @paulsysadmin apologies for the delayed response, Dirsync was replaced by AADConnect a while back but still applies for organizations with an On-Prem presence. For the sudden change for your specific tenant - we'll need to look into it. Will contact you separately regarding the same.

@shivtorov For InterpretedUserType values in the output of Get-CsOnlineUser when it is used without -Identity vs when it is used with -Identity we're currently looking into it and investigating whether it is limited to a few organizations or widespread. Will updated this thread on findings

**Comment by isrumnon** [comment] 2022-07-11 11:41
@paulsysadmin regarding above issue, please reach out to me on isrumnon@microsoft.com. Deleting this post for privacy reasons.

**Comment by shivtorov** [comment] 2022-07-11 12:50
Thanks @isrumnon
I worked with several tenants in the last couple of months. The issue is consistent in all of them. 

The most visible case for me is the users still homed in on-premises SFBS - for them `Get-CsOnlineUser` without `-Identity` always incorrectly report `InterpretedUserType ` = `HybridOnline*` (e.g. `HybridOnlineSfBUserWithTeamsLicense`) instead of `HybridOnpremSfBUserWithTeamsLicense`

**Comment by yogkumgit** [comment] 2022-07-25 05:11
@isrumnon Please comment.

**Comment by isrumnon** [comment] 2022-07-25 18:12
@yogkumgit am working with both customers offline to resolve

**Comment by zaichornik** [comment] 2022-08-01 09:00
Hi @isrumnon,

Are you planning to support again the filtering by _whenCreated_ Azure AD attribute as part of_Get-CsOnlineUser_ command (for human - based accounts)?

Thanks.

**Comment by yogkumgit** [comment] 2022-08-16 08:25
@isrumnon Please comment and advise for closure. Thanks

**Comment by yogkumgit** [comment] 2022-08-30 07:20
@isrumnon as you are working offline on this, can we clear it from here. Kindly guide us or close it if suitable. Thanks

**Comment by isrumnon** [comment] 2022-08-31 07:40
Hi @zaichornik we are not going to add WhenCreated but we will expose WhenChanged but even for this we are not going to expose this property for everyone but you can raise a support ticket to get it enabled for your tenant

**Comment by isrumnon** [comment] 2022-08-31 07:42
@yogkumgit we can close this ticket if there are no further questions

**Closed** 2022-08-31 11:25 UTC
Labels: area:teams
