### ISSUE TITLE
[Set-CsAutoAttendant] A parameter cannot be found that matches parameter name 'ForceListenMenuEnabled'. (DefaultCallFlow.ForceListenMenuEnabled)

### ISSUE THREAD

**Issue by RPE-PeterD** [MicrosoftDocs/office-docs-powershell#11100] opened 2023-07-22 12:48 UTC
I was receiving this error when attempting to add a Holiday to an existing AutoAttendant, but was able to work around it.

```
$currentSchedule = New-CsOnlineSchedule -Name $currentHolidayNameIDShort -FixedSchedule -DateTimeRanges @($currentDateRangeOutputArray);
$currentCallHandlingAssociation = New-CsAutoAttendantCallHandlingAssociation -Type Holiday -ScheduleId $currentSchedule.Id -CallFlowId $currentCallFlow.Id

$currentAutoAttendantID = $testAutoAttendantID;
$currentAutoAttendantHolidays = Get-CsAutoAttendantHolidays -Identity $currentAutoAttendantID
$currentAutoAttendant = Get-CsAutoAttendant -Identity $currentAutoAttendantID
$currentAutoAttendant.CallFlows += @($currentCallFlow)
$currentAutoAttendant.CallHandlingAssociations += @($currentCallHandlingAssociation)
Set-CsAutoAttendant -Instance $currentAutoAttendant
```

```
Set-CsAutoAttendant : A parameter cannot be found that matches parameter name 'ForceListenMenuEnabled'.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\5.4.0\custom\Merged_custom_PsExt.ps1:8472 char:94
+ ... igAPI.Cmdlets.internal\Set-CsAutoAttendant @PSBoundParameters @httpPi ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-CsAutoAttendant], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-CsAutoAttendant
```

Turns out turning off 'Force Listen' in the Teams AA Default Greeting allows the above to process without error.

![ForceListen_Teams-AA](https://github.com/MicrosoftDocs/office-docs-powershell/assets/60473273/8f9626ca-5c31-4267-ba4c-26d3ea1a8880)

This is where the param in the cmdlet is referenced

C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\5.4.0\custom\Merged_custom_PsExt.ps1:8374
```
if ($Instance.DefaultCallFlow.ForceListenMenuEnabled -eq $true) {
    $PSBoundParameters.Add('ForceListenMenuEnabled', $true)
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8aedf07e-205e-ebe8-6351-1c1956f99b85
* Version Independent ID: c18defb2-97e8-1196-dc32-47260dad5c09
* Content: [Set-CsAutoAttendant (SkypeForBusiness)](https://learn.microsoft.com/en-us/powershell/module/skype/set-csautoattendant?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsAutoAttendant.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsAutoAttendant.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by get-itips** [comment] 2023-07-26 17:00
Hello @RPE-PeterD 

ForceListenMenuEnabled is a property of CallFlows (CsAutoAttendantCallFlow), it is a switch parameter, how are you setting it in $currentCallFlow?

To understand if we need to update any article, thanks

**Comment by RPE-PeterD** [comment] 2023-07-28 20:42
```
$currentCallFlow = New-CsAutoAttendantCallFlow -Name $currentHolidayNameIDShort -Greetings @($currentPrompt) -Menu $currentMenu #-ForceListenMenuEnabled;
```

I have it omitted

Turning it back on will work for the particular Auto-Attendant after having disabled 'Force Listen' for that AA.

So the switch param works on AA's with 'Force Listen' -eq $FALSE 
```
$currentAutoAttendant.DefaultCallFlow.ForceListenMenuEnabled
```
If the above resolved to True, then I wasn't ever able to modify CallFlows with or without setting the switch param ForceListenMenuEnabled

**Comment by get-itips** [comment] 2023-07-28 21:40
Thanks for adding more details.
Can you still reproduce that? I could not reproduce it yet to see if we need to adjust the article.

**Comment by RPE-PeterD** [comment] 2023-07-29 13:20
Yep, am able to reproduce it on multiple AutoAttendants.

I've tested with ForceListenMenuEnabled enabled and disabled in CallFlows (all True ; some True) with ForceListenMenuEnabled enabled and disabled in DefaultCallFlow. 

 Has only occurred when **Microsoft.Rtc.Management.Hosted.OAA.Models.AutoAttendant.DefaultCallFlow.ForceListenMenuEnabled** is True.

```
   TypeName: Microsoft.Rtc.Management.Hosted.OAA.Models.AutoAttendant

Name                     MemberType Definition
----                     ---------- ----------
CallFlows                Property   Microsoft.Rtc.Management.Hosted.OAA.Models.CallFlow[] CallFlows {get;set;}
DefaultCallFlow          Property   Microsoft.Rtc.Management.Hosted.OAA.Models.CallFlow DefaultCallFlow {get;set;}
```
Both CallFlows & DefaultCallFlow have the ForceListenMenuEnabled property.
```
   TypeName: Microsoft.Rtc.Management.Hosted.OAA.Models.CallFlow

Name                      MemberType Definition
----                      ---------- ----------
ForceListenMenuEnabled    Property   bool ForceListenMenuEnabled {get;set;}
```

**Comment by yogkumgit** [comment] 2023-07-31 11:41
@get-itips

**Comment by RPE-PeterD** [comment] 2023-07-31 16:52
I've done a little more testing on how to set the DefaultCallFlow's value, depending on it's ForceListenMenuEnabled value.

> In the Teams Admin (https://admin.teams.microsoft.com/auto-attendants/v2/<aa_id>) set Call Flow - Force Listen (DefaultCallFlow.ForceListenMenuEnabled) to be FALSE to capture result, then TRUE to capture result
>```
>$aaFalse = Get-CsAutoAttendant -Identity $aaID;
>```
>```
>$aaTrue  = Get-CsAutoAttendant -Identity $aaID;
>```

Current state of the Auto-Attendant in question : DefaultCallFlow.ForceListenMenuEnabled is TRUE

>```
>Set-CsAutoAttendant -Instance $aaFalse
>```
>Attempting to set DefaultCallFlow.ForceListenMenuEnabled to FALSE : Success

Current state of the Auto-Attendant in question : DefaultCallFlow.ForceListenMenuEnabled is FALSE


>```
>Set-CsAutoAttendant -Instance $aaTrue
>Set-CsAutoAttendant : A parameter cannot be found that matches parameter name 'ForceListenMenuEnabled'.
>At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\5.4.0\custom\Merged_custom_PsExt.ps1:8472 char:94
>+ ... igAPI.Cmdlets.internal\Set-CsAutoAttendant @PSBoundParameters @httpPi ...
>+                                                ~~~~~~~~~~~~~~~~~~
>   + CategoryInfo          : InvalidArgument: (:) [Set-CsAutoAttendant], ParentContainsErrorRecordException
>    + FullyQualifiedErrorId : NamedParameterNotFound,Set-CsAutoAttendant
>```
>Attempting to set DefaultCallFlow.ForceListenMenuEnabled to TRUE : FAIL

---

Tried a couple other things like using New-CsAutoAttendantCallFlow but that also didn't work (when attempting to elevate the DefaultCallFlow.ForceListenMenuEnabled from FALSE to TRUE

These appear to fail on my end
>https://learn.microsoft.com/en-us/powershell/module/skype/new-csautoattendantcallflow?view=skype-psexamples

**Comment by get-itips** [comment] 2023-07-31 16:53
Thanks for providing more information, I'm checking internally

**Comment by yogkumgit** [comment] 2023-08-11 12:36
@get-itips Please update.

**Comment by get-itips** [comment] 2023-08-11 13:52
@yogkumgit Still waiting on an update internally.

**Comment by get-itips** [comment] 2023-08-29 17:08
@yogkumgit Still waiting on an update internally...

**Comment by vdevenr** [comment] 2023-09-18 12:33
Any update on this issue ?

**Comment by yogkumgit** [comment] 2023-10-20 13:06
@tiburd Please help. Thanks

**Comment by JensTrier** [comment] 2023-11-16 13:50
I tested this today and it works now.

`PS 2023-11-16 13:47:16Z C:\> $aa=Get-CsAutoAttendant -Identity 5e4fee32-2c0d-4dd0-bd3c-454bba817a6e
PS 2023-11-16 13:47:20Z C:\> $aa.DefaultCallFlow

Id                     : 9a5e5426-1dda-4015-8f95-9d0f84d9cab2
Name                   : AA 1 Default call flow
Greetings              : TextToSpeechPrompt=Welcome to SfB Lab Denmark
Menu                   : Business hours call flow
ForceListenMenuEnabled : False


PS 2023-11-16 13:47:27Z C:\> $aa.DefaultCallFlow.ForceListenMenuEnabled = $true
PS 2023-11-16 13:47:35Z C:\> set-CsAutoAttendant -Instance $aa

Identity                 : 5e4fee32-2c0d-4dd0-bd3c-454bba817a6e
TenantId                 : bc2632e3-750c-47d7-aeae-9fee035bc0c7
Name                     : AA 1
LanguageId               : en-US
VoiceId                  : Female
DefaultCallFlow          : AA 1 Default call flow
Operator                 : ID=bf9d94bc-6cb4-4d33-bac8-ebd5e14c8ad3, Type=User
TimeZoneId               : Romance Standard Time
VoiceResponseEnabled     : True
CallFlows                : AA 1 After hours call flow, Holiday 1, Winter Vacation
Schedules                : After hours AA 1, Holiday1, Holiday2
CallHandlingAssociations : AfterHours(1), Holiday(2)
Status                   : Successful
DialByNameResourceId     : 86d665cc-03f4-4e22-9707-2d2351b3fe73
DirectoryLookupScope     :
ApplicationInstances     : {a3c1a8e0-84f6-46af-847d-a2e5e896e1b1, 35052022-48d5-4a92-b743-45cbcbb5b7d5,
                           1f371810-2435-4b94-b19d-9b8811162220, 8630baad-c821-4e0e-96e4-fd40afcab9bc…}
AuthorizedUsers          : {c637742d-1c12-4632-bdca-15c4f57978a6, bf9d94bc-6cb4-4d33-bac8-ebd5e14c8ad3}
HideAuthorizedUsers      : {}


PS 2023-11-16 13:47:46Z C:\> (Get-CsAutoAttendant -Identity 5e4fee32-2c0d-4dd0-bd3c-454bba817a6e).DefaultCallFlow

Id                     : 9a5e5426-1dda-4015-8f95-9d0f84d9cab2
Name                   : AA 1 Default call flow
Greetings              : TextToSpeechPrompt=Welcome to SfB Lab Denmark
Menu                   : Business hours call flow
ForceListenMenuEnabled : True


PS 2023-11-16 13:48:14Z C:\>`

**Comment by yogkumgit** [comment] 2023-11-17 12:02
@JensTrier Thank you very much for sharing this information. @RPE-PeterD Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2023-11-17 12:02 UTC
Labels: area:teams / skype, writer-input-required
