### ISSUE TITLE
Grant-CsTenantDialPlan fails with UPN

### ISSUE THREAD

**Issue by Briggidy** [MicrosoftDocs/office-docs-powershell#9082] opened 2022-03-10 16:19 UTC
### Unable to apply Dial Plan to users using UPN.

Using the following cmdlet:
<code>
Grant-CsTenantDialPlan -PolicyName US -Identity first.last@contoso.com
</code>

**Error:**

<code>Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPolicy : User does not exist</code>
<code> At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.1.1\net472\custom\PsExt\Grant-CsUserOrTenantPolicy.ps1:61 char:13</code>
<code>+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPo ...</code>
<code>+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</code>
<code>    + CategoryInfo          : InvalidOperation: ({ Identity = 0b...ntUserRequest }:<>f__AnonymousType56`3) [Grant-CsUserPolicy_GrantExpanded], Exception</code>
<code>    + FullyQualifiedErrorId : ClientError,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GrantCsUserPolicy_GrantExpanded
</code>

<p>

**Versions Tried:**

- 4.0.0 - fail with similar error above
- 3.1.1 - fail
- 3.1.0 - fail with similar error above
- 3.0.0 - fail with similar error above
- 2.6.0 - cmdlet works as expected
</p>

**Workaround 1**

<code>Grant-CsTenantDialPlan -PolicyName US -Identity ObjectID</code>

**Workaround 2**

<code>Get-CsOnlineUser -Identity first.last@contoso.com| Grant-CsTenantDialPlan -PolicyName US</code>

**Comment by olanga** [comment] 2022-03-10 19:08
We have the same issue since last Saturday.  We have been  using 3.1.1 for weeks without issue. 
Unfortunately none of your workarounds works for me. 
1- "User does not exist" 2. "Grant-CsTenantDialPlan : One or more errors occurred"

Here is the answer we have got from Microsoft:
"Assessment/Analysis:
This scenario matches a known issue related to version 3.1.1 that we are currently investigating. The workaround is to downgrade Teams Module version 2.6.0 which you have just tested and confirmed that it's working.
As for the ETA, we expect the issue to be fixed by the end of this quarter. "

**Comment by Briggidy** [comment] 2022-03-11 16:56
@olanga  sorry the workarounds don't help.  Thanks for the info.  Seems like a lot of issues lately with Teams modules.

**Comment by yogkumgit** [comment] 2022-03-12 03:49
@olanga Thank you very much for the contribution and sharing this explanation. @Briggidy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2022-03-12 03:49 UTC
Labels: area:teams, doc-enhancement
