### ISSUE TITLE
-Settings parameter not reserved for Microsoft

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/office-docs-powershell#9462] opened 2022-05-20 23:15 UTC
This feedback applies to both New-LabelPolicy and Set-LabelPolicy cmdlets

It mentions that -Settings parameter is reserved for Microsoft. This is incorrect this is used to configure the mandatory, default and justification settings for the label policy

Full details
- Mandatory label required
- Mandatory label Power Bi
- Mandatory label with groups and site labels
- Disable mandatory label in Outlook
- Justification to downgrade
- Default labels for files
- Default label for Outlook 
- Default label for Groups and sites
- Default label for PowerB

See example

(Get-LabelPolicy -Identity d6d59712-8daa-4d41-a7db-5ecef0cb25b8).settings
Returns
[powerbimandatory, false]
[siteandgroupmandatory, false]
[mandatory, false]
[siteandgroupdefaultlabelid, 53b33ef2-621e-4d62-a684-02365aaee0ac]
[outlookdefaultlabel, defa4170-0d19-0005-0001-bc88714345d2]
[requiredowngradejustification, true]
[defaultlabelid, defa4170-0d19-0005-0003-bc88714345d2]
[disablemandatoryinoutlook, false]
[powerbidefaultlabelid, defa4170-0d19-0005-0002-bc88714345d2]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b52f0d-9a9f-626d-ded6-868dfcb4c505
* Version Independent ID: a8505998-6adb-3311-3cf0-05aafb96355e
* Content: [Set-LabelPolicy (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-labelpolicy?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-LabelPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-LabelPolicy.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-05-20 23:59
Closing as duplicate of #9461

**Closed by chrisda** 2022-05-20 23:59 UTC
Labels: status:duplicate
