### ISSUE TITLE
Created a hidden group but I still see all members

### ISSUE THREAD

**Issue by ilantom** [MicrosoftDocs/office-docs-powershell#9880] opened 2022-09-08 22:12 UTC
I created a hidden group via

New-UnifiedGroup -DisplayName "group-name" HiddenGroupMembershipEnabled

but I still see all the members in the group. What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03921866-8345-7e01-e873-3ec191191fbf
* Version Independent ID: cb374ec2-99c3-7186-66ed-c037a678e946
* Content: [New-UnifiedGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/new-unifiedgroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/New-UnifiedGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/New-UnifiedGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-09-08 23:58
I'm tempted to resolve this as a duplicate of #9879.

Are you using certificate-based authentication (CBA) to connect? That likely won't work.

**Closed** 2022-09-20 14:42 UTC
Labels: area:exchange, Microsoft submitter
