### ISSUE TITLE
Get-CsPoolUpgradeReadinessState is not available in Skype for Business Server 2019.

### ISSUE THREAD

**Issue by NeeranjanShettar** [MicrosoftDocs/office-docs-powershell#1613] opened 2018-08-23 16:42 UTC
Get-CsPoolUpgradeReadinessState is not available in Skype for Business Server 2019, please see if this command is deprecated or missed in the build. Take action accordingly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91c9c3b1-7919-bd59-9ee8-5e2198c61fac
* Version Independent ID: 4a0f1966-0c42-e2ba-1c61-c6602dcc9a46
* Content: [Get-CsPoolUpgradeReadinessState (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/get-cspoolupgradereadinessstate?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Get-CsPoolUpgradeReadinessState.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Get-CsPoolUpgradeReadinessState.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by NeeranjanShettar** [comment] 2018-08-26 12:07
Any updates on assigning this to someone ?

**Comment by AndreaBarr** [comment] 2018-09-21 17:32
@NeeranjanShettar Thank you for this feedback

This is a duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/1610 so I am closing this issue.

**Closed by AndreaBarr** 2018-09-21 17:32 UTC
