### ISSUE TITLE
Issue running the command from PS

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/office-docs-powershell#5451] opened 2020-05-02 11:46 UTC
Hi,

I'm trying to automatically set an externally generated certificate that exists in the Local Computer Personal Store to an SfB 2015 Edge server, however seemingly I cannot do this. I am guessing I am missing a step somewhere.

The certificate to be set is always fins and exists in the Local Machine personal store. Indeed I can import this use the `Import-CsCertificate`  with no issue. However, running `Get-CsCertificate` does NOT show the certificate as avaliable.

If, however, I run through the `SfB 2015 Deployment wizard -> Install or Update -> Request Install, or Assign Cert`, then Assign the cert that shows in the local certificate store, this works without issue. Further, the PS command that shows as being used in the Wizard is exactly the same as that which I try to use from the PS command line, for example:

```
Set-CSCertificate -Type AccessEdgeExternal,DataEdgeExternal,AudioVideoAuthentication,XmppServer -Thumbprint XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -Confirm:$false -Report "C:\Users\Administrator\AppData\Local\Temp\2\Set-CSCertificate-[2020_05_02][12_26_14].html"
```

So the question is, why does it work through the Assign Wizard, but not directly via the CLI? What am I doing wrong?

Running the command via the CLI results in:

```
WARNING: Set-CSCertificate failed.
WARNING: Detailed results can be found at "C:\Users\Administrator\AppData\Local\temp\Set-CSCertificate_20200502T1231583614.html".
Set-CSCertificate : Command execution failed: "‎XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX " not found in MY certificate store or not trusted. To enable 
trust, install the root certificate in the Trusted Certification Authorities store.
At line:1 char:1
+ Set-CSCertificate -Type AccessEdgeExternal,DataEdgeExternal,AudioVide ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-CsCertificate], UnknownObjectException
    + FullyQualifiedErrorId : ProcessingFailed,Microsoft.Rtc.Management.Deployment.SetCertificateCmdlet
```

Obviously all the root certs are installed as well and the cert is trusted on the Edge server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 134b663a-d763-63ca-8c85-66889a690961
* Version Independent ID: 0decdcc3-52f0-0a7c-7b55-022fa77c6dec
* Content: [Set-CsCertificate (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cscertificate?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsCertificate.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsCertificate.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @hirenshah1
* Microsoft Alias: **hirshah**

**Comment by yogkumgit** [comment] 2020-05-04 11:18
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2020-05-11 13:11
Hello @swinster How are you? Hope you are doing great. 👍 

As this is intended to cover issues currently in documentation, I fired up my lab and I tried to reproduce what you are experiencing to see if any impact to the documentation should be made.

I can confirm you that after issuing an `Import-CsCertificate`, the certificate won't show as a result of running `Get-CsCertificate`, this is by design.

I received the same error as you when I copied the thumbprint from the properties of the certificate in mmc snap in, so I wrote the thumbprint letter by letter and it worked without issues.  Although this may be a bit obvious, please make sure you write the thumbprint and not copy it as it can contain hidden chars.

Hope this information helps you.

**Comment by yogkumgit** [comment] 2020-05-12 03:53
@get-itips  Thank you very much for the contribution and sharing this explanation. @swinster 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by swinster** [comment] 2020-05-17 17:29
Unfortunately the item passed it is extracted programmatically, so I'm not entire sure what I can do with validating the data. @get-itips when you typed in the information, exactly what format di you use?

**Comment by get-itips** [comment] 2020-05-18 11:20
> Unfortunately the item passed it is extracted programmatically, so I'm not entire sure what I can do with validating the data. @get-itips when you typed in the information, exactly what format di you use?

Hey @swinster How are you? I am not sure what you refer as typing format, but for example I used

`-Thumbprint 934367bf1c9703f877db0f15cb1b586957d3133`

If the issue persists, I recommend opening a support ticket, they will be able to help you further.

**Comment by yogkumgit** [comment] 2020-05-18 11:21
@get-itips  Thank you very much for the contribution and sharing this explanation. @swinster 
Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-05-18 11:21 UTC
Labels: area:teams / skype
