### ISSUE TITLE
Incorrect descriptions for two parameters

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/office-docs-powershell#927] opened 2018-04-26 08:56 UTC
The parameters ConnectionFilterOutUnlicensed and ConnectionUseDisabledFilter have incorrect descriptions:
{{Fill ConnectionFilterOutUnlicensed Description}}
instead of the actual description.

Can this be corrected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2a9f9ba-dbaf-8b0f-04a6-ec103816d049
* Version Independent ID: d8aa0e5f-7d9f-6d64-cd41-ad162ccfac44
* Content: [Add-SPProfileSyncConnection (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/add-spprofilesyncconnection?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Add-SPProfileSyncConnection.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Add-SPProfileSyncConnection.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment] 2018-09-20 18:42
@ykuijs Thank you for this feedback

From what I can tell Trevor has handled this request. I am going to close this issue. If the issue is not resolved please repoen the issue.

**Closed by AndreaBarr** 2018-09-20 18:42 UTC
Labels: area:sp-server-powershell
