### ISSUE TITLE
The Outputs section is missing deviant behavior for Exchange Online

### ISSUE THREAD

**Issue by oleschri** [MicrosoftDocs/office-docs-powershell#4428] opened 2019-11-21 16:43 UTC
On successfully creating a DistributionGroup the cmdlet New-DistributionGroup always writes the following text to the PowerShell host which cannot be redirected or suppressed in any way. The Exchange team might rethink being bad PowerShell citizens. See also: https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/35163415-new-distributiongroup-allow-redirection-of-infor

(localized de-de)
"Neu! Office 365-Gruppen sind die neue Generation von Verteilerlisten.
Gruppen bieten Teams gemeinsam genutzte Tools für die Zusammenarbeit mittels E-Mail, Dateien, einen Kalender und mehr.
Sie können sofort anfangen, indem Sie das Cmdlet "New-UnifiedGroup" verwenden."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eae749c-28e8-a53b-857e-b8f5d64b0806
* Version Independent ID: 32c33918-11d3-01a0-4e7b-0e218d5ff263
* Content: [New-DistributionGroup (exchange)](https://docs.microsoft.com/en-us/powershell/module/exchange/users-and-groups/new-distributiongroup?view=exchange-ps#feedback)
* Content Source: [exchange/exchange-ps/exchange/users-and-groups/New-DistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/users-and-groups/New-DistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment] 2019-11-22 07:10
@officedocsbot assign @yogkumgit

**Comment by msbemba** [comment] 2019-11-25 12:39
@oleschri Thank you for your feedback.  This message is by design when you run new-distributiongroup cmdlet and it is an informational message for admins. As such, there is no need for a change in the document specified.

Thanks
Sri

**Comment by msbemba** [comment] 2019-11-25 12:42
@oleschri  You can upvote the design change via the UserVoice that was mentioned earlier (https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/35163415-new-distributiongroup-allow-redirection-of-infor) so that the product group can take action accordingly. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment] 2019-11-25 12:44
@msbemba  Thank you very much for the contribution and sharing this explanation. @oleschri 
Hope this comment is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2019-11-25 12:44 UTC
Labels: area:exchange
