### ISSUE TITLE
Same Issue again see Issue#9518

### ISSUE THREAD

**Issue by nicuberger** [MicrosoftDocs/office-docs-powershell#9906] opened 2022-09-15 08:25 UTC
Sometimes we are running into "Internal server error occured" again when we are using Set-CsOnlineSchedule. Last time there was an DNS resolving problem on your side.
![issue](https://user-images.githubusercontent.com/61410367/190354080-c967856d-2892-41b0-8e09-450028d921aa.png)

**Comment by yinzh798** [comment] 2022-09-20 17:52
Thank you so much for reporting it to Microsoft. There was a single server issue caused by a recent change in a machine pool. The issue has been identified and fixed since last Thursday.

**Comment by yogkumgit** [comment] 2022-09-21 04:15
@nicuberger Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-09-21 04:15 UTC
Labels: area:teams
