### ISSUE TITLE
Links in Skype cmdlets related links sections are wrong

### ISSUE THREAD

**Issue by tomlarse** [MicrosoftDocs/office-docs-powershell#10] opened 2017-10-12 11:13 UTC
If you browse a cmdlet at https://docs.microsoft.com/en-us/powershell/module/skype/?view=skype-ps, the links in the "Related links" section all seem to be linking back to the page itself.

For instance on https://docs.microsoft.com/en-us/powershell/module/skype/new-csserverapplication?view=skype-ps, the related links are to Set-CsServerApplication and Remove-CsServerApplication, but both links point back to https://docs.microsoft.com/en-us/powershell/module/skype/new-csserverapplication?view=skype-ps instead. 

In the [.md file](https://github.com/MicrosoftDocs/office-docs-powershell/blame/master/skype/skype-ps/skype/Get-CsConversationHistoryConfiguration.md#L124-L126) it seems to be right with 

```
[Remove-CsConversationHistoryConfiguration]()

[Set-CsConversationHistoryConfiguration]()
```

This seems to be the case on all (or at least many, everyone I've checked so far) cmdlets

**Comment by kenwith** [comment] 2017-10-12 16:13
Confirmed as a bug and I opened an issue with the team that handles the push from GitHub to docs.microsoft.com. Thank you for reporting! I will leave this open until I can get a resolution.

**Comment by kenwith** [comment] 2017-10-12 22:57
Just a quick update. The format needs to be like this:

[Get-CsDeviceUpdateRule](Get-CsDeviceUpdateRule.md)

I will need to write a program to manipulate these since there are so many. Or if anyone else wants to volunteer to do it. :)   I am thinking Python .. plan is to get this done and updated within a couple of weeks. I will update this issue when done.

**Comment by kenwith** [comment] 2017-10-13 16:29
OMG I LOVE YOU! :)  Merged and links should be working shortly!

**Closed by kenwith** 2017-10-13 16:29 UTC

**Comment by thedanfernandez** [comment] 2017-10-13 17:11
This is great thanks for the contribution!

**Comment by tomlarse** [comment] 2017-10-13 20:21
Glad to be of any help :)
