### ISSUE TITLE
Get-TeamChannelUser gives inconsistent results

### ISSUE THREAD

**Issue by vishnookumar** [MicrosoftDocs/office-docs-powershell#9628] opened 2022-07-06 05:42 UTC
I am using the Get-TeamChannelUser to get the list of members in a private channel, but it is giving inconsistent result. I ran the command thrice continuously, but the results are different each time. Refer the screenshot. 

Get-TeamChannelUser -GroupId 5db1753c-9c4a-4082-b404-9300d8d10ff4 -DisplayName Private2

![image](https://user-images.githubusercontent.com/70580406/177477377-52ee0896-842c-4402-adb7-dbfc5e770355.png)

I also tried with Graph API Explorer and found the same issue. The results are inconsistent every time we execute the Graph Query

GET https://graph.microsoft.com/v1.0/teams/5db1753c-9c4a-4082-b404-9300d8d10ff4/channels/19:c1dfc674e7e94bf59d27ec4283556992@thread.tacv2/members

I have tried this with multiple teams & private channels, but observed the same behavior. I also tried on a different tenant, same behavior.

**Comment by vishnookumar** [comment] 2022-07-08 10:26
Hi @yogkumgit Are you able to reproduce this and file an issue to fix this?

**Comment by get-itips** [comment] 2022-07-11 20:21
Hello @vishnookumar 
Here, we are limited to **documentation** fixes and improvements, besides that, I could not reproduce, the best in this case would be to open a support request from your tenant.
Thank you,

**Comment by yogkumgit** [comment] 2022-07-14 06:09
@get-itips Thank you very much for the contribution and sharing this explanation. @vishnookumar Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-07-14 06:09 UTC
Labels: area:teams, support-request
