### ISSUE TITLE
Usage limits for Set-SPOSite cmdlet on Groups site are missing documentation

### ISSUE THREAD

**Issue by nikrampi** [MicrosoftDocs/office-docs-powershell#1555] opened 2018-08-08 10:40 UTC
I tried update site Title (different from site Name that can be set in web interface) but cmdlet is returning error because site is connected to Groups. This limitation is not described in documentation.

Returned error string is:

Set-SPOSite : https://mycompanytenant.sharepoint.com/teams/biblio is a Groups site collection. The valid parameters for this type of site collection are '-Identity',
'-AllowSelfServiceUpgrade', '-DenyAddAndCustomizePages', '-DisableCompanyWideSharingLinks', '-DisableSharingForNonOwners', '-LockState', '-Owner', '-ResourceQuota',
'-ResourceQuotaWarningLevel', '-SandboxedCodeActivationCapability', '-SharingCapability', '-ShowPeoplePickerSuggestionsForGuestUsers', '-StorageQuota', '-StorageQuotaReset', and
'-StorageQuotaWarningLevel'.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 5d1c6b2b-5af6-acce-b7e8-bf784bb0973e
* Version Independent ID: 301586d3-ec04-c42d-4681-0bb59443d35c
* Content: [Set-SPOSite (sharepoint-online)](https://docs.microsoft.com/it-it/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment] 2018-09-21 00:09
@nikrampi Thank you for this feedback

I am going to get this to the PowerShell team so we can get this updated. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by fredericklin** [comment] 2018-12-18 08:06
@AndreaBarr I noticed Set-AzureADMSGroup -Title will eventually trigger an SPOSite title change.  

Would you be able to indicate how quickly these changes should replicate?  I understand when you execute these sequentially that it does not guarantee FIFO.  Is there a process to ensure that if the title update is made out-of-order that the SPO site title will be eventually be consistent with the Unified Group display name?

**Comment by AndreaBarr** [comment] 2018-12-18 17:34
@tseward Could you please investigate this issue?

**Comment by fredericklin** [comment] 2018-12-18 17:57
@AndreaBarr @tsweard @kenwith Thanks! We have a few site collections that are still not being updated from a Set-AzureADMSGroup.  It's been about 18 hours so far.  We've tried running the cmdlet again with the same values with the intention to trigger replication but it is still not setting the SPOSite title.

This is important to us because we have an automated process in applying a naming policy to the group, site, and email alias using a process that is specific to our business (goes beyond what is provided with Microsoft's naming policy controls).

**Comment by kenwith** [comment] 2018-12-20 16:58
@fredericklin - it definitely sounds like it could be a bug. The fastest way would be to open a support service request in your tenant and they can escalate it right away to get it resolved. Let's keep this issue open and then we will update the article as we work with support and product team to figure out what is going on. Would you be comfortable communicating here as support discusses with you? You can also let support and product team know to please loop me in (my Microsoft alias is kenwith) and @tseward and I can get this article updated as support and product team figure it out.

**Comment by fredericklin** [comment] 2018-12-20 17:53
@kenwith  @tseward I suspect we won't pick this up until January due to holiday season.  Will definitely update here with discussions on progress.

**Comment by get-itips** [comment] 2019-05-17 19:25
Hello @nikrampi 
Thanks for your feedback.
I tested in my lab and could reproduce the error trying to change the title on a Groups SC, this was fixed in documentation after you made this comment in https://github.com/MicrosoftDocs/office-docs-powershell/pull/2939 
Also, I could use Set-AzureADMSGroup to change the title of a Group that ended changing the title of the site and that can be used as alternative.
We will proceed closing this issue.
Thank you

**Comment by yogkumgit** [comment] 2019-05-20 13:07
@get-itips  Thank you very much for the contribution and sharing this explanation. @nikrampi 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment] 2019-05-20 13:07
@officedocsbot close

**Closed by yogkumgit** 2019-05-20 13:07 UTC
Labels: area:spo-powershell
