### ISSUE TITLE
New-SPManagedAccount is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by samboustani** [MicrosoftDocs/office-docs-powershell#1727] opened 2018-09-12 15:09 UTC
New-SPManagedAccount : The term 'New-SPManagedAccount' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ New-SPManagedAccount -Credential $SearchService
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-SPManagedAccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1934d19d-71c8-ef02-1f78-681e63a52789
* Version Independent ID: 6e20458b-807e-be10-f5c2-bdba099d4d7c
* Content: [New-SPManagedAccount (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spmanagedaccount?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/New-SPManagedAccount.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/New-SPManagedAccount.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment] 2018-09-21 20:10
@samboustani Thank you for this feedback

It looks like Trevor has given you an answer for your issue. I am going to close this issue. If the issue is not resolved please reopen the issue.

**Closed by AndreaBarr** 2018-09-21 20:10 UTC
