### ISSUE TITLE
[teams] Phone numbers assigned to users

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/office-docs-powershell#10701] opened 2023-04-05 23:50 UTC
To get information about DirectRouting phone number assigned to user accounts, I can use `Get-CsOnlineUser` and `Get-CsPhoneNumberAssignment` cmdlets. It appears these two cmdlets read data from different sources, thus produce different results.

It would be great if you can add some info into Description section explaining why we get different results about assigned numbers from `Get-CsOnlineUser` and `Get-CsPhoneNumberAssignment` cmdlets, and what it means for us from practical perspective. 

A screenshot showing different assigned phone number info for user "c307ecda-9a49-46e8-94f2-caa60b830f7f":

![image](https://user-images.githubusercontent.com/31003608/230237186-148f4405-47db-4e35-bf14-b1b33acee47a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bfb9351-75be-abb8-c8ac-bf08f51d08a1
* Version Independent ID: c7925810-6411-9371-7a04-fc28a4c827ec
* Content: [Get-CsPhoneNumberAssignment (MicrosoftTeamsPowerShell)](https://learn.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps)
* Content Source: [teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md)
* Service: **teams-powershell**
* GitHub Login: @JensTrier
* Microsoft Alias: **jenstr**

**Comment by get-itips** [comment] 2023-04-11 00:18
Hello @shivtorov I'm working on this.

**Comment by get-itips** [comment] 2023-04-11 15:30
Hello @shivtorov 
I asked the product team and they couldn't reproduce this behavior, so I was adviced if you can please open a support request to understand your scenario.
Thank you

**Comment by yogkumgit** [comment] 2023-04-12 16:13
@get-itips Thank you very much for the contribution and sharing this explanation. @shivtorov Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment] 2023-04-12 16:13
@get-itips Thank you very much for the contribution and sharing this explanation. @shivtorov Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed** 2023-04-12 16:13 UTC
Labels: area:teams, support-request
