### ISSUE TITLE
-Verbose seems to do nothing

### ISSUE THREAD

**Issue by EricWarnke** [MicrosoftDocs/office-docs-powershell#1909] opened 2018-10-18 19:19 UTC
Adding -Verbose appears to have no effect. The request returns nothing unless it is malformed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f61076b-1d49-4f87-b400-fff52d067ea8
* Version Independent ID: 8173ce51-c1ef-50be-2069-1ccd3d0ab5b3
* Content: [Request-SPOPersonalSite (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/request-spopersonalsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md)
* Service: **sharepoint-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment] 2018-10-19 17:12
@EricWarnke Thank you for this feedback

I will get this information about -Verbose not working to the PowerShell team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by VesaJuvonen** [comment] 2018-10-24 13:20
This is by designs. There simply is no special handling for verbose switch in many of the SPO cmdlets. Surely that would be nice, but as the cmdlets are calling remote APIs under the hood, they can't provide you details what's happening in the service side, in a similar way as the server side PowerShell can do. Technically when SPO PowerShell is called, it calls remotely an API in the SPO - there's no way we can provide details on the progress of the execution within the current implementation and we are not planning to change this model for now as it would require a significant rewrite for existing design.

**Comment by EricWarnke** [comment] 2018-10-24 16:01
@VesaJuvonen Thanks for your reply. I suggest you update the documentation so that users like me do not expect it to work if it is designed not to work. 

Your docs literally say `This example requests that two users to be enqueued for the creation of a Personal Site and the status of the command will be displayed.` for the Verbose flag...

In fact, this entire command provides zero feedback at any time. If I wanted to just call the raw API are you able to provide that for me?

**Comment by VesaJuvonen** [comment] 2018-10-25 12:59
Additional texts have been now removed. This cmdlet uses CSOM method of Tenant.RequestPersonalSites(string) under the covers. It simply calls the remote API exposed in the server side without any progress indications, so calling the API directly does not give you an additional set of information.

**Comment by byteben** [comment] 2018-11-02 14:19
Can you add the schedule for the timer job that creates the personal sites please

**Comment by VesaJuvonen** [comment] 2019-01-15 08:49
Closing as answered as the @byteben's comment is not really related on the original issue.

**Closed by VesaJuvonen** 2019-01-15 08:49 UTC
Labels: area:spo-powershell
