### ISSUE TITLE
The -SyncToItems parameter not working

### ISSUE THREAD

**Issue by joannecklein** [MicrosoftDocs/office-docs-powershell#3390] opened 2019-05-10 03:21 UTC
I'm trying to use this cmdlet to set the default retention label for a library and sync that label to all existing items. The label is being set as the default, however the label isn't being applied to existing items in the library. It is my understand the -SyncToItems parameter set to $true should do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdca3e3c-69bb-f4f8-2711-0f93c016e84b
* Version Independent ID: 4aee2eaf-c707-f796-34c1-335968f4bc6d
* Content: [Set-PnPLabel (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplabel?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPLabel.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPLabel.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment] 2019-05-10 11:24
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2019-05-17 12:42
Hello @joannecklein 
Thanks for your feedback.
I could reproduce the behavior both in PnP Powershell and the Sharepoint UI. Although this issue resource is intended to report on issues in documentation. I found the issue reported here https://github.com/SharePoint/PnP-PowerShell/issues/1841 please follow that issue for updates.
We will proceed closing this one.

**Comment by yogkumgit** [comment] 2019-05-17 13:23
@get-itips  Thank you very much for the contribution and sharing this explanation. @joannecklein 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment] 2019-05-17 13:24
@officedocsbot close

**Closed by yogkumgit** 2019-05-17 13:24 UTC
Labels: area:pnp-powershell
