### ISSUE TITLE
Incorrect Scripts

### ISSUE THREAD

**Issue by devonbowers** [MicrosoftDocs/office-docs-powershell#9991] opened 2022-10-03 14:39 UTC
Powershell scripts do not work as written, missing close brackets on some, need to nest your loops, please test these before posting!

use something like this 
foreach ($NP in $NPS) {Set-User -Identity $NP -RemotePowerShellEnabled $false}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d03c6ce2-687b-e138-939b-413014d1c81a
* Version Independent ID: 9fe6c492-d0fe-e454-6574-06de8cd31a21
* Content: [Control remote PowerShell access to Exchange servers](https://learn.microsoft.com/en-us/powershell/exchange/control-remote-powershell-access-to-exchange-servers?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by DMoenks** [comment] 2022-10-03 16:52
Duplicate of #9990

**Comment by chrisda** [comment] 2022-10-03 17:19
Closing as duplicate of #9990.

That topic has been incorrect for a long time. Four years at least.

Thanks for the feedback.

Closing

**Closed by chrisda** 2022-10-03 17:19 UTC
Labels: area:exchange
