### ISSUE TITLE
-AcceptLicense parameter required

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/office-docs-powershell#4701] opened 2020-01-18 18:06 UTC
PackageManagement\Install-Package : License Acceptance is required for module 'ExchangeOnlineManagement'. Please specify 
'-AcceptLicense' to perform this operation.

So the documentation needs to be updated to have the -AcceptLicense option added to the command line. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de2836a0-0af3-c147-2d4a-78220ac4e0f1
* Version Independent ID: 2cde9735-6281-bb9f-bf07-b30b2f6c7f37
* Content: [Exchange Online PowerShell V2](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment] 2020-01-20 09:52
@officedocsbot assign @yogkumgit

**Comment by dariomws306** [comment] 2020-01-21 23:11
Hi @alexverboon, thank you for your feedback.

You should get this screen when you run "Install-Module -Name ExchangeOnlineManagement":
![image](https://user-images.githubusercontent.com/33589238/72851362-30cb3a80-3c8a-11ea-8506-9829345709d0.png)

**Comment by dariomws306** [comment] 2020-01-21 23:12
And if you run "Install-Module -Name ExchangeOnlineManagement -RequiredVersion 0.3527.3" you won't get a prompt for License Acceptance.

What command are you running to install this module?

**Comment by michevnew** [comment] 2020-01-23 09:11
You'll get the error if you run the cmdlet with -Force, and I suppose this is by design.

**Comment by dariomws306** [comment] 2020-01-23 13:39
Thank you @michevnew!

In this case I think it's outside the scope of the document and the error message is self explanatory.

**Comment by yogkumgit** [comment] 2020-01-23 15:42
@dariomws306  Thank you very much for the contribution and sharing this explanation. @alexverboon Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-01-23 15:42 UTC
Labels: area:exchange
