### ISSUE TITLE
Get-CsUserCallingSettings returns no value for some attributes for some users in our tenant

### ISSUE THREAD

**Issue by richardh-ncp** [MicrosoftDocs/office-docs-powershell#8948] opened 2022-02-14 08:01 UTC
I have been experiementing with the new "Get-CsUserCallingSettings" cmdlet in 3.0.1

I notice that for some of our users attribute are blank where it is assumed that a value should be present

For example "IsForwardingEnabled" should have a value of true or false, yet for half our users nothing is displayed
Similar for "ForwardingType"

Any other tests i should try??

**Comment by JensTrier** [comment] 2022-02-14 10:51
@richardh-ncp thanks for the feedback. 

Seeing IsForwardingEnabled and IsUnansweredEnabled as blank in the output from Get-CsUserCallingSettings means that the user has not gone and explicitly changed the call forward settings in Microsoft Teams (Settings->Calls. In such cases the default call forwarding settings is in effect, i.e. transfer to voicemail on unanswered.

Seeing other parameters as blank can either be caused by the same default setting as above or by how the settings have been changed by the user via the Microsoft Teams client.

I'll add a note about this to the Get-CsUserCallingSettings documentation

**Comment by richardh-ncp** [comment] 2022-02-16 11:22
This was my guess

For a new user i see this:

SipUri                    : sip:xxxxxx@dxxxxxxxxxxxxx.com
IsForwardingEnabled       : 
ForwardingType            : 
ForwardingTarget          : 
ForwardingTargetType      : 
IsUnansweredEnabled       : 
UnansweredTarget          : 
UnansweredTargetType      : 
UnansweredDelay           : 00:00:20
Delegates                 : 
Delegators                : 
CallGroupOrder            : Simultaneous
CallGroupTargets          : {}
GroupMembershipDetails    : 
GroupNotificationOverride : 


For a user who has been 'adjusting' settings i see this:

SipUri                    : sip:yyyyy@dxxxxxxxxxxx.com
IsForwardingEnabled       : False
ForwardingType            : Immediate
ForwardingTarget          : 
ForwardingTargetType      : Voicemail
IsUnansweredEnabled       : True
UnansweredTarget          : 
UnansweredTargetType      : Voicemail
UnansweredDelay           : 00:00:20
Delegates                 : 
Delegators                : 
CallGroupOrder            : Simultaneous
CallGroupTargets          : {}
GroupMembershipDetails    : 
GroupNotificationOverride : 

Good to know it isnt a bug and the cmdlet can be trusted

**Comment by yogkumgit** [comment] 2022-02-17 07:55
@richardh-ncp Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-02-17 07:55 UTC
Labels: area:teams, doc-enhancement
