### ISSUE TITLE
Which Version of SharePoint Server

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-docs-powershell#1327] opened 2018-06-24 20:56 UTC
Please identify the versions of SharePoint for which these cmdlets will work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a90c18-81d3-0ae4-0abb-a4fa9c331f4b
* Version Independent ID: bbfcc73a-2696-527e-8e6d-95b5bc8b7f17
* Content: [SharePoint Server PowerShell](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/index?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/sharepoint-server.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/sharepoint-server.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment] 2018-06-24 21:28
This should be part of the cmdlet documentation. As parameters vary in terms of support, I think it's easier to document each cmdlet directly rather than on this very long list. There are also minimal variations from 2010 to 2016, so nearly all cmdlets would state "2010, 2013, 2016".

**Comment by DeanGross** [comment] 2018-06-24 21:41
I did not mean to suggest doing it for every cmdlet, I was thinking of something more like what is done on https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps

**Comment by tseward** [comment] 2018-06-24 22:16
Ah thanks, yes I agree that would look nice. I can start working on this; it'll take awhile due to the number of cmdlets.

**Comment by tseward** [comment] 2018-06-30 19:52
@DeanGross let me know if this is along the lines of what you're expecting.

https://github.com/MicrosoftDocs/office-docs-powershell/blob/d7d2217db9559537a200ac996b34193987d2d5c9/sharepoint/sharepoint-ps/sharepoint-server/sharepoint-server.md

**Comment by tseward** [comment] 2018-07-01 16:53
Submitted #1376. Still needs work, but gets us to a point where we can start filling out details.

**Comment by DeanGross** [comment] 2018-07-19 19:46
Thanks that looks like it will be very helpful

**Comment by kenwith** [comment] 2018-07-19 19:50
Super awesome @tseward !    @Techwriter40 - ok to merge?

**Comment by AndreaBarr** [comment] 2018-09-20 21:48
@DeanGross Thank you for this feedback

It looks like Trevor handled your request. I am going to close this issue. If the issue is not resolved please reopen the issue.

**Closed by AndreaBarr** 2018-09-20 21:48 UTC
Labels: area:sp-server-powershell
