### ISSUE TITLE
Description body is incomplete

### ISSUE THREAD

**Issue by dr-raypc** [MicrosoftDocs/office-docs-powershell#9830] opened 2022-08-24 15:19 UTC
Can you please update the Description body? Also is there a way to break lines inside the description to make it easier to read?

-Description
This parameter is available only in the cloud-based service.

{{ Fill Description Description }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42e2373d-198f-dba7-285c-66a2a5f384c4
* Version Independent ID: 3329c2f3-bf2d-111a-02dc-ce6d52d8164f
* Content: [Set-DistributionGroup (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/set-distributiongroup?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Set-DistributionGroup.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Set-DistributionGroup.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2022-08-25 16:35
@dr-raypc, generally, when people point out empty parameter descriptions, I say, "by design" and refer them to [this explanation]((https://github.com/MicrosoftDocs/office-docs-powershell/issues/7429#issuecomment-808564486).

However, in this case, there are 40 other cmdlets with a "Description" parameter, so I just copied the description from one of those.

Thanks for the feedback.

Closing

**Closed by chrisda** 2022-08-25 16:35 UTC
Labels: area:exchange, Empty parameter description
