### ISSUE TITLE
Issue while enabling Private CDN for multiple site collections and sub-sites through foreach loop using PowerShell script

### ISSUE THREAD

**Issue by pratyusha-kodumuri** [MicrosoftDocs/office-docs-powershell#1568] opened 2018-08-10 10:29 UTC
I have a requirement to enable Private CDN origin to a custom document library for multiple sharepoint site collections and subsites using PowerShell. I have written CSOM PowerShell code to read all sub sites and trying to add new Origin using "Add-SPOTenantCdnOrigin -CdnType Private -OriginUrl <OriginURL> -Confirm:$false" command but after successfully enabling CDN origin for few subsites, I am facing below issue:

Add-SPOTenantCdnOrigin : Value cannot be longger than 5000.
At line:1 char:1

Add-SPOTenantCdnOrigin -CdnType Private -OriginUrl "OriginURL"
  + CategoryInfo          : NotSpecified: (:) [Add-SPOTenantCdnOrigin], ServerException
  + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.AddTenantCdnOrigin

I could not find this type of error anywhere.

**Comment by AndreaBarr** [comment] 2018-09-21 00:15
@pratyusha-kodumuri Thank you for this feedback

This is a duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/1567 . I am closing this issue as a duplicate.

**Closed by AndreaBarr** 2018-09-21 00:15 UTC
Labels: area:spo-powershell
