### ISSUE TITLE
Faulty method only retrieve one item 

### ISSUE THREAD

**Issue by GamalielCorona** [MicrosoftDocs/office-docs-powershell#3474] opened 2019-05-27 21:43 UTC
Hi there, this method doesn't retrieve Guest accounts list even using -PageSize there are some work around using GET-SPOUser but to be honest there still a lot work to do to filtering and clean data, please can someone give a feedback about this? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f480c3ac-70f4-dd19-e86c-7d95821eb901
* Version Independent ID: 64961e66-bdd4-d9ac-c62d-131dbb13092b
* Content: [Get-SPOExternalUser (sharepoint-online)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spoexternaluser?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOExternalUser.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOExternalUser.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment] 2019-05-28 12:11
@officedocsbot assign @yogkumgit

**Comment by yogkumgit** [comment] 2019-05-29 11:12
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2019-06-05 01:24
Duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/180
@trent-green Can we get some information about this? Is Get-SPOExternalUser getting support for users invited using modern sharing? Thanks

**Comment by yogkumgit** [comment] 2019-06-10 13:05
@trent-green Please reply to the query by @get-itips

**Comment by get-itips** [comment] 2019-07-05 23:34
Hello @trent-green can you help us with this?
Thank you

**Comment by yogkumgit** [comment] 2020-02-19 13:20
@GamalielCorona Thank you for reporting this feedback here. This list is focused on content issues and I want to make sure your immediate product issue does not get lost in this list. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team.

**Closed by yogkumgit** 2020-02-19 13:20 UTC
Labels: area:docs, area:spo-powershell
