### ISSUE TITLE
Difference in output Get-CSonlineUser in version 3.1.1 and 2.3.1

### ISSUE THREAD

**Issue by Fimlore** [MicrosoftDocs/office-docs-powershell#8960] opened 2022-02-15 12:51 UTC
I see a difference in output of Get-CSOnlineUser between versions 3.1.1 and 2.3.1
version 2.3.1:

```
get-csonlineuser -identity XXXXXX@XXXXXXX | fl *uri*, *voice*

OnPremLineURI                : tel:+49XXXXXXXX
LineServerURI                :
OnPremLineURIManuallySet     : True
LineURI                      : tel:+49XXXXXXXX
OnPremEnterpriseVoiceEnabled : False
HostedVoiceMail              : True
EnterpriseVoiceEnabled       : True
TeamsVoiceRoute              : False
VoicePolicy                  : HybridVoice
OnlineVoicemailPolicy        :
VoiceRoutingPolicy           :
HostedVoicemailPolicy        : BusinessVoice
OnlineVoiceRoutingPolicy     :XXX
```

Version 3.1.1:
```
get-csonlineuser -identity XXXXXX@XXXXXXX | fl *uri*, *voice*
LineURI                      : 
OnPremLineURI                : 
EnterpriseVoiceEnabled : False
OnPremEnterpriseVoiceEnabled : False
OnlineVoiceRoutingPolicy     : XXX
OnlineVoicemailPolicy        :
```

is this by design?

**Comment by isrumnon** [comment] 2022-02-16 08:53
Hi @Fimlore yes the returned output attributes are expected as the ones not showing up have been deprecated as documented here https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps

**Comment by Fimlore** [comment] 2022-02-16 09:05
Hi, thanks for the reply. I understand the deprecated items that are missing , but not the assigned lineURI, this can be seen in 2.3.1, but not in 3.1.1

**Comment by isrumnon** [comment] 2022-02-16 09:07
Got it, can you please share your Tenant ID and User ID so my team can look into it? This is unexpected behavior

**Comment by pmisley** [comment] 2022-02-16 16:18
Thank goodness someone else is seeing this as well. I thought I was going crazy. I understand the attributes have been deprecated, but the results are simply wrong. In one version it tells me EnterpriseVoiceEnabled is true and in another it tells me EnterpriseVoiceEnabled is false. I have automation built around this that is now broken since it is returning incorrect results.

**Comment by pmisley** [comment] 2022-02-16 16:26
Some additional details that I have determined around this bug. When performing a single user lookup, the new results are displayed.

`Get-CsOnlineUser -Identity user@domain.com`

If pulling a group of users and then referencing them individually, it displays all the attributes although not all correctly match the expected value.

`$AllUsers = Get-CsOnlineUser`
`$AllUsers[0]`

**Comment by shivtorov** [comment] 2022-02-17 05:08
see 3-rd party blog post about the changes in phone number assignment:
https://www.adamfowlerit.com/2022/01/microsoft-teams-powershell-phone-number-assigning-cmdlet-change/

**Comment by isrumnon** [comment] 2022-02-17 06:56
@pmisley can you share your tenant ID and impacted user ID so we can get it checked out?

**Comment by poshdude** [comment] 2022-02-17 08:56
I'm seeing this behaviour with any MicrosoftTeams v3.x.x.  Not only are certain properties not being returned the types are also different.




$csolProps = @(
    'UserPrincipalName',
    'Enabled',
    'InterpretedUserType',
    'TeamsUpgradeEffectiveMode',
    'Identity',
    'ObjectId',
    'WindowsEmailAddress',
    'LineURI',
    'OnPremLineURI',
    'OnPremLineUriManuallySet',
    'EnterpriseVoiceEnabled',
    'HostedVoicemail',
    'OnlineVoiceRoutingPolicy',
    'TenantDialPlan',
    'TeamsCallingPolicy',
    'TeamsEmergencyCallingPolicy',
    'TeamsEmergencyCallRoutingPolicy',
    'UsageLocation'
)
Import-Module MicrosoftTeams -RequiredVersion <version>
Connect-MicrosoftTeams
$csonlineuser = Get-CsOnlineUser -Identity <upn> | Select $csolProps
$csonlineuser | Get-Member -MemberType Properties  | Select -ExpandProperty Name | ForEach-Object {
    
    $r = [ordered]@{}
    try {
        $r.Add('PropertyName', $_)
        $p = $csonlineuser.$_
        $r.Add('Type', $p.GetType().fullname)
    }
    catch{
        [string]$v = if ($_.Exception.Message -match "null-valued") {'No value returned.'} else {$_.Exception.Message}
        $r.Add('Type', $v)
    }
    finally {
        [pscustomobject]$r
    }
}



**e.g. 3.1.1**

PropertyName                    Type
------------                    ----
Enabled                         No value returned.
EnterpriseVoiceEnabled          System.Boolean
HostedVoicemail                 No value returned.
Identity                        System.String
InterpretedUserType             System.String
LineUri                         System.String
ObjectId                        No value returned.
OnlineVoiceRoutingPolicy        Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.UserPolicyDefinition
OnPremLineUri                   System.String
OnPremLineUriManuallySet        No value returned.
TeamsCallingPolicy              Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.UserPolicyDefinition
TeamsEmergencyCallingPolicy     Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.UserPolicyDefinition
TeamsEmergencyCallRoutingPolicy Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.UserPolicyDefinition
TeamsUpgradeEffectiveMode       System.String
TenantDialPlan                  Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.UserPolicyDefinition
UsageLocation                   System.String
UserPrincipalName               System.String
WindowsEmailAddress             No value returned.

**e.g. 2.3.1**

PropertyName                    Type
------------                    ----
Enabled                         System.Boolean
EnterpriseVoiceEnabled          System.Boolean
HostedVoiceMail                 System.Boolean
Identity                        System.String
InterpretedUserType             System.String
LineURI                         System.String
ObjectId                        System.Guid
OnlineVoiceRoutingPolicy        System.String
OnPremLineURI                   System.String
OnPremLineURIManuallySet        System.Boolean
TeamsCallingPolicy              System.String
TeamsEmergencyCallingPolicy     System.String
TeamsEmergencyCallRoutingPolicy System.String
TeamsUpgradeEffectiveMode       System.String
TenantDialPlan                  System.String
UsageLocation                   System.String
UserPrincipalName               System.String
WindowsEmailAddress             System.String

**Comment by DEberhardt** [comment] 2022-02-17 09:26
Personally, I am only missing VoicePolicy as I was ascertaining the VoiceConfigType from there.
Based on this table: https://docs.microsoft.com/en-us/microsoftteams/direct-routing-migrating#user-provisioning-end-state-for-various-pstn-connectivity-options, I have created an `InterpretedVoiceConfigType` that now defaults to `Unknown` because of VoicePolicy not being there anymore... Would it be possible to return that in one form or another?

Thanks,
David

**Comment by isrumnon** [comment] 2022-02-17 11:32
@DEberhardt what was the output you were looking at previously in VoicePolicy and expecting to see in the new TPM version?

**Comment by DEberhardt** [comment] 2022-02-17 13:12
This was 'BusinessVoice' for managed Numbers (Calling Plan, et. all - unknown whether this also extended to operator Connect as that was not documented in the above documentation for Direct Routing). and 'HybridVoice' for unmanaged Numbers (i.E. Direct Routing and Skype For Business Hybrid PSTN connectivity, etc.).

Based on that, I have created a small logic that creates the VoiceConfigType based on current configuration (if HybridVoice and an OVP is assigned, that is `DirectRouting`, if HybridVoice and a VoiceRoutingPolicy is assigned, thats `SkypeForBusinessHybridPSTN`).

```powershell
#$CsUser = Get-CsOnlineUser <UPN>     
    function TestVoiceConfigType ($CsUser) {
      if ($CsUser.VoicePolicy -eq 'BusinessVoice') {
        Write-Verbose -Message "InterpretedVoiceConfigType is 'CallingPlans' (VoicePolicy found as 'BusinessVoice')"
        $InterpretedVoiceConfigType = 'CallingPlans'
      }
      elseif ($CsUser.VoicePolicy -eq 'HybridVoice') {
        Write-Verbose -Message "VoicePolicy found as 'HybridVoice'"
        if ($null -ne $CsUser.VoiceRoutingPolicy -and $null -eq $CsUser.OnlineVoiceRoutingPolicy) {
          Write-Verbose -Message "InterpretedVoiceConfigType is 'SkypeHybridPSTN' (VoiceRoutingPolicy assigned and no OnlineVoiceRoutingPolicy found)"
          $InterpretedVoiceConfigType = 'SkypeHybridPSTN'
        }
        else {
          Write-Verbose -Message "InterpretedVoiceConfigType is 'DirectRouting' (VoiceRoutingPolicy not assigned)"
          $InterpretedVoiceConfigType = 'DirectRouting'
        }
      }
      else {
        Write-Verbose -Message "InterpretedVoiceConfigType is 'Unknown' (undetermined)"
        $InterpretedVoiceConfigType = 'Unknown'
      }
      return $InterpretedVoiceConfigType
    }
```

If you can build that into the parameter by default, it would be even better 😄

**Comment by pmisley** [comment] 2022-02-18 01:44
> @pmisley can you share your tenant ID and impacted user ID so we can get it checked out?

@isrumnon 

Tenant ID: b1c14d5c-3625-45b3-a430-9552373a0c2f
User ID: Elizabeth.Carrasco@sas.com

**Comment by isrumnon** [comment] 2022-02-18 10:08
@pmisley we made some changes on our end - this should fix this issues you are experiencing with unexpected values for bulk queries. 
The results displayed for single user values is by design given the deprecated attributes were SfBO specific

**Comment by Fimlore** [comment] 2022-02-21 12:16
After doing some tests and getting crazier by the second, please observe the outputs below:

Multi user search:
`
$users = get-csonlineuser -Filter {Enabled -eq $true}
$users | where-object {$_.UserPrincipalName -eq "User@Customer.com" -and $_.OnlineVoiceRoutingPolicy -like "*-*" -and $_.Enabled -eq $true} | select-object UserprincipalName,LineURI,OnlineVoiceRoutingPolicy
`

OUTPUT:
`
UserPrincipalName            LineURI            OnlineVoiceRoutingPolicy
-----------------            -------            ------------------------
User@Customer.COM tel:+49XXXXXXXX DE-International
`

SingleUserSearch:
`
get-csonlineuser "User@Customer.COM" | where-object {$_.AccountEnabled -eq $true -and $_.LineURI -lt 0} | select-object UserprincipalName,LineURI,OnlineVoiceRoutingPolicy
`

OUTPUT:
`UserPrincipalName            LineUri OnlineVoiceRoutingPolicy
-----------------            ------- ------------------------
User@Customer.COM         DE-International
`


Also, the MultiUserSearch uses Enabled -EQ $true as its filter, while the property is AccountEnabled in the actual users' list - not what this is about, the issue is the Missing (or in fact the REPORTED) LineURI.

The LineURI is ALSO missing on the TAC - User is unable to receive calls, so the multi-user report is WRONG.

**Comment by Fimlore** [comment] 2022-02-21 12:25
Having done some tests and getting craz

> Got it, can you please share the impacted Tenant ID and User ID so my team can look into it? This is unexpected behavior

Can I sent this in a DM, or something less "visible" to everyone on the internet? :)

**Comment by vincentkurmi** [comment] 2022-02-21 12:45
Hi @Fimlore, we are discussing about similar behavior here https://github.com/MicrosoftDocs/office-docs-powershell/issues/8935 and here https://github.com/MicrosoftDocs/office-docs-powershell/issues/8973

**Comment by Fimlore** [comment] 2022-02-21 12:51
> Hi @Fimlore, we are discussing about similar behavior here #8935 and here #8973

ok. just so you are aware, this is the same module I am using (3.2.0-preview)

**Comment by isrumnon** [comment] 2022-02-22 06:50
@Fimlore we made some changes from our end. Can you check now and confirm?

**Comment by isrumnon** [comment] 2022-02-22 18:39
> @isrumnon I checked the same user and the EnterpriseVoiceEnabled attribute is still returning False during a bulk query. The single user value is correctly returning True. I closed out all active PS sessions and started fresh.

Hi @pmisley we currently do not have a good solution to this issue - you can expect consistent results in point and bulk queries by the end of March. An immediate solution is to reset the phone number through Set-CsUser and re-run the cmdlet. Hope this helps

**Comment by Fimlore** [comment] 2022-02-22 19:49
I do not see any changes in the queries.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by isrumnon** [comment] 2022-02-23 04:45
@Fimlore I'm following up with my team to investigate further

**Comment by JoukevanRossum** [comment] 2022-03-07 12:23
Any updates on this matter?
I've been experiencing same issues.

LineURI format is different in v2.3.1 vs v3.1.1

**Comment by isrumnon** [comment] 2022-03-07 12:45
@JoukevanRossum we are working towards reintroducing the old format. Will update you when my team finalizes on a decision

**Comment by JoukevanRossum** [comment] 2022-03-07 13:21
> @JoukevanRossum we are working towards reintroducing the old format. Will update you when my team finalizes on a decision

Thank you very much.

**Comment by JoukevanRossum** [comment] 2022-03-15 14:24
Another strange addition: is that when I fetch a user from MS Teams using version 2.3.1 the user does not have a lineuri assigned but when using version 4.0.0 all of a sudden it returns a lineuri...

**Comment by isrumnon** [comment] 2022-03-15 17:11
Hi @poshdude , to your queries:

1. LineURI is missing 'tel:+' - Can you please check now? This fix just got deployed today
2. ObjectId is being returned as the Identity property and the ObjectId field is empty - ObjectID has been renamed to Identity, the script you are running causes the ObjectID field to show up empty because it no longer exists 
3. OnPremLineURIManuallySet flag is empty - This has also been removed and is now replaced by OnPremLineURI reason is the following:

OnPremLineURI: This attribute previously used to refer to both:
- LineURI set via OnPrem AD.
- Direct Routing numbers assigned to users via Set-CsUser.

In Teams PowerShell Modules 3.0.0 and above OnPremLineURI will only refer to the LineURI set via on-premises Active Directory.

**Comment by poshdude** [comment] 2022-03-15 18:25
Hi, thanks for the update and good to know about those changes in properties.   I'm afraid LineURI is still missing 'tel:+', have attempted on a couple of our customer tenants and still no show, I shall try again tomorrow and share an update.  

Also, can I confirm that with Get-AzureADUser, ObjectId field has not been renamed but with Get-CsOnlineUser it is now renamed to Identity?

Finally, I have observed another issue with 4.0.0:  e.g. Get-CsOnlineUser -ResultSize 1 just hangs?

**Comment by poshdude** [comment] 2022-03-16 11:34
Hi,

Some inconsistent behaviour to report with 4.0.0 based on today's look (Get-CsOnlineUser -ResultSize 1 is not hanging today).

1. Running Get-CsOnlineUser against a target UPN still doesn't show LineURI with 'tel:+' (NOTE: this UPN **does** have a dirsynced LineURI so we expect a value for OnPremLineUri)
```
Get-CsOnlineUser -Identity <UPN> | Select LineUri, OnPremLineUri

**LineUri                         : 44xxxxxxxxxx**
OnPremLineUri               : tel:+44xxxxxxxxxx

```
2. If I use a filter, the LineURI in the result does show a 'tel:+'  (I thought this maybe a good workaround but see Item 7)
```
Get-CsOnlineUser -Filter {UserPrincipalName -eq '<UPN>'}  | Select LineUri, OnPremLineUri

LineUri                         : tel:+44xxxxxxxxxx
OnPremLineUri            : tel:+44xxxxxxxxxx

```
3. If I re-run the same command as in step 1 again,  the 'tel:+' is still missing in the LineURI value (see Items 5 & 6 for why I did this). 
```
Get-CsOnlineUser -Identity <UPN> | Select LineUri, OnPremLineUri

**LineUri                         : 44xxxxxxxxxx**
OnPremLineUri               : tel:+44xxxxxxxxxx

```
4. If I run a filter like this, the LineURI in the result does show a 'tel:+'  but _also populates OnPremLineUri which is **incorrect** as the UPN this returned does not have a dirsynced LineUri._
```
Get-CsOnlineUser -Filter {LineURI -like '*'} -ResultSize 1  | Select LineUri, OnPremLineUri

LineUri                         : tel:+44xxxxxxxxxx
**OnPremLineUri         : tel:+44xxxxxxxxxx**

```

5. If I target the UPN returned by the Step 4 query directly after, the LineURI in the result does show a 'tel:+'  and the OnPremLineURI is now missing which is correct.  **NOTE: I'm now only getting a 'tel:+' in the LineURI because I ran step 4.**
```
Get-CsOnlineUser -Identity <UPN from Step 4> | Select LineUri, OnPremLineUri
LineUri                                : tel:+44xxxxxxxxxx
OnPremLineUri                   : 

```
6. If I re-run the same command as in step 1 again,  the 'tel:+' is now there in the LineURI value. **NOTE: I'm now only getting a 'tel:+' in the LineURI because I ran step 4.**
```
Get-CsOnlineUser -Identity <UPN> | Select LineUri, OnPremLineUri

LineUri                         : tel:+44xxxxxxxxxx
OnPremLineUri            : tel:+44xxxxxxxxxx

```

7.  If use a filter to target the UPN from Step 4, both LineUri and OnPremLineUri are populated - as per Step 4, this is incorrect.
```
Get-CsOnlineUser -Filter {UserPrincipalName -eq '<UPN from Step 4>'}  | Select LineUri, OnPremLineUri

LineUri                         : tel:+44xxxxxxxxxx
OnPremLineUri            : tel:+44xxxxxxxxxx

```

Looks unusable to me in the present state.

Regards,

**Comment by poshdude** [comment] 2022-03-18 10:46
@isrumnon - any thoughts on the above please?

**Comment by poshdude** [comment] 2022-03-31 10:32
I believe I have identified the reason for the difference in the Teams property values being returned, which appears to be related to whether the data is being returned via AutoRest or a Remoting PSSession.  I have showcased this here [https://github.com/MicrosoftDocs/office-docs-powershell/issues/9182](url) and this issue, where error trapping was not working with AutoRest, here [https://github.com/MicrosoftDocs/office-docs-powershell/issues/9103#issuecomment-1075257455
](url)

@isrumnon - are you able to provide any feedback please on the above assertion?  I saw advisory "TM346847 - Admins are unable to run some cmdlets in Microsoft Teams PowerShell Module version 3.0 and above" recently, is this behaviour an item that is going to be resolved after April 15th?  Thanks.

**Comment by poshdude** [comment] 2022-04-01 10:39
Re-tried with 4.1.0 just released.  Appears to be better consistency for a number of properties. The LineURI/OnPremLineURI properties are still not aligned when using a filter - this is especially important as we are now reliant on the OnPremLine property to indicate whether the user has a telephone number set in the on-premises Active Directory, instead of the now legacy OnPremLineURIManuallySet flag.

```
Get-CsOnlineUser -Identity <UPN> -Verbose | Select LineURI,OnPremLineURI
VERBOSE: EnabledForFlight: True, AutoRestCommandInfo: True

LineUri                     OnPremLineUri
-------                     -------------
tel:+44xxxxxxxxxxx          tel:+44xxxxxxxxxx

# same UPN using a filter
Get-CsOnlineUser -Filter {UserPrincipalName -eq '<UPN>'} -Verbose | Select LineURI,OnPremLineURI
VERBOSE: EnabledForFlight: True, AutoRestCommandInfo: True

LineUri                      OnPremLineURI
-------                      -------------
tel:+44xxxxxxxxxx

```

**Comment by olanga** [comment] 2022-04-01 14:34
Looks like OnPremLineUri is not even on the list of properties while using:
Get-CsOnlineUser -filter "UserPrincipalName -eq '$UPN'"

**Comment by isrumnon** [comment] 2022-04-05 03:09
Hi @poshdude @olanga apologies for the delayed response. OnPremLineURI is currently only available when using Get-CsOnlineUser with the "-Identity" parameter and now indicative of the OnPremLineURIManuallySet Flag. We are looking into how we can reintroduce the OnPremLineURI attribute when using -Filter

**Comment by poshdude** [comment] 2022-04-05 07:22
@isrumnon thanks for the response.  Good to know it's being looked at as it doesn't make sense for the same command to return different property sets.  I'm sure there is a use case for wanting to retrieve a batch of users with a filter and identify those who have an OnPrem synced phone number. Cheers.

**Comment by JoukevanRossum** [comment] 2022-04-05 08:28
@isrumnon do you know what will happen with the current commandlets of version 2.3.1 once they are deprecated?
As of now, the new commandlets are still not working properly.. Is the deprecation postponed?

**Comment by isrumnon** [comment] 2022-04-05 08:39
@JoukevanRossum  these OnPrem attributes are available with -Identity scenario currently. In non -Identity scenario Onprem attributes will also be added soon. Older versions will go away starting 15 June

**Comment by vlethiec** [comment] 2022-04-05 16:19
@JoukevanRossum, for info here is the official communication. 
![image](https://user-images.githubusercontent.com/52075388/161799877-178d559b-493c-4669-a2c7-08525852bda2.png)

**Comment by yogkumgit** [comment] 2022-04-08 04:40
@Fimlore Hope this helps, kindly close this issue.

**Closed** 2022-05-03 12:19 UTC
Labels: area:teams, doc-enhancement
