### ISSUE TITLE
Adding owners to teams adds as members

### ISSUE THREAD

**Issue by meven3000** [MicrosoftDocs/office-docs-powershell#5940] opened 2020-06-18 09:29 UTC
Hi, when attempting to add multiple owners 3+ to a new team, subsequent owners appear to be added as owners in the team under PowerShell, Groups. However, when visiting the team via the Teams App or Website, only the first owner which was added is in fact the owner. All other "owners" are listed as members, and access permission is as members.

The user who creates the group is added as an owner [service account], the second owner is added correctly. other appears as members in the GUI.

Testing Scenario 1
                          Add-TeamUser -GroupId $Teamgroup.GroupId -User $NewMember -Role Member 
                          Add-TeamUser -GroupId $Teamgroup.GroupId -User $NewMember -Role Owner 

Testing Scenario 1
                          Add-TeamUser -GroupId $Teamgroup.GroupId -User $NewMember -Role Owner 

![GroupError2](https://user-images.githubusercontent.com/63767341/85003545-b4397b00-b199-11ea-9906-fc25efe8905e.PNG)
![GroupError3](https://user-images.githubusercontent.com/63767341/85003550-b56aa800-b199-11ea-9a31-bf6ba81f7804.PNG)
![GroupError1](https://user-images.githubusercontent.com/63767341/85003551-b6033e80-b199-11ea-8cc7-db9d1c1679a8.PNG)

**Comment by yogkumgit** [comment] 2020-06-18 12:56
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2020-06-22 12:35
Hello @meven3000 
Are you using the latest stable release Teams PowerShell module (1.0.7) ?
Thanks

**Comment by meven3000** [comment] 2020-06-22 21:45
Yep 1.0.7

**Comment by get-itips** [comment] 2020-06-23 12:19
Hello @meven3000 How are you?
Correct me if I misunderstood any of the steps taken by you, however, I could not reproduce what happened to you:


![image](https://user-images.githubusercontent.com/36666927/85402497-2d3a2900-b532-11ea-99a2-a9f8c383c599.png)

![image](https://user-images.githubusercontent.com/36666927/85402533-3a571800-b532-11ea-8cee-772bfe9cd187.png)

All members added as owners were instantly listed as owners in Teams App/Web.



If this situation continues for you I suggest contact support directly in your tenant for your scenario, they will be able to help you further.

Thanks

**Comment by yogkumgit** [comment] 2020-06-24 10:36
@get-itips  Thank you very much for the contribution and sharing this explanation. @meven3000 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-06-24 10:36 UTC
Labels: area:teams
