### ISSUE TITLE
Single user not found

### ISSUE THREAD

**Issue by sarollins** [MicrosoftDocs/office-docs-powershell#7621] opened 2021-04-15 19:45 UTC
[Enter feedback here]
Attempting to add/remove users (call answering users) using the PowerShell cmdlet Set-CsCallQueue

To add a new user, this works

$o = Get-CsCallQueue -Identity "d2187857-4011-41b2-b44a-2019ee167526" | Select Users
$o.Users.Add("A111DDA8-DCFC-4905-B26B-7E5EC44E9C7F")
Set-CsCallQueue -Identity "d2187857-4011-41b2-b44a-2019ee167526" -Users $o.Users

Subsequently, to remove a user, when I execute this script, I would expect it to work (if I do not cast my string as a GUID, it does not remove the item from the array)

$o = Get-CsCallQueue -Identity "d2187857-4011-41b2-b44a-2019ee167526" | Select Users
$o.Users.Remove([GUID]"8a67db3e-46e4-4c76-8b46-720854b6d5b8")
Set-CsCallQueue -Identity "d2187857-4011-41b2-b44a-2019ee167526" -Users $o.Users

I get the following error

Single user not found (9ff75dfd-dfd9-4a1d-b75b-205f26cc3303).
    + CategoryInfo          : NotSpecified: (:) [Set-CsCallQueue], OnlineCmdletException
    + FullyQualifiedErrorId : Unspecified,Microsoft.Rtc.Management.Hosted.CallQueue.SetCsCallQueueCmdlet
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

9ff75dfd-dfd9-4a1d-b75b-205f26cc3303 is a user in $o.Users

$o.Users

Guid
----
b66e8544-a3c3-415f-acf3-dc5b29eacccc
a111dda8-dcfc-4905-b26b-7e5ec44e9c7f
9ff75dfd-dfd9-4a1d-b75b-205f26cc3303
281c1487-8a2c-4ed0-952b-09c0615da6ca

Each of the elements in the array is a GUID

$o.Users[0].GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Guid                                     System.ValueType

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ade68d-5dc0-c598-a659-8b018cef3e26
* Version Independent ID: 67efa086-edb0-2828-cc14-4c245290e4f3
* Content: [Set-CsCallQueue (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-cscallqueue?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsCallQueue.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/Set-CsCallQueue.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

**Comment by sarollins** [comment] 2021-04-15 20:49
The error is valid.  At some point, that user's Enterprise voice enabled status changed, thus, they are not eligible to be a call answer user

**Comment by get-itips** [comment] 2021-04-27 13:10
Hello @sarollins How are you? Before I try this, if I understood well based on your last message, you found out the cause of the error being the user is not EV enabled? Thank you for your clarification.

**Comment by sarollins** [comment] 2021-04-27 13:12
Correct.  Not an issue with the PowerShell cmdlet

Thank you


Sent from my iPhone

On Apr 27, 2021, at 8:10 AM, Andres Mariano Gorzelany ***@***.***> wrote:

﻿

Hello @sarollins<https://github.com/sarollins> How are you? Before I try this, if I understood well based on your last message, you found out the cause of the error being the user is not EV enabled? Thank you for your clarification.

**Comment by get-itips** [comment] 2021-04-27 13:14
Thanks for returning and clarifying that.
@yogkumgit please kindly close.

**Comment by yogkumgit** [comment] 2021-04-27 13:49
@get-itips Thank you very much for the contribution and sharing this explanation. @sarollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-04-27 13:49 UTC
Labels: area:teams / skype
