### ISSUE TITLE
Link in top "Module: sharepoint-pnp" gives a 404 error

### ISSUE THREAD

**Issue by 2ndcahl** [MicrosoftDocs/office-docs-powershell#3322] opened 2019-04-30 12:12 UTC
Link in top "Module: sharepoint-pnp" gives a 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba509b85-58e0-f1f7-8134-4678339c7097
* Version Independent ID: e3837ec6-d90c-35c4-a563-4313ffb11fb6
* Content: [Get-PnPFile (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpfile?view=sharepoint-ps#feedback)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFile.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPFile.md)
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by yogkumgit** [comment] 2019-05-01 10:48
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2019-05-03 02:58
Duplicate of https://github.com/MicrosoftDocs/office-docs-powershell/issues/3229

**Comment by get-itips** [comment] 2019-05-11 13:00
Hello! Good news, the article has been created and does not give a 404 anymore.
We will close this issue. Thanks.

**Comment by VesaJuvonen** [comment] 2019-05-13 06:23
Closing based on the comment from @get-itips and as issue no longer exists.

**Closed by VesaJuvonen** 2019-05-13 06:23 UTC
