### ISSUE TITLE
The -UseSQLSnapshot switch does not work unless run with Farm account

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/office-docs-powershell#1370] opened 2018-06-29 19:14 UTC
Running Export-SPWeb with the -UseSQLSnapshot returns and Access Denied. This can only be run successfully using the SharePoint farm account. Any other account will fail. Verified proper access SharePoint (farm admin + full control in web app user policy), SQL Server (SA), databases (granted db_owner, but SA trumps that anyhow) and backup path (local admin to SharePoint and SQL servers). Created a Premier case to get help with this. After reproducing in lab, MS engineer stated it is a known problem and there are no plans to fix it in SharePoint Server 2013. The problem still exists in SharePoint 2016 and we requested it to be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7709132-eaba-7ae9-8f3d-76fe40cc4420
* Version Independent ID: 7f5b5c75-601b-02d2-fd14-a4092aec52e8
* Content: [Backup-SPSite (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/backup-spsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Backup-SPSite.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-server/Backup-SPSite.md)
* Product: **sharepoint-2016-powershell**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment] 2018-06-29 23:53
Ok, I see what it is doing. When using a SQL snapshot, the context of the export is Central Admin. It will then look up the default user id in the SPWeb in which you're exporting for a particular ID, but that ID may be in Windows Classic mode on a Windows Claims site leading to an access denied.

**Comment by AndreaBarr** [comment] 2018-09-20 22:15
@SharePointBlackBelt Thank you for this feedback

It looks like Trevor answered this for you. I am going to close this issue. If the issue is not resolved please reopen the issue.

**Closed by AndreaBarr** 2018-09-20 22:15 UTC
Labels: area:sp-server-powershell
