### ISSUE TITLE
Connect-ExchangeOnline Erroring when using App-only auth and -DelegatedOrganization

### ISSUE THREAD

**Issue by gesbeckj** [MicrosoftDocs/office-docs-powershell#7110] opened 2021-01-19 19:47 UTC
We are getting an error specifically when using app-only auth and specifying a delegated organization. Interactive auth works for both our tenancy and our delegated tenants. However, app-only auth only works for our tenancy. We are unable to use app-only auth to connect to our delegated clients. 

Anytime we try to specify a delegated organization we get the following error:
New-ExoPSSession : Connecting to remote server outlook.office365.com failed with the following error message :  For
more information, see the about_Remote_Troubleshooting Help topic.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.3\ExchangeOnlineManagement.psm1:426 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchang
   e.Management.ExoPowershellSnapin.NewExoPSSession

**Comment by chrisda** [comment] 2021-01-20 20:04
Closing as duplicate of #7109

**Closed by chrisda** 2021-01-20 20:04 UTC
Labels: area:exchange, duplicate
