### ISSUE TITLE
"Import of transport rules is not supported"

### ISSUE THREAD

**Issue by sinnamingrrl** [MicrosoftDocs/office-docs-powershell#7085] opened 2021-01-14 19:04 UTC
I used

> $file = Export-TransportRuleCollection
> Set-Content -Path "C:\scripts\Rules.xml" -Value $file.FileData -Encoding Byte

to export my transport rules from an O365 Tenant.  I then connected to a new O365 tenant and ran the following:

> [Byte[]]$Data = Get-Content -Path "C:\scripts\transportrules\Rules.xml" -Encoding Byte -ReadCount 0
> Import-TransportRuleCollection -FileData $Data
> 
I recieved the following error:

Import of transport rules is not supported
    + CategoryInfo          : InvalidOperation: (Import of trans...s not supported:String) [Import-TransportRuleCollec
   tion], InvalidOperationException
    + FullyQualifiedErrorId : [Server=PH0PR05MB7589,RequestId=591308ea-4fdc-4d2b-bdf2-0f4b138814d3,TimeStamp=1/14/2021
    7:00:41 PM] [FailureCategory=Cmdlet-InvalidOperationException] 2C654CD5,Microsoft.Exchange.MessagingPolicies.Rule
  s.Tasks.ImportTransportRuleCollection
    + PSComputerName        : outlook.office365.com

So, it appears importing of tranport rules is no longer supported in "Exchange Online"?  If so, please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c167afae-a629-3a14-e5ab-ce0687f5a523
* Version Independent ID: 592c3b09-d9b0-dffc-a3db-2b385f7469eb
* Content: [Import-TransportRuleCollection (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/import-transportrulecollection?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Import-TransportRuleCollection.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/exchange-ps/exchange/Import-TransportRuleCollection.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2021-01-15 18:06
@sinnamingrrl, I'm told import of transport rules has been temporarily disabled. Please open a support case. They should be able to enable specifically for your organization.

**Comment by sinnamingrrl** [comment] 2021-01-15 23:07
Hey Chris, if that is the case, then the article should still be updated to reflect the fact that Import-tranportrulecollection is not currently supported for Exchange online and EOP

**Comment by sushilmaurya13** [comment] 2021-01-19 11:50
Hello, I am also getting same error message when run command:
$file = Export-TransportRuleCollection
Set-Content -Path "C:\scripts\Rules.xml" -Value $file.FileData -Encoding Byte

When MS will enable this for GA as per article.
https://docs.microsoft.com/en-us/powershell/module/exchange/import-transportrulecollection?view=exchange-ps

**Comment by yogkumgit** [comment] 2021-02-04 13:44
@chrisda  Thank you very much for sharing this explanation. @sinnamingrrl Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2021-02-04 13:44 UTC
Labels: area:exchange

**Comment by thakkerjay** [comment] 2021-02-09 23:47
Hello @chrisda,

Thanks for your inputs. As suggested by you, I opened a MS Support case since manual creation of 30+ transport rules from on prem to O365 is not an ideal solution. 

However, to my surprise, the MS Support Engineer just told me that import of transport rules to O365 is disabled by Microsoft and there is no alternative that he could offer. 

Any thoughts/ suggestions would be much appreciated as this is going to be a pain for any migrations we do for our clients. 

Regards,
Jay Thakker

**Comment by chrisda** [comment] 2021-02-11 17:26
@thakkerjay, I asked again, and it was confirmed to me again that the global lack of access to Import-TransportRuleCollection was temporary, and is in the process of being made available again globally. Try again next week (Feb 14 or later). Eventually, it should work.

**Comment by thakkerjay** [comment] 2021-03-10 15:22
Thank you @chrisda for your inputs! The import of transport rules works now.
