### ISSUE TITLE
Running Install-Module -Name ExchangeOnlineManagement gives an error

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/office-docs-powershell#6507] opened 2020-09-14 10:59 UTC
Running the command Import-Module ExchangeOnlineManagement is giving the below error:

```
Import-Module : The specified module 'ExchangeOnlineManagement' was not loaded because no valid module file was found   in any module directory.
At line:1 char:1
+ Import-Module ExchangeOnlineManagement
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ExchangeOnlineManagement:String) [Import-Module], FileNotFoundExce
   ption
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

However, if you run it as follows, it will work without errors. Hence, I believe till this issue is resolved, you may update this article.

`Install-Module -Name ExchangeOnlineManagement -RequiredVersion 1.0.1`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fbe5a2-c138-b566-c094-82ffc3d1b734
* Version Independent ID: 4d69ee5d-5a6d-a203-69fe-bf5441a8b5eb
* Content: [Connect to Exchange Online PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps)
* Content Source: [exchange/docs-conceptual/connect-to-exchange-online-powershell.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/exchange/docs-conceptual/connect-to-exchange-online-powershell.md)
* Service: **exchange-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws** [comment] 2020-09-21 19:28
Hi @ahamin01, thank you for your feedback.

I cannot reproduce this error:
![image](https://user-images.githubusercontent.com/33589238/93812006-69f7e800-fc27-11ea-831d-5ce39c4f6bb5.png)

Please try installing the latest version of the module:
https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#update-the-exo-v2-module

**Comment by yogkumgit** [comment] 2020-09-23 11:17
@dariomws Thank you very much for the contribution and sharing this explanation. @ahamin01 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-09-23 11:17 UTC
Labels: area:exchange

**Comment by KSib** [comment] 2021-01-12 17:10
I also tried the same command as @ahamin01  and it definitely doesn't work as written. I'm trying it on Powershell x64 windows 7.1.0 and I see this:

```
PS C:\Users\[redacted]> Import-Module ExchangeOnlineManagement
Import-Module: The specified module 'ExchangeOnlineManagement' was not loaded because no valid module file was found in any module directory.
```

If it does work for you, that's great, but the documentation should be updated in a way that helps people it doesn't work for.

If I run the following command then it does work:

```
PS C:\Users\[redacted]> Install-Module -Name ExchangeOnlineManagement -RequiredVersion 2.0.3

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
```
