### ISSUE TITLE
Grant-CsOnlineVoiceRoutingPolicy doesn't appear to work for resource accounts assigned to call queues

### ISSUE THREAD

**Issue by kpinel** [MicrosoftDocs/office-docs-powershell#8930] opened 2022-02-08 23:19 UTC
This process was working in Teams module 2.6. Not sure what we are missing as assigning the routing policy used to work prior to V3

Testing using 3.1.1:
```powershell
# RA Account
Get-CsOnlineUser -Identity 5cf1d39a-2b2f-405d-9709-a780210d3034 | fl Alias,OnPremLineURI,EnterpriseVoiceEnabled,HostedVoiceMail,TenantDialPlan,OnlineVoiceRoutingPolicy


Alias                    : RA-Test-For-Kev
OnPremLineUri            :
EnterpriseVoiceEnabled   : True
TenantDialPlan           :
OnlineVoiceRoutingPolicy :

# instance
Get-CsOnlineApplicationInstance | ?{$_.displayName -eq "RA-Test-For-Kev"} | fl

ApplicationId     : 11cd3e2e-fccb-42ad-ad00-878b93575e07
DisplayName       : RA-Test-For-Kev
ObjectId          : 5cf1d39a-2b2f-405d-9709-a780210d3034
PhoneNumber       :
TenantId          : dc0b52a3-68c5-44f7-881d-9383d8850b96
UserPrincipalName : RA-Test-For-Kev@tenant.onmicrosoft.com

# Attempt to assign the policy to the RA using the user object ID
Grant-CsOnlineVoiceRoutingPolicy -Identity 5cf1d39a-2b2f-405d-9709-a780210d3034 -PolicyName AU-International
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPolicy : User does not exist
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.1.1\net472\custom\PsExt\Grant-CsUserOrTenantPolicy.ps1:61 char:13
+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPo ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = 5c...ntUserRequest }:<>f__AnonymousType56`3) [Grant-CsUserPolicy_GrantExpanded], Exception
    + FullyQualifiedErrorId : ClientError,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GrantCsUserPolicy_GrantExpanded

# Confirm that the user object does exist in AzureAD
Get-AzureADUser -ObjectId 5cf1d39a-2b2f-405d-9709-a780210d3034

ObjectId                             DisplayName     UserPrincipalName                             UserType
--------                             -----------     -----------------                             --------
5cf1d39a-2b2f-405d-9709-a780210d3034 RA-Test-For-Kev RA-Test-For-Kev@tenant.onmicrosoft.com Member
```
Using Teams 2.6.0
```powershell
Grant-CsOnlineVoiceRoutingPolicy -Identity 5cf1d39a-2b2f-405d-9709-a780210d3034 -PolicyName AU-International

Get-CsOnlineUser -Identity 5cf1d39a-2b2f-405d-9709-a780210d3034 | fl Alias,OnPremLineURI,EnterpriseVoiceEnabled,HostedVoiceMail,TenantDialPlan,OnlineVoiceRoutingPolicy


Alias                    : RA-Test-For-Kev
OnPremLineURI            :
EnterpriseVoiceEnabled   : True
HostedVoiceMail          :
TenantDialPlan           :
OnlineVoiceRoutingPolicy : AU-International
```

**Comment by kpinel** [comment] 2022-02-09 04:31
I note that issue 8932 has just been logged for the same problem

**Comment by BrenCollinsAmundi** [comment] 2022-02-16 18:07
I have the same problem assigning a Teams Compliance recording policy using the command Teams powershell cmdlet "Grant-CsTeamsComplianceRecordingPolicy"

For some users I am getting the error 
"Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPolicy : User does not exist"

I can however complete a Get-CsOnlineUser for the same identifier and it outputs fine.
and I can complete the same "Grant-CsTeamsComplianceRecordingPolicy" command with my account successfully

I was running MicrosoftTeams v3.0.0 and upgraded to MicrosoftTeams v3.1.1 but still no success

**Comment by BrenCollinsAmundi** [comment] 2022-02-16 18:38
I have confirmed the command works if I use MicrosoftTeams v2.6.0

**Comment by dariomws** [comment] 2022-02-19 08:06
Hi all,

Thank you for your feedback.

I have tested it with 3.1.1 in a lab tenant and it works for me.

If you still have this issue, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment] 2022-02-20 12:50
@dariomws Thank you very much for the contribution and sharing this explanation. @kpinel Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-02-20 12:50 UTC
Labels: area:teams / skype, support-request

**Comment by Jonny-P-W** [comment] 2022-05-31 12:49
I have the same issue using MicrosoftTeams module 4.3.0.  Does anyone know how to fix? @kpinel @dariomws @DEberhardt @DanScottExpo

**Comment by DEberhardt** [comment] 2022-05-31 12:57
I usually pipe the Object into the grant command: `Get-CsOnlineUser "$UPN" | Grant-CsOnlineVoiceRoutingPolicy -PolicyName x`

We haven't had any issues with this approach with V4.x

Hope this helps

**Comment by Jonny-P-W** [comment] 2022-05-31 15:17
@DEberhardt using the pipe worked. thanks
