### ISSUE TITLE
Set-SPOSite on Group Sites is now giving an error.

### ISSUE THREAD

**Issue by henryed07** [MicrosoftDocs/office-docs-powershell#5316] opened 2020-04-17 16:01 UTC
I've got an Azure Runbook running the following to update a Teams Site to turn of External Sharing. It's been working fine up until a week ago.
 Connect-SPOService -Url $adminSiteUrl -Credential $myCred
    Get-SPOSite -Identity  $SiteUrl | select sharingcapability
    Set-SPOSite -Identity $SiteUrl -SharingCapability Disabled

**Error:**

Unexpected error: [Site Address] is a Groups site collection. The valid parameters for this type of site collection are '-Identity', '-AllowSelfServiceUpgrade', '-DefaultLinkPermission', '-DefaultSharingLinkType', '-DenyAddAndCustomizePages', '-DisableCompanyWideSharingLinks', '-DisableSharingForNonOwners', '-LockState', '-Owner', '-ResourceQuota', '-ResourceQuotaWarningLevel', '-SandboxedCodeActivationCapability', '-SharingCapability', '-ShowPeoplePickerSuggestionsForGuestUsers', '-SocialBarOnSitePagesDisabled', '-StorageQuota', '-StorageQuotaReset', and '-StorageQuotaWarningLevel'.

However, nothing has change from our end...

**Comment by yogkumgit** [comment] 2020-04-20 10:56
@officedocsbot assign @yogkumgit

**Comment by get-itips** [comment] 2020-04-20 16:02
@henryed07 How are you? Are you still facing this error?
Tried to reproduce to verify if we need to impact the documentation however I could set SharingCapability to Disabled on a Groups sc without issues.

**Comment by henryed07** [comment] 2020-04-20 17:11
Hi, 
Yes still getting the issue - looked at the Runbook and it's all failed - so its still not working. Should I log this with Microsoft Support too?

**Comment by get-itips** [comment] 2020-04-20 17:13
> Hi,
> Yes still getting the issue - looked at the Runbook and it's all failed - so its still not working. Should I log this with Microsoft Support too?

Thanks for getting back and share your update.
Yes please, I kindly suggest opening a support ticket, as I could not reproduce and here, we are limited to documentation issues.
If, for any reason, I detect that the cmdlet behavior has changed, I'll impact the article.
Thank you

**Comment by henryed07** [comment] 2020-04-21 09:00
Hi, 
I've logged a ticket this morning. 
Henry

**Comment by yogkumgit** [comment] 2020-04-21 11:56
@get-itips Thank you very much for the contribution and sharing this explanation. @henryed07 
Hope this comment is helpful for you and thanks for opening a service ticket. We proceed here to close this issue. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2020-04-21 11:56 UTC
Labels: area:spo-powershell
