### ISSUE TITLE
Error on adding JSLink to calculated site column

### ISSUE THREAD

**Issue by HTEredrock** [MicrosoftDocs/office-docs-powershell#956] opened 2018-05-02 13:16 UTC
Hi,

I'm getting the error `The formula contains a syntax error or is not 
supported.` when setting the JSLink property (As defined above) of a calculated site column and using the `-UpdateExistingLists` flag. It works fine if I do not include the `-UpdateExistingLists` flag

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05960454-d3f7-83b0-f342-5eac9afbb826
* Version Independent ID: 4e74fecb-6506-3652-c0cd-cb6270c0a3f9
* Content: [Set-PnPField (sharepoint-pnp)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpfield?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPField.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPField.md)
* Service: **unspecified**
* GitHub Login: @techwriter40
* Microsoft Alias: **kirks**

**Comment by nsshommo** [comment] 2018-05-02 16:33
@HTEredrock Thanks for letting us know your query. We will get back to you very soon.

@VesaJuvonen Can you help me on this one?

**Comment by erwinvanhunen** [comment] 2018-05-11 11:45
Hi, what does the formula look like? I just tried it here with a calculated sitecolumn, which have been added to a list, but I receive no error message while setting the JSLink property and using the -UpdateExistingLists flag

**Comment by VesaJuvonen** [comment] 2018-05-12 02:25
Hi @HTEredrock - like noted by @erwinvanhunen, we would need to have the repro clarified so that we can solve what's wrong. Right now we cannot move as we cannot reproduce the issue. Thanks for the additional details advance.

**Comment by HTEredrock** [comment] 2018-05-18 08:54
Hi @VesaJuvonen @erwinvanhunen , apologies for the slow response.

The field is question is a calc field with the following code:
```
=IF(PublishCalc=TRUE;CONCATENATE("<div><table style='float:left'><tr><td rowspan='2' style='width:70px'><img style='width:55px' src='";ImageAvailableURL;"'></img></td><td><a href='"&PageURLcalc&"?Block="&Title&"' style='font-size: 17px;'>";TitleAndDate;"</a></td></tr><tr><td style='padding-bottom: 15px; font-size: 13px;' >";Location;"</td></tr></table></div>");CONCATENATE("<div><table style='float:left'><tr><td rowspan='2' style='width:70px'><img style='width:55px' src='";ImageUnavailableURL;"'></img></td><td style='font-size: 17px;'>";TitleAndDate;"</a></td></tr><tr><td style='padding-bottom: 15px; font-size: 13px;' >";Location;"</td></tr></table></div>"))
```

Basically what it does is build up some HTML structure, which I then render with a code snippet in the JSLink property. This works fine when I add the JSLink at a list level, however when adding at a Site Column, it gave me the error mentioned above in my first post.

**Comment by HTEredrock** [comment] 2018-06-04 07:53
Just to follow up here, I think this may be related to another issue we are experiencing on the Tenant. Will confirm details when the other issue has been resolved and I have tested the above again.

Please keep the issue open until then.

**Comment by AndreaBarr** [comment] 2018-09-19 23:04
@HTEredrock Thank you for this feedback

We want to make sure your PnP issue is handled appropriately.

We have a separate repo for the PnP PowerShell issues. We want your issue to get the proper attention it deserves.  

Please open your issue in this repo: https://github.com/SharePoint/PnP-PowerShell  
 
I am going to close this issue so that we can track to correct one in the PnP PowerShell repo.

**Closed by AndreaBarr** 2018-09-19 23:04 UTC
Labels: area:pnp-powershell
