### ISSUE TITLE
Import failure of module MicrosoftTeams 4.0.0 after import MSOnline

### ISSUE THREAD

**Issue by fsilvestre** [MicrosoftDocs/office-docs-powershell#9107] opened 2022-03-15 21:51 UTC
Transcript01 start a new session importing MSOnline before MicrosoftTeams [https://pastebin.com/hbXeeD28](url)

Transcript02 start a new session importing only MicrosoftTeams [https://pastebin.com/Q0NacXS2](url)

**Comment by dariomws** [comment] 2022-03-25 08:10
Hi @fsilvestre, thank you for your feedback.

I cannot see the links you are sharing, but I cannot reproduce your issue:
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/33589238/160080738-80f87e3f-dec8-4a57-b057-6361c962ac16.png">

**Comment by dariomws** [comment] 2022-03-25 08:11
@fsilvestre, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by yogkumgit** [comment] 2022-03-25 13:27
@dariomws Thank you very much for the contribution and sharing this explanation. @fsilvestre Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Closed by yogkumgit** 2022-03-25 13:27 UTC
Labels: area:teams, support-request
